package gocomments

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// numbersFound runs Check over a file body and returns just the numbers, which
// is what every case here asserts on.
func numbersFound(t *testing.T, body string) []string {
	t.Helper()
	var out []string
	for _, hit := range Check("x.go", "package p\n\n"+body+"\n") {
		out = append(out, hit.Number)
	}
	return out
}

func TestADigitCountIsReported(t *testing.T) {
	assert.Equal(t, []string{"3"}, numbersFound(t, "// the walk has 3 phases"))
}

func TestAWordCountIsReported(t *testing.T) {
	assert.Equal(t, []string{"once"}, numbersFound(t, "// the sweep runs once"))
}

// A digit against a letter is a name, which is how a reference survives.
func TestANameCarryingDigitsIsLeftAlone(t *testing.T) {
	assert.Empty(t, numbersFound(t, "// sha256 over the amd64 payload, capped at 10ms"))
}

func TestAQualifiedNameIsLeftAlone(t *testing.T) {
	assert.Empty(t, numbersFound(t, "// sync.Once guards it, and net/http serves it"))
}

func TestAURLIsLeftAlone(t *testing.T) {
	assert.Empty(t, numbersFound(t, "// see https://example.com/v2/spec"))
}

// A fragment is its own token, because `#` cannot sit inside a name. So a
// numbered anchor reads as a count, which is the citation the remedy tells the
// author to spell as a slug.
func TestAFragmentAfterAURLIsReadOnItsOwn(t *testing.T) {
	assert.Equal(t, []string{"3"}, numbersFound(t, "// see https://example.com/spec#section-3"))
}

// The exemptions that let a citation, a protocol answer and a cost stay.
func TestSectionSignExemptsItsNumber(t *testing.T) {
	assert.Empty(t, numbersFound(t, "// the rule in §7.3 governs this"))
}

func TestHTTPExemptsAStatusCode(t *testing.T) {
	assert.Empty(t, numbersFound(t, "// the proxy answers HTTP 403 here"))
}

func TestABareStatusCodeIsStillACount(t *testing.T) {
	assert.Equal(t, []string{"403"}, numbersFound(t, "// the proxy answers 403 here"))
}

func TestACurrencySignExemptsTheAmount(t *testing.T) {
	assert.Empty(t, numbersFound(t, "// the run costs $1.43 of budget"))
}

// A word that merely contains a number word is a word.
func TestAWordContainingANumberWordIsLeftAlone(t *testing.T) {
	assert.Empty(t, numbersFound(t, "// someone has to own this"))
}

// A directive addresses a tool, so it carries no prose to go stale.
func TestADirectiveIsSkipped(t *testing.T) {
	assert.Empty(t, numbersFound(t, "//go:build go1.27"))
}

// A generated file's author is a program, and telling a program to write
// differently is not a repair.
func TestAGeneratedFileIsSkipped(t *testing.T) {
	src := "// Code generated by stringer. DO NOT EDIT.\n\npackage p\n\n// holds 4 entries\n"
	assert.Empty(t, Check("z.go", src))
	assert.True(t, IsGenerated(src))
}

// The marker only counts above the package clause, so ordinary prose quoting it
// does not silence a whole file.
func TestTheMarkerBelowThePackageClauseDoesNotSkip(t *testing.T) {
	src := "package p\n\n// Code generated by hand. DO NOT EDIT.\n// holds 4 entries\n"
	assert.False(t, IsGenerated(src))
	assert.NotEmpty(t, Check("z.go", src))
}

// A block comment carries several lines, and each is read on its own.
func TestABlockCommentIsReadLineByLine(t *testing.T) {
	assert.Equal(t, []string{"two"}, numbersFound(t, "/*\nthe cache holds two shards\n*/"))
}

// The position is what a report points at, so it has to name the real line.
func TestTheHitNamesItsLineAndColumn(t *testing.T) {
	hits := Check("x.go", "package p\n\n// fine\n// holds 5 entries\n")
	require.Len(t, hits, 1)
	assert.Equal(t, 4, hits[0].Line)
	assert.Equal(t, 10, hits[0].Col)
}

// A tree mid-edit is exactly when this runs, so a file that cannot compile
// still reports its comments rather than an error.
func TestAFileThatDoesNotCompileIsStillRead(t *testing.T) {
	assert.Equal(t, []string{"6"}, numbersFound(t, "// holds 6 entries\nfunc ( {"))
}
