package slopfix_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/wow-look-at-my/slopfix"
)

// prose puts a document to Fix with no path, which is how a caller vouches for
// text as prose.
func prose(content string) slopfix.Repair {
	return slopfix.Fix(slopfix.Request{Content: content})
}

// The join is structure, so it is held here: a wrapped paragraph comes back as
// a single line. What the count rule writes is held in rules/.
func TestFixJoinsAWrapAndCutsACount(t *testing.T) {
	repair := prose("There are three sections in the payload,\nand each one is read.\n")
	assert.True(t, repair.Changed)
	assert.Equal(t, 1, strings.Count(strings.TrimRight(repair.Text, "\n"), "\n")+1)
	assert.NotEmpty(t, repair.Removed)
}

func TestFixLeavesACleanDocumentAlone(t *testing.T) {
	doc := "A paragraph that needs no repair at all.\n"
	repair := prose(doc)
	assert.False(t, repair.Changed)
	assert.Equal(t, doc, repair.Text)
	assert.Empty(t, repair.Removed)
	assert.Empty(t, repair.Findings)
}

// A fence is data. Joining its lines changes what the code says.
func TestFixKeepsAFencedBlockWhole(t *testing.T) {
	doc := "# Title\n\n```sh\nfirst\nsecond\n```\n"
	repair := prose(doc)
	assert.False(t, repair.Changed)
	assert.Equal(t, doc, repair.Text)
}

// A sentence whose halves share a subject divides at the conjunction, and the
// new sentence names the subject again. Neither half is a fragment.
func TestFixRestatesTheSharedSubject(t *testing.T) {
	long := "The gate reads every file in the session and refuses the write when any one of them carries a finding that a rewrite cannot repair on its own.\n"
	repair := prose(long)
	assert.True(t, repair.Changed)
	assert.Equal(t,
		"The gate reads every file in the session. The gate refuses the write when any one of them carries a finding that a rewrite cannot repair on its own.\n",
		repair.Text)
	assert.Empty(t, repair.Findings)
}

// The prose repair runs on the joined paragraph, so a rule sees the sentence
// the hand wrap split apart.
func TestFixRepairsProseAcrossAWrap(t *testing.T) {
	repair := prose("A sentence that is wrapped\nand that doesn't expand.\n")
	assert.True(t, repair.Changed)
	assert.NotContains(t, repair.Text, "doesn't", "the rule reached across the wrap")
	assert.Empty(t, repair.Findings)
}

func TestFixRepairsTheMechanicalRules(t *testing.T) {
	repair := prose("It doesn't matter; a caller should wait, so the write fails.\n")
	assert.True(t, repair.Changed)
	// The contraction, the semicolon and the modal are each somebody's rule.
	assert.Empty(t, repair.Findings)
}

// A list item is prose, and its marker survives the repair.
func TestFixKeepsAListMarker(t *testing.T) {
	repair := prose("- It doesn't run.\n")
	assert.True(t, repair.Changed)
	assert.True(t, strings.HasPrefix(repair.Text, "- "))
}

// A fence is data, so no prose rule reaches inside it.
func TestFixLeavesProseInsideAFenceAlone(t *testing.T) {
	doc := "```sh\nit doesn't run; nothing does\n```\n"
	repair := prose(doc)
	assert.False(t, repair.Changed)
	assert.Equal(t, doc, repair.Text)
}

func TestFixFileWritesTheRepair(t *testing.T) {
	path := filepath.Join(t.TempDir(), "doc.md")
	require.NoError(t, os.WriteFile(path, []byte("It doesn't run.\n"), 0o644))

	repair, err := slopfix.FixFile(path)
	require.NoError(t, err)
	assert.True(t, repair.Changed)

	written, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Equal(t, repair.Text, string(written), "the file holds what the repair answered")
}

func TestFixFileLeavesACleanFileAlone(t *testing.T) {
	path := filepath.Join(t.TempDir(), "doc.md")
	require.NoError(t, os.WriteFile(path, []byte("A clean line.\n"), 0o400))

	repair, err := slopfix.FixFile(path)
	require.NoError(t, err)
	assert.False(t, repair.Changed)
}

func TestOnlyTheNamedRuleRuns(t *testing.T) {
	doc := "There are three sections,\nand each is read.\n"
	repair := slopfix.Fix(slopfix.Request{Content: doc, Rules: []slopfix.Rule{slopfix.RuleCounts}})

	assert.NotEmpty(t, repair.Removed)
	assert.Contains(t, repair.Text, "\nand each is read.")
	assert.Empty(t, repair.Findings)
}

func TestSourceGetsTheTombstoneRuleAndNoProseRule(t *testing.T) {
	src := "// This used to read the flag.\nx := \"a sentence far too long to pass the cap\"\n"
	repair := slopfix.Fix(slopfix.Request{Content: src, Path: "a.go"})

	assert.True(t, repair.Changed)
	assert.NotContains(t, repair.Text, "used to read")
	assert.Empty(t, repair.Findings)
}

// A generator writes its output again on the next run, so no repair lands
// there. Joining the marker line with the next one would also stop tools from
// reading the file as generated.
func TestAGeneratedFileIsNeitherRepairedNorReported(t *testing.T) {
	src := "// Code generated by sqlc. DO NOT EDIT.\n// versions:\n//   sqlc v1.28.0\n\npackage dbgen\n\n" +
		"// Prune used to read the flag.\n" + strings.Repeat("// It deletes a row that is stale on both clocks, and keeps the rest.\n", 16) +
		"func Prune() {}\n"
	for name, run := range map[string]func(slopfix.Request) slopfix.Repair{"fix": slopfix.Fix, "report": slopfix.Report} {
		repair := run(slopfix.Request{Content: src, Path: "dbgen/jobs.sql.gen.go"})
		assert.False(t, repair.Changed, name)
		assert.Equal(t, src, repair.Text, name)
		assert.Empty(t, repair.Kept, name)
		assert.Empty(t, repair.Findings, name)
	}

	// The same text without the marker is the author's own, and every rule reads it.
	own := strings.Replace(src, "// Code generated by sqlc. DO NOT EDIT.\n", "", 1)
	assert.NotEmpty(t, slopfix.Report(slopfix.Request{Content: own, Path: "dbgen/jobs.go"}).Kept)
}

// A document a generator writes carries the marker on its first line, and is
// exempt the way a generated source file is.
func TestAGeneratedDocumentIsNeitherRepairedNorReported(t *testing.T) {
	body := "There are three sections in the payload,\nand each one is read.\n"
	for path, marker := range map[string]string{
		"docs/api.md":     "<!-- Code generated by apidoc. DO NOT EDIT. -->\n",
		"docs/routes.txt": "# Code generated by buildhost routes. DO NOT EDIT.\n",
	} {
		src := marker + "\n" + body
		repair := slopfix.Fix(slopfix.Request{Content: src, Path: path})
		assert.False(t, repair.Changed, path)
		assert.Empty(t, slopfix.Report(slopfix.Request{Content: src, Path: path}).Findings, path)
		assert.Empty(t, slopfix.CheckContent(path, src), path)
		assert.True(t, slopfix.Fix(slopfix.Request{Content: body, Path: path}).Changed, "%s without the marker is the author's own", path)
	}
}

// A file .gitattributes marks linguist-generated needs no marker in its bytes.
// A route table a program renders and a CI gate compares is one: a joined line
// breaks the gate.
func TestAPathMarkedGeneratedIsNeitherRepairedNorReported(t *testing.T) {
	root := t.TempDir()
	out, err := exec.Command("git", "-C", root, "init", "-q").CombinedOutput()
	require.NoError(t, err, string(out))
	require.NoError(t, os.MkdirAll(filepath.Join(root, "docs"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(root, ".gitattributes"), []byte("docs/routes.txt linguist-generated\n"), 0o644))
	var table strings.Builder
	for _, route := range []string{"/", "/__signin", "/api/v1/projects", "/api/v1/tokens", "/llms.txt"} {
		table.WriteString(route + " {GET}\n")
	}
	path := filepath.Join(root, "docs", "routes.txt")
	require.NoError(t, os.WriteFile(path, []byte(table.String()), 0o644))

	assert.True(t, slopfix.Fix(slopfix.Request{Content: table.String(), Path: "routes.txt"}).Changed, "an unmarked table is joined like any paragraph")
	assert.Empty(t, slopfix.CheckContent(path, table.String()))
	assert.False(t, slopfix.Fix(slopfix.Request{Content: table.String(), Path: path}).Changed)
	tree := slopfix.FixTree(root)
	for _, finding := range tree.Findings {
		assert.NotEqual(t, path, finding.Path)
	}
	assert.NotContains(t, tree.Repaired, path)
	got, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Equal(t, table.String(), string(got))
}

// A status code and a migration number are values, and a repair that cut them
// changed what the sentence says.
func TestFixLeavesValuesThatAreNotCounts(t *testing.T) {
	for _, doc := range []string{
		"Any status other than 201 or 409 there triggers a full upload.\n",
		"The row insert and the 201 responses are shared with a full upload.\n",
		"A 401 or 403 confirms that the module exists.\n",
		"Migration 015 defines it.\n",
		"It answers HTTP 404 for a miss.\n",
	} {
		repair := slopfix.Fix(slopfix.Request{Content: doc, Path: "a.md"})
		assert.Equal(t, doc, repair.Text)
	}
}

// A count beside a size is still a count. The repair cuts the count and keeps
// the sentence readable.
func TestFixCutsACountBesideASize(t *testing.T) {
	repair := slopfix.Fix(slopfix.Request{Content: "It sends one create and four 1 MiB `?offset=` PATCH requests.\n", Path: "a.md"})
	assert.Equal(t, "It sends one create and 1 MiB `?offset=` PATCH requests.\n", repair.Text)
}

// A size ahead of its noun goes whole, number and unit, so no vague word
// stands in front of the unit.
func TestFixCutsASizeAheadOfItsNoun(t *testing.T) {
	repair := slopfix.Fix(slopfix.Request{Content: "It assembles a larger file in 64 MiB chunks by default.\n", Path: "a.md"})
	assert.Equal(t, "It assembles a larger file in chunks by default.\n", repair.Text)
}

// What the prose rules write is stated in rules/, entry by entry. What this
// holds is the routing: a document path reaches them at all.
func TestADocumentPathStillGetsTheProseRules(t *testing.T) {
	doc := "It doesn't expand.\n"
	repair := slopfix.Fix(slopfix.Request{Content: doc, Path: "a.md"})
	assert.True(t, repair.Changed)
	assert.NotEqual(t, doc, repair.Text)
}

// A named ID repairs that rule and leaves its siblings alone, which is what
// makes an ID worth naming at all.
func TestANamedIDRepairsThatRuleAlone(t *testing.T) {
	doc := "It should work; that is fine, we can't stop.\n"

	semicolon := slopfix.Fix(slopfix.Request{
		Content: doc,
		Rules:   []slopfix.Rule{slopfix.RuleEnglish},
		IDs:     []string{"english/semicolon"},
	})
	contraction := slopfix.Fix(slopfix.Request{
		Content: doc,
		Rules:   []slopfix.Rule{slopfix.RuleSTE},
		IDs:     []string{"ste/contraction"},
	})

	// Each named ID repairs the document, and both answers differ.
	assert.NotEqual(t, doc, semicolon.Text)
	assert.NotEqual(t, doc, contraction.Text)
	assert.NotEqual(t, semicolon.Text, contraction.Text)
}

// A finding outside the named ID is neither repaired nor reported, so a caller
// that asks for a rule is not handed the rest of the category. The named rule
// itself is repaired and reports nothing afterwards.
func TestANamedIDLeavesTheRestOfItsCategoryAlone(t *testing.T) {
	doc := "There are three sections; each is read.\n"
	repair := slopfix.Fix(slopfix.Request{
		Content: doc,
		Rules:   []slopfix.Rule{slopfix.RuleCounts},
		IDs:     []string{"counts/stated-count"},
	})

	// The count is repaired, the semicolon beside it is left standing.
	assert.NotEmpty(t, repair.Removed)
	assert.Contains(t, repair.Text, ";")
	assert.Empty(t, repair.Findings)
}

// Naming an ID keeps every other rule's repair off the file, the whole-line
// strip included. A caller that asked for a number repair and got a deleted
// doc line has had another rule applied to it unasked.
func TestANamedIDKeepsTheWholeLineStripOff(t *testing.T) {
	src := "// Add inserts elem. It returns true when the element was added,\n" +
		"// or false when it was already present.\nfunc Add() {}\n"

	repair := slopfix.Fix(slopfix.Request{
		Content: src,
		Path:    "set.go",
		IDs:     []string{"comments/number"},
	})
	assert.Equal(t, src, repair.Text, "no number is stated here, so nothing changes")
}

// Sentences from a real document, each of which a count cut once left saying
// something false or ungrammatical. A duration, a status code, a partitive and
// a sentence-initial cut each keep what the reader needs.
func TestACountCutLeavesTheSentenceTrue(t *testing.T) {
	for _, c := range []struct {
		in        string
		forbidden string
	}{
		{"So readiness is its own statement, re-checked every 15 minutes, and logged at startup.\n", "every minutes"},
		{"No caller can fix that, and a 404 buries it.\n", "a buries"},
		{"Inside those namespaces a caller needs one of two things.\n", "one of things"},
		{"Either of the other two confirms the module exists.\n", "the other confirms"},
	} {
		t.Run(c.in, func(t *testing.T) {
			repair := prose(c.in)
			assert.NotContains(t, repair.Text, c.forbidden)
		})
	}
}

// A cut at the front of a sentence leaves the next word to start it.
func TestACountCutAtTheStartCapitalizesWhatFollows(t *testing.T) {
	for _, in := range []string{
		"Two defects compounded, and the reader saw neither.\n",
		"Two ambiguities are resolved deliberately here.\n",
	} {
		t.Run(in, func(t *testing.T) {
			repair := prose(in)
			require.NotEmpty(t, repair.Text)
			first := []rune(repair.Text)[0]
			assert.False(t, first >= 'a' && first <= 'z', "sentence starts lowercase: %q", repair.Text)
		})
	}
}

func TestEveryCategoryNamesItsRules(t *testing.T) {
	for _, rule := range slopfix.AllRules {
		ids := slopfix.IDsFor(rule)
		assert.False(t, ids.IsEmpty(), "%s names no rule", rule)
		for id := range ids.All() {
			assert.True(t, strings.HasPrefix(id, string(rule)+"/"), "%s is not under %s", id, rule)
		}
	}
	assert.True(t, slopfix.IDsFor(slopfix.Rule("nosuch")).IsEmpty())
}
