package slopfix_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/wow-look-at-my/slopfix"
)

// Each case is text a fix over a real repository mangled.

// A count reworded beside a bare number it shares a clause with read half done.
func TestEveryCountInAClauseReadsTheSameWay(t *testing.T) {
	in := "- go-toolchain warns at 500 lines and errors at 750. Extract into a topical file rather than growing one.\n"
	got := slopfix.Fix(slopfix.Request{Path: "AGENTS.md", Content: in})
	assert.Equal(t, "- go-toolchain warns at many lines and errors at a higher count. Extract into a topical file rather than growing one.\n", got.Text)
}

// A pattern cut ran inside a quotation and left `no ".`.
func TestAQuotationSurvivesTheRepair(t *testing.T) {
	in := "- Comments state the invariant and why, in short sentences and active voice. No changelogs, no dates, no \"this used to\".\n"
	got := slopfix.Fix(slopfix.Request{Path: "AGENTS.md", Content: in})
	assert.Contains(t, got.Text, `no "this used to".`)
}

// A cut left a comment on "a consumer that.".
func TestACommentCutNeverEndsOnAnOpener(t *testing.T) {
	in := "package mirror\n\n" +
		"// recordFailure counts a failure and parks a subscription that keeps failing.\n" +
		"//\n" +
		"// Parking is loud, not quiet: the subscription stays in the store, marked\n" +
		"// disabled with the reason, so an operator sees a consumer that stopped being\n" +
		"// told rather than that silently never was.\n" +
		"func recordFailure() {\n\tlimit := 3\n\tif limit <= 0 {\n\t\tlimit = 1\n\t}\n}\n"
	got := slopfix.Fix(slopfix.Request{Path: "internal/mirror/notify.go", Content: in})
	assert.NotContains(t, got.Text, "consumer that.")
	assert.NotContains(t, got.Text, "rather than that.")
}

// sqlc output lost the line break after its generated-file marker.
func TestAGeneratedFileKeepsItsMarkerLine(t *testing.T) {
	in := "// Code generated by sqlc. DO NOT EDIT.\n// versions:\n//   sqlc v1.31.1\n\npackage dbgen\n"
	got := slopfix.Fix(slopfix.Request{Path: "internal/database/dbgen/db.gen.go", Content: in})
	assert.Equal(t, in, got.Text)
	assert.True(t, strings.HasPrefix(got.Text, "// Code generated by sqlc. DO NOT EDIT.\n"))
}
