// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: `(?s)(  +)(?s:.*)`

package commentlength


import "github.com/wow-look-at-my/go-regex-compiler/match"



import "unicode/utf8"

// englishPat2At reports whether input fully matches the regex `(?s)(  +)(?s:.*)`.
func englishPat2At(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		// Invalid UTF-8 decodes as (RuneError, 1) and is matched as U+FFFD,
		// exactly like regexp: each bad byte is one U+FFFD rune.
		r, size := utf8.DecodeRuneInString(input[i:])
		switch state {

		case 0:
			switch {
			case r == ' ': state = 1
			default: return false
			}
		case 1:
			switch {
			case r == ' ': state = 2
			default: return false
			}
		case 2:
			switch {
			case match.InRange(r, '\x00', '\x1f'): state = 3
			case r == ' ': state = 2
			case match.InRange(r, '!', '\U0010ffff'): state = 3
			default: return false
			}
		case 3:
			switch {
			case match.InRange(r, '\x00', '\U0010ffff'): state = 3
			default: return false
			}
		default:
			return false
		}
		i += size
	}

	switch state {
	case 2, 3:
		return true
	default:
		return false
	}
}

// englishPat2FindIndex returns the submatch index slice for the regex `(?s)(  +)(?s:.*)`,
// or nil if the input does not match. It is a COMPILED tagged-DFA register
// machine: a straight-line state machine that records capture-group byte offsets
// into an integer register file in a single left-to-right pass — no NFA program,
// live-position list, or epsilon-closure at run time. Each config that is live
// in a state owns a block of the register file; a transition sets a block's slot
// to the current position when a group boundary is crossed, or copies it from
// the source config's block. At end of input the winning config's block holds
// the capture offsets. The slice layout matches
// regexp.Regexp.FindStringSubmatchIndex: pair (2*g, 2*g+1) is group g's
// [start, end) byte offsets, index 0 is the whole match, and a group that did
// not participate is (-1, -1). It allocates only the result slice and is safe
// for concurrent use (all state is local).
func englishPat2FindIndex(input string) []int {
	var reg [12]int
	for i := range reg {
		reg[i] = -1
	}
	reg[2] = 0
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return nil
		}
		np := i + size
		switch state {
		case 0:
			if r != ' ' { return nil }
			state = 1
		case 1:
			if r != ' ' { return nil }
			reg[7] = np; reg[11] = np; reg[6] = reg[2]; reg[10] = reg[2]; state = 2
		case 2:
			switch {
			case match.InRange(r, '\x00', '\x1f'): reg[2] = reg[6]; reg[3] = reg[7]; state = 3
			case r == ' ': reg[7] = np; reg[11] = np; reg[6] = reg[2]; reg[10] = reg[2]; state = 2
			case match.InRange(r, '!', '\U0010ffff'): reg[2] = reg[6]; reg[3] = reg[7]; state = 3
			default:
				return nil
			}
		case 3:
			if !(match.InRange(r, '\x00', '\U0010ffff')) { return nil }
			reg[6] = reg[2]; reg[7] = reg[3]; state = 3
		default:
			return nil
		}
		i += size
	}
	switch state {
	case 3:
		result := make([]int, 4)
		result[0] = 0
		result[1] = len(input)
		copy(result[2:], reg[6:8])
		return result
	case 2:
		result := make([]int, 4)
		result[0] = 0
		result[1] = len(input)
		copy(result[2:], reg[10:12])
		return result
	default:
		return nil
	}
}

// englishPat2Find returns captured groups for the regex `(?s)(  +)(?s:.*)`.
// Returns nil if the input does not match. Index 0 is the entire match,
// indices 1..N are capture groups. A group that did not participate in the
// match yields "" (parity with regexp.Regexp.FindStringSubmatch); use
// englishPat2FindIndex to distinguish an absent group (offset pair -1) from an
// empty one.
func englishPat2Find(input string) []string {
	idx := englishPat2FindIndex(input)
	if idx == nil {
		return nil
	}
	result := make([]string, 2)
	for g := 0; g < 2; g++ {
		s, e := idx[g*2], idx[g*2+1]
		if s >= 0 && e >= 0 && s <= len(input) && e <= len(input) {
			result[g] = input[s:e]
		}
	}
	return result
}

// englishPat2Names returns the names of the capture groups for the regex
// `(?s)(  +)(?s:.*)`. The slice has one entry per group index: index 0 (the
// whole match) is always "", and an unnamed group is "". This is parity with
// regexp.Regexp.SubexpNames.
func englishPat2Names() []string {
	return []string{"", ""}
}

