package commentlength

import (
	"slices"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The Go path reads a map, and Go randomises map iteration. So the answer has
// to be sorted before it leaves, or Fix splices with stale line numbers. Repeat
// the call: one pass agrees with the file order about half the time.
func TestTheBlocksComeBackInFileOrder(t *testing.T) {
	essay := "// The point.\n//\n// Then a paragraph of elaboration that runs well past the length of the\n// declaration it sits above, several lines of it, saying little.\n"
	src := "package p\n\n" + essay + "const a = 1\n\n" + essay + "const b = 2\n\n" + essay + "const c = 3\n"

	for range 50 {
		got := blocks("x.go", src)
		require.Len(t, got, 3)
		starts := make([]int, 0, len(got))
		for _, b := range got {
			starts = append(starts, b.start)
		}
		require.True(t, slices.IsSorted(starts), "blocks out of file order: %v", starts)
	}
}

// These pin the three places this rule had drifted from go-toolchain's
// commentspan analyzer, which is the gate every repository here is measured by.

const generatedHeader = "// Code generated by stringer. DO NOT EDIT.\n"

// commentspan returns before measuring anything in a generated file. Nobody
// can act on a finding there: the fix belongs in the generator.
func TestAGeneratedFileIsSkipped(t *testing.T) {
	essay := strings.Repeat("// A long explanation that runs well past the code.\n", 8)
	body := "package p\n\n" + essay + "const p = 1\n"

	require.NotEmpty(t, Check("x.go", body), "the control must report without the marker")
	assert.Empty(t, Check("x.go", generatedHeader+body))
}

// The marker is a header, so the same text further down the file is prose.
func TestTheGeneratedMarkerIsReadInTheHeaderOnly(t *testing.T) {
	essay := strings.Repeat("// A long explanation that runs well past the code.\n", 8)
	src := "package p\n\nconst q = 2\n\n" + generatedHeader + essay + "const p = 1\n"
	assert.NotEmpty(t, Check("x.go", src))
}

// The hash family carries the same marker.
func TestAGeneratedShellFileIsSkipped(t *testing.T) {
	essay := strings.Repeat("# A long explanation that runs well past the code.\n", 8)
	body := essay + "x=1\n"

	require.NotEmpty(t, Check("x.sh", body), "the control must report without the marker")
	assert.Empty(t, Check("x.sh", "# Code generated by gen.sh. DO NOT EDIT.\n"+body))
}

// commentspan asks ast.NewCommentMap, which associates a comment inside a
// function body with the statement it belongs to. The declaration-kind walk
// this replaced saw doc comments only, so it reported none of them.
func TestACommentInsideAFunctionBodyIsMeasured(t *testing.T) {
	essay := strings.Repeat("\t// A long explanation that runs well past the call.\n", 6)
	src := "package p\n\nfunc f() {\n" + essay + "\tcall()\n}\n"
	assert.NotEmpty(t, Check("x.go", src))
}

// A trailing comment shares its line with code. Measuring the line counts the
// code as comment text, and cutting it deletes the code, so this rule leaves
// one alone where commentspan measures it. Stated divergence, not an oversight.
func TestATrailingCommentIsLeftAlone(t *testing.T) {
	src := "package p\n\nfunc f() {\n\tcall() // " + strings.Repeat("a", floorChars+40) + "\n}\n"
	assert.Empty(t, Check("x.go", src))
}

// commentspan weighs a comment against the whole node. A capped code span
// reported a proportionate comment on a long function as an essay, so the span
// follows the node however far it runs.
func TestALongFunctionIsFollowedToItsEnd(t *testing.T) {
	body := strings.Repeat("\tcallSomethingWithARatherLongName(argumentOne, argumentTwo)\n", 80)
	doc := strings.Repeat("// A line of explanation that earns its place here.\n", 45)
	src := "package p\n\n" + doc + "func f() {\n" + body + "}\n"
	assert.Empty(t, Check("x.go", src), "the comment is shorter than the function")

	// The control: the same comment over a function the cap would have covered
	// IS reported, so the case above proves the span was followed.
	short := "package p\n\n" + doc + "func f() {\n\tcall()\n}\n"
	assert.NotEmpty(t, Check("x.go", short))
}
