// Code generated by ts-translate. DO NOT EDIT.

package rust

import (
	_ "embed"
	"sync"

	ts "github.com/wow-look-at-my/go-tree-sitter"
	grammar "github.com/wow-look-at-my/go-tree-sitter/grammars/rust"
)

//go:embed tables.zst
var tablesBlob []byte

var characterSets [][]ts.CharacterRange

func tsLex(lexer *ts.Lexer, state ts.StateID) bool {
	result := false
	skip := false
	eof := false
	var lookahead int32
	_, _ = eof, lookahead
	goto start
nextState:
	lexer.Advance(skip)
start:
	skip = false
	lookahead = lexer.Lookahead
	eof = lexer.EOF()
	switch state {
	case 0:
		if eof {
			state = 74
			goto nextState
		}
		switch lookahead {
		case 33:
			state = 172
			goto nextState
		case 34:
			state = 158
			goto nextState
		case 35:
			state = 145
			goto nextState
		case 36:
			state = 87
			goto nextState
		case 37:
			state = 101
			goto nextState
		case 38:
			state = 106
			goto nextState
		case 39:
			state = 147
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 42:
			state = 94
			goto nextState
		case 43:
			state = 92
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 98
			goto nextState
		case 46:
			state = 135
			goto nextState
		case 47:
			state = 173
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 85
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 148
			goto nextState
		case 61:
			state = 125
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 64:
			state = 134
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 92:
			state = 49
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 94:
			state = 102
			goto nextState
		case 98:
			state = 179
			goto nextState
		case 99:
			state = 180
			goto nextState
		case 109:
			state = 183
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 108
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 69
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 1:
		if (lookahead == 10) {
			state = 193
			goto nextState
		}
		if (lookahead == 91) {
			state = 3
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			state = 1
			goto nextState
		}
		if (lookahead != 0) {
			state = 3
			goto nextState
		}
		return result
	case 2:
		if (lookahead == 10) {
			state = 193
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			state = 1
			goto nextState
		}
		if ((lookahead != 0) && (lookahead != 91)) {
			state = 3
			goto nextState
		}
		return result
	case 3:
		if (lookahead == 10) {
			state = 193
			goto nextState
		}
		if (lookahead != 0) {
			state = 3
			goto nextState
		}
		return result
	case 4:
		switch lookahead {
		case 33:
			state = 104
			goto nextState
		case 34:
			state = 158
			goto nextState
		case 35:
			state = 144
			goto nextState
		case 36:
			state = 87
			goto nextState
		case 37:
			state = 101
			goto nextState
		case 38:
			state = 106
			goto nextState
		case 39:
			state = 147
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 42:
			state = 94
			goto nextState
		case 43:
			state = 92
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 98
			goto nextState
		case 46:
			state = 135
			goto nextState
		case 47:
			state = 100
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 85
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 131
			goto nextState
		case 61:
			state = 125
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 64:
			state = 134
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 94:
			state = 102
			goto nextState
		case 98:
			state = 179
			goto nextState
		case 99:
			state = 180
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 108
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 4
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 5:
		switch lookahead {
		case 33:
			state = 104
			goto nextState
		case 34:
			state = 158
			goto nextState
		case 35:
			state = 144
			goto nextState
		case 36:
			state = 67
			goto nextState
		case 37:
			state = 101
			goto nextState
		case 38:
			state = 106
			goto nextState
		case 39:
			state = 147
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 42:
			state = 94
			goto nextState
		case 43:
			state = 92
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 97
			goto nextState
		case 46:
			state = 135
			goto nextState
		case 47:
			state = 100
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 85
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 131
			goto nextState
		case 61:
			state = 124
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 94:
			state = 102
			goto nextState
		case 98:
			state = 179
			goto nextState
		case 99:
			state = 180
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 108
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 5
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 6:
		switch lookahead {
		case 33:
			state = 104
			goto nextState
		case 34:
			state = 158
			goto nextState
		case 35:
			state = 144
			goto nextState
		case 36:
			state = 86
			goto nextState
		case 37:
			state = 101
			goto nextState
		case 38:
			state = 106
			goto nextState
		case 39:
			state = 147
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 42:
			state = 94
			goto nextState
		case 43:
			state = 92
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 98
			goto nextState
		case 46:
			state = 135
			goto nextState
		case 47:
			state = 100
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 85
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 131
			goto nextState
		case 61:
			state = 125
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 64:
			state = 134
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 94:
			state = 102
			goto nextState
		case 98:
			state = 179
			goto nextState
		case 99:
			state = 180
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 108
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 6
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 7:
		switch lookahead {
		case 33:
			state = 104
			goto nextState
		case 34:
			state = 158
			goto nextState
		case 36:
			state = 67
			goto nextState
		case 37:
			state = 101
			goto nextState
		case 38:
			state = 106
			goto nextState
		case 39:
			state = 147
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 42:
			state = 94
			goto nextState
		case 43:
			state = 92
			goto nextState
		case 45:
			state = 97
			goto nextState
		case 46:
			state = 135
			goto nextState
		case 47:
			state = 100
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 85
			goto nextState
		case 60:
			state = 131
			goto nextState
		case 61:
			state = 125
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 94:
			state = 102
			goto nextState
		case 98:
			state = 179
			goto nextState
		case 99:
			state = 180
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 108
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 7
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 8:
		switch lookahead {
		case 33:
			state = 104
			goto nextState
		case 37:
			state = 101
			goto nextState
		case 38:
			state = 106
			goto nextState
		case 39:
			state = 146
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 42:
			state = 94
			goto nextState
		case 43:
			state = 92
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 97
			goto nextState
		case 46:
			state = 135
			goto nextState
		case 47:
			state = 100
			goto nextState
		case 58:
			state = 85
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 148
			goto nextState
		case 61:
			state = 124
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 94:
			state = 102
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 108
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 8
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 9:
		switch lookahead {
		case 33:
			state = 104
			goto nextState
		case 37:
			state = 101
			goto nextState
		case 38:
			state = 106
			goto nextState
		case 39:
			state = 146
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 42:
			state = 94
			goto nextState
		case 43:
			state = 92
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 97
			goto nextState
		case 46:
			state = 135
			goto nextState
		case 47:
			state = 100
			goto nextState
		case 58:
			state = 43
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 131
			goto nextState
		case 61:
			state = 124
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 94:
			state = 102
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 108
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 9
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 10:
		switch lookahead {
		case 33:
			state = 104
			goto nextState
		case 37:
			state = 101
			goto nextState
		case 38:
			state = 106
			goto nextState
		case 39:
			state = 146
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 42:
			state = 94
			goto nextState
		case 43:
			state = 92
			goto nextState
		case 45:
			state = 97
			goto nextState
		case 46:
			state = 135
			goto nextState
		case 47:
			state = 100
			goto nextState
		case 58:
			state = 43
			goto nextState
		case 60:
			state = 131
			goto nextState
		case 61:
			state = 125
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 94:
			state = 102
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 108
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 10
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 11:
		switch lookahead {
		case 33:
			state = 104
			goto nextState
		case 37:
			state = 101
			goto nextState
		case 38:
			state = 106
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 42:
			state = 94
			goto nextState
		case 43:
			state = 92
			goto nextState
		case 45:
			state = 97
			goto nextState
		case 46:
			state = 135
			goto nextState
		case 47:
			state = 100
			goto nextState
		case 58:
			state = 43
			goto nextState
		case 60:
			state = 148
			goto nextState
		case 61:
			state = 125
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 94:
			state = 102
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 124:
			state = 108
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 11
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 12:
		switch lookahead {
		case 33:
			state = 103
			goto nextState
		case 34:
			state = 158
			goto nextState
		case 35:
			state = 144
			goto nextState
		case 36:
			state = 67
			goto nextState
		case 38:
			state = 105
			goto nextState
		case 39:
			state = 147
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 42:
			state = 93
			goto nextState
		case 43:
			state = 91
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 96
			goto nextState
		case 46:
			state = 33
			goto nextState
		case 47:
			state = 31
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 85
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 130
			goto nextState
		case 61:
			state = 46
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 98:
			state = 179
			goto nextState
		case 99:
			state = 180
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 124:
			state = 107
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 12
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 13:
		switch lookahead {
		case 33:
			state = 103
			goto nextState
		case 34:
			state = 158
			goto nextState
		case 35:
			state = 144
			goto nextState
		case 36:
			state = 67
			goto nextState
		case 38:
			state = 105
			goto nextState
		case 39:
			state = 147
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 42:
			state = 93
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 96
			goto nextState
		case 46:
			state = 34
			goto nextState
		case 47:
			state = 31
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 85
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 130
			goto nextState
		case 61:
			state = 123
			goto nextState
		case 62:
			state = 128
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 98:
			state = 179
			goto nextState
		case 99:
			state = 180
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 107
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 13
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 14:
		switch lookahead {
		case 33:
			state = 103
			goto nextState
		case 34:
			state = 158
			goto nextState
		case 35:
			state = 144
			goto nextState
		case 36:
			state = 67
			goto nextState
		case 38:
			state = 105
			goto nextState
		case 39:
			state = 147
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 42:
			state = 93
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 96
			goto nextState
		case 46:
			state = 35
			goto nextState
		case 47:
			state = 31
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 43
			goto nextState
		case 60:
			state = 130
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 98:
			state = 179
			goto nextState
		case 99:
			state = 180
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 124:
			state = 107
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 14
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 15:
		switch lookahead {
		case 33:
			state = 103
			goto nextState
		case 34:
			state = 158
			goto nextState
		case 36:
			state = 67
			goto nextState
		case 38:
			state = 105
			goto nextState
		case 39:
			state = 147
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 42:
			state = 93
			goto nextState
		case 43:
			state = 91
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 99
			goto nextState
		case 46:
			state = 34
			goto nextState
		case 47:
			state = 31
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 43
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 130
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 98:
			state = 179
			goto nextState
		case 99:
			state = 180
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 107
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 15
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 16:
		switch lookahead {
		case 33:
			state = 103
			goto nextState
		case 34:
			state = 158
			goto nextState
		case 36:
			state = 67
			goto nextState
		case 38:
			state = 105
			goto nextState
		case 39:
			state = 147
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 42:
			state = 93
			goto nextState
		case 45:
			state = 99
			goto nextState
		case 46:
			state = 35
			goto nextState
		case 47:
			state = 31
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 43
			goto nextState
		case 60:
			state = 130
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 98:
			state = 179
			goto nextState
		case 99:
			state = 180
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 107
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 16
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 17:
		switch lookahead {
		case 33:
			state = 103
			goto nextState
		case 35:
			state = 144
			goto nextState
		case 36:
			state = 67
			goto nextState
		case 38:
			state = 105
			goto nextState
		case 39:
			state = 146
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 42:
			state = 93
			goto nextState
		case 43:
			state = 91
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 45
			goto nextState
		case 46:
			state = 33
			goto nextState
		case 47:
			state = 31
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 85
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 130
			goto nextState
		case 61:
			state = 123
			goto nextState
		case 62:
			state = 128
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 107
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 17
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 18:
		switch lookahead {
		case 33:
			state = 103
			goto nextState
		case 39:
			state = 146
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 43:
			state = 91
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 46:
			state = 33
			goto nextState
		case 47:
			state = 31
			goto nextState
		case 58:
			state = 85
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 148
			goto nextState
		case 61:
			state = 123
			goto nextState
		case 62:
			state = 128
			goto nextState
		case 64:
			state = 134
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 107
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 18
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 19:
		switch lookahead {
		case 33:
			state = 103
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 46:
			state = 33
			goto nextState
		case 47:
			state = 31
			goto nextState
		case 58:
			state = 43
			goto nextState
		case 60:
			state = 148
			goto nextState
		case 61:
			state = 46
			goto nextState
		case 64:
			state = 134
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 107
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 19
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 20:
		switch lookahead {
		case 33:
			state = 44
			goto nextState
		case 37:
			state = 101
			goto nextState
		case 38:
			state = 106
			goto nextState
		case 39:
			state = 146
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 42:
			state = 94
			goto nextState
		case 43:
			state = 92
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 98
			goto nextState
		case 46:
			state = 135
			goto nextState
		case 47:
			state = 100
			goto nextState
		case 58:
			state = 84
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 131
			goto nextState
		case 61:
			state = 124
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 94:
			state = 102
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 108
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 20
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 21:
		switch lookahead {
		case 33:
			state = 44
			goto nextState
		case 37:
			state = 101
			goto nextState
		case 38:
			state = 106
			goto nextState
		case 39:
			state = 146
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 42:
			state = 94
			goto nextState
		case 43:
			state = 92
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 97
			goto nextState
		case 46:
			state = 135
			goto nextState
		case 47:
			state = 100
			goto nextState
		case 58:
			state = 84
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 131
			goto nextState
		case 61:
			state = 124
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 94:
			state = 102
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 108
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 21
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 22:
		switch lookahead {
		case 33:
			state = 44
			goto nextState
		case 37:
			state = 101
			goto nextState
		case 38:
			state = 106
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 42:
			state = 94
			goto nextState
		case 43:
			state = 92
			goto nextState
		case 45:
			state = 98
			goto nextState
		case 46:
			state = 135
			goto nextState
		case 47:
			state = 100
			goto nextState
		case 60:
			state = 131
			goto nextState
		case 61:
			state = 125
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 94:
			state = 102
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 124:
			state = 108
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 22
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 23:
		if (lookahead == 34) {
			state = 158
			goto nextState
		}
		if (lookahead == 47) {
			state = 31
			goto nextState
		}
		if (lookahead == 59) {
			state = 75
			goto nextState
		}
		if (lookahead == 114) {
			state = 181
			goto nextState
		}
		if (lookahead == 123) {
			state = 81
			goto nextState
		}
		if ((lookahead == 98) || (lookahead == 99)) {
			state = 180
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 23
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 24:
		switch lookahead {
		case 35:
			state = 144
			goto nextState
		case 36:
			state = 67
			goto nextState
		case 38:
			state = 27
			goto nextState
		case 39:
			state = 146
			goto nextState
		case 42:
			state = 36
			goto nextState
		case 43:
			state = 91
			goto nextState
		case 47:
			state = 31
			goto nextState
		case 58:
			state = 43
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 130
			goto nextState
		case 61:
			state = 46
			goto nextState
		case 62:
			state = 128
			goto nextState
		case 109:
			state = 183
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 107
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 24
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 25:
		switch lookahead {
		case 35:
			state = 144
			goto nextState
		case 36:
			state = 67
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 47:
			state = 31
			goto nextState
		case 58:
			state = 43
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 130
			goto nextState
		case 61:
			state = 123
			goto nextState
		case 109:
			state = 183
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 25
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 26:
		switch lookahead {
		case 35:
			state = 144
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 46:
			state = 34
			goto nextState
		case 47:
			state = 31
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 84
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 130
			goto nextState
		case 61:
			state = 123
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 26
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 27:
		if (lookahead == 38) {
			state = 109
			goto nextState
		}
		return result
	case 28:
		if (lookahead == 39) {
			state = 159
			goto nextState
		}
		return result
	case 29:
		if (lookahead == 39) {
			state = 159
			goto nextState
		}
		if (lookahead == 92) {
			state = 50
			goto nextState
		}
		if (lookahead != 0) {
			state = 28
			goto nextState
		}
		return result
	case 30:
		switch lookahead {
		case 39:
			state = 146
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 42:
			state = 93
			goto nextState
		case 43:
			state = 91
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 45
			goto nextState
		case 46:
			state = 33
			goto nextState
		case 47:
			state = 31
			goto nextState
		case 58:
			state = 84
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 148
			goto nextState
		case 61:
			state = 123
			goto nextState
		case 62:
			state = 128
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 107
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 30
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 31:
		if (lookahead == 42) {
			state = 175
			goto nextState
		}
		if (lookahead == 47) {
			state = 161
			goto nextState
		}
		return result
	case 32:
		if (lookahead == 42) {
			state = 93
			goto nextState
		}
		if (lookahead == 43) {
			state = 91
			goto nextState
		}
		if (lookahead == 47) {
			state = 88
			goto nextState
		}
		if (lookahead == 63) {
			state = 95
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			state = 89
			goto nextState
		}
		if (lookahead != 0) {
			state = 90
			goto nextState
		}
		return result
	case 33:
		if (lookahead == 46) {
			state = 137
			goto nextState
		}
		return result
	case 34:
		if (lookahead == 46) {
			state = 136
			goto nextState
		}
		return result
	case 35:
		if (lookahead == 46) {
			state = 138
			goto nextState
		}
		return result
	case 36:
		if (lookahead == 47) {
			state = 177
			goto nextState
		}
		return result
	case 37:
		if (lookahead == 49) {
			state = 39
			goto nextState
		}
		if (lookahead == 51) {
			state = 38
			goto nextState
		}
		if (lookahead == 54) {
			state = 41
			goto nextState
		}
		if (lookahead == 56) {
			state = 149
			goto nextState
		}
		if (lookahead == 115) {
			state = 48
			goto nextState
		}
		return result
	case 38:
		if (lookahead == 50) {
			state = 149
			goto nextState
		}
		return result
	case 39:
		if (lookahead == 50) {
			state = 42
			goto nextState
		}
		if (lookahead == 54) {
			state = 149
			goto nextState
		}
		return result
	case 40:
		if (lookahead == 51) {
			state = 38
			goto nextState
		}
		if (lookahead == 54) {
			state = 41
			goto nextState
		}
		return result
	case 41:
		if (lookahead == 52) {
			state = 149
			goto nextState
		}
		return result
	case 42:
		if (lookahead == 56) {
			state = 149
			goto nextState
		}
		return result
	case 43:
		if (lookahead == 58) {
			state = 142
			goto nextState
		}
		return result
	case 44:
		if (lookahead == 61) {
			state = 127
			goto nextState
		}
		return result
	case 45:
		if (lookahead == 62) {
			state = 143
			goto nextState
		}
		return result
	case 46:
		if (lookahead == 62) {
			state = 83
			goto nextState
		}
		return result
	case 47:
		if (lookahead == 101) {
			state = 149
			goto nextState
		}
		return result
	case 48:
		if (lookahead == 105) {
			state = 51
			goto nextState
		}
		return result
	case 49:
		if (lookahead == 117) {
			state = 52
			goto nextState
		}
		if (lookahead == 120) {
			state = 63
			goto nextState
		}
		if (lookahead != 0) {
			state = 160
			goto nextState
		}
		return result
	case 50:
		if (lookahead == 117) {
			state = 53
			goto nextState
		}
		if (lookahead == 120) {
			state = 64
			goto nextState
		}
		if (lookahead != 0) {
			state = 28
			goto nextState
		}
		return result
	case 51:
		if (lookahead == 122) {
			state = 47
			goto nextState
		}
		return result
	case 52:
		if (lookahead == 123) {
			state = 61
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 59
			goto nextState
		}
		return result
	case 53:
		if (lookahead == 123) {
			state = 62
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 65
			goto nextState
		}
		return result
	case 54:
		if (lookahead == 125) {
			state = 28
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 54
			goto nextState
		}
		return result
	case 55:
		if (lookahead == 125) {
			state = 160
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 55
			goto nextState
		}
		return result
	case 56:
		if (((lookahead == 48) || (lookahead == 49)) || (lookahead == 95)) {
			state = 154
			goto nextState
		}
		return result
	case 57:
		if (((48 <= lookahead) && (lookahead <= 55)) || (lookahead == 95)) {
			state = 155
			goto nextState
		}
		return result
	case 58:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 28
			goto nextState
		}
		return result
	case 59:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 63
			goto nextState
		}
		return result
	case 60:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 160
			goto nextState
		}
		return result
	case 61:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 55
			goto nextState
		}
		return result
	case 62:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 54
			goto nextState
		}
		return result
	case 63:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 60
			goto nextState
		}
		return result
	case 64:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 58
			goto nextState
		}
		return result
	case 65:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 64
			goto nextState
		}
		return result
	case 66:
		if (((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || (lookahead == 95)) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 157
			goto nextState
		}
		return result
	case 67:
		if ((((65 <= lookahead) && (lookahead <= 90)) || (lookahead == 95)) || ((97 <= lookahead) && (lookahead <= 122))) {
			state = 194
			goto nextState
		}
		return result
	case 68:
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 69:
		if eof {
			state = 74
			goto nextState
		}
		switch lookahead {
		case 33:
			state = 104
			goto nextState
		case 34:
			state = 158
			goto nextState
		case 35:
			state = 145
			goto nextState
		case 36:
			state = 87
			goto nextState
		case 37:
			state = 101
			goto nextState
		case 38:
			state = 106
			goto nextState
		case 39:
			state = 147
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 42:
			state = 94
			goto nextState
		case 43:
			state = 92
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 98
			goto nextState
		case 46:
			state = 135
			goto nextState
		case 47:
			state = 100
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 85
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 148
			goto nextState
		case 61:
			state = 125
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 64:
			state = 134
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 94:
			state = 102
			goto nextState
		case 98:
			state = 179
			goto nextState
		case 99:
			state = 180
			goto nextState
		case 109:
			state = 183
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 108
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 69
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 70:
		if eof {
			state = 74
			goto nextState
		}
		switch lookahead {
		case 33:
			state = 104
			goto nextState
		case 34:
			state = 158
			goto nextState
		case 35:
			state = 144
			goto nextState
		case 36:
			state = 67
			goto nextState
		case 37:
			state = 101
			goto nextState
		case 38:
			state = 106
			goto nextState
		case 39:
			state = 147
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 42:
			state = 94
			goto nextState
		case 43:
			state = 92
			goto nextState
		case 45:
			state = 97
			goto nextState
		case 46:
			state = 135
			goto nextState
		case 47:
			state = 100
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 43
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 131
			goto nextState
		case 61:
			state = 124
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 94:
			state = 102
			goto nextState
		case 98:
			state = 179
			goto nextState
		case 99:
			state = 180
			goto nextState
		case 109:
			state = 183
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 108
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 70
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 71:
		if eof {
			state = 74
			goto nextState
		}
		switch lookahead {
		case 33:
			state = 103
			goto nextState
		case 34:
			state = 158
			goto nextState
		case 35:
			state = 145
			goto nextState
		case 36:
			state = 67
			goto nextState
		case 38:
			state = 105
			goto nextState
		case 39:
			state = 147
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 42:
			state = 93
			goto nextState
		case 43:
			state = 91
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 96
			goto nextState
		case 46:
			state = 34
			goto nextState
		case 47:
			state = 31
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 85
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 130
			goto nextState
		case 61:
			state = 123
			goto nextState
		case 62:
			state = 128
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 92:
			state = 49
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 98:
			state = 179
			goto nextState
		case 99:
			state = 180
			goto nextState
		case 109:
			state = 183
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 107
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 72
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 72:
		if eof {
			state = 74
			goto nextState
		}
		switch lookahead {
		case 33:
			state = 103
			goto nextState
		case 34:
			state = 158
			goto nextState
		case 35:
			state = 145
			goto nextState
		case 36:
			state = 67
			goto nextState
		case 38:
			state = 105
			goto nextState
		case 39:
			state = 147
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 41:
			state = 78
			goto nextState
		case 42:
			state = 93
			goto nextState
		case 43:
			state = 91
			goto nextState
		case 44:
			state = 141
			goto nextState
		case 45:
			state = 96
			goto nextState
		case 46:
			state = 34
			goto nextState
		case 47:
			state = 31
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 85
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 130
			goto nextState
		case 61:
			state = 123
			goto nextState
		case 62:
			state = 128
			goto nextState
		case 63:
			state = 95
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 93:
			state = 80
			goto nextState
		case 98:
			state = 179
			goto nextState
		case 99:
			state = 180
			goto nextState
		case 109:
			state = 183
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 107
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 72
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 73:
		if eof {
			state = 74
			goto nextState
		}
		switch lookahead {
		case 33:
			state = 103
			goto nextState
		case 34:
			state = 158
			goto nextState
		case 35:
			state = 144
			goto nextState
		case 36:
			state = 67
			goto nextState
		case 38:
			state = 105
			goto nextState
		case 39:
			state = 147
			goto nextState
		case 40:
			state = 77
			goto nextState
		case 42:
			state = 93
			goto nextState
		case 45:
			state = 96
			goto nextState
		case 46:
			state = 34
			goto nextState
		case 47:
			state = 31
			goto nextState
		case 48:
			state = 153
			goto nextState
		case 58:
			state = 43
			goto nextState
		case 59:
			state = 75
			goto nextState
		case 60:
			state = 130
			goto nextState
		case 61:
			state = 46
			goto nextState
		case 91:
			state = 79
			goto nextState
		case 98:
			state = 179
			goto nextState
		case 99:
			state = 180
			goto nextState
		case 109:
			state = 183
			goto nextState
		case 114:
			state = 181
			goto nextState
		case 123:
			state = 81
			goto nextState
		case 124:
			state = 107
			goto nextState
		case 125:
			state = 82
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 73
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 156
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 74:
		result = true
		lexer.ResultSymbol = 0
		lexer.MarkEnd()
		return result
	case 75:
		result = true
		lexer.ResultSymbol = 2
		lexer.MarkEnd()
		return result
	case 76:
		result = true
		lexer.ResultSymbol = 3
		lexer.MarkEnd()
		return result
	case 77:
		result = true
		lexer.ResultSymbol = 4
		lexer.MarkEnd()
		return result
	case 78:
		result = true
		lexer.ResultSymbol = 5
		lexer.MarkEnd()
		return result
	case 79:
		result = true
		lexer.ResultSymbol = 6
		lexer.MarkEnd()
		return result
	case 80:
		result = true
		lexer.ResultSymbol = 7
		lexer.MarkEnd()
		return result
	case 81:
		result = true
		lexer.ResultSymbol = 8
		lexer.MarkEnd()
		return result
	case 82:
		result = true
		lexer.ResultSymbol = 9
		lexer.MarkEnd()
		return result
	case 83:
		result = true
		lexer.ResultSymbol = 10
		lexer.MarkEnd()
		return result
	case 84:
		result = true
		lexer.ResultSymbol = 11
		lexer.MarkEnd()
		return result
	case 85:
		result = true
		lexer.ResultSymbol = 11
		lexer.MarkEnd()
		if (lookahead == 58) {
			state = 142
			goto nextState
		}
		return result
	case 86:
		result = true
		lexer.ResultSymbol = 12
		lexer.MarkEnd()
		return result
	case 87:
		result = true
		lexer.ResultSymbol = 12
		lexer.MarkEnd()
		if ((((65 <= lookahead) && (lookahead <= 90)) || (lookahead == 95)) || ((97 <= lookahead) && (lookahead <= 122))) {
			state = 194
			goto nextState
		}
		return result
	case 88:
		result = true
		lexer.ResultSymbol = 13
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 175
			goto nextState
		}
		if (lookahead == 47) {
			state = 162
			goto nextState
		}
		if ((((lookahead != 0) && (lookahead != 42)) && (lookahead != 43)) && (lookahead != 63)) {
			state = 90
			goto nextState
		}
		return result
	case 89:
		result = true
		lexer.ResultSymbol = 13
		lexer.MarkEnd()
		if (lookahead == 47) {
			state = 88
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			state = 89
			goto nextState
		}
		if ((((lookahead != 0) && (lookahead != 42)) && (lookahead != 43)) && (lookahead != 63)) {
			state = 90
			goto nextState
		}
		return result
	case 90:
		result = true
		lexer.ResultSymbol = 13
		lexer.MarkEnd()
		if ((((lookahead != 0) && (lookahead != 42)) && (lookahead != 43)) && (lookahead != 63)) {
			state = 90
			goto nextState
		}
		return result
	case 91:
		result = true
		lexer.ResultSymbol = 14
		lexer.MarkEnd()
		return result
	case 92:
		result = true
		lexer.ResultSymbol = 14
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 113
			goto nextState
		}
		return result
	case 93:
		result = true
		lexer.ResultSymbol = 15
		lexer.MarkEnd()
		return result
	case 94:
		result = true
		lexer.ResultSymbol = 15
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 115
			goto nextState
		}
		return result
	case 95:
		result = true
		lexer.ResultSymbol = 16
		lexer.MarkEnd()
		return result
	case 96:
		result = true
		lexer.ResultSymbol = 49
		lexer.MarkEnd()
		return result
	case 97:
		result = true
		lexer.ResultSymbol = 49
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 114
			goto nextState
		}
		return result
	case 98:
		result = true
		lexer.ResultSymbol = 49
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 114
			goto nextState
		}
		if (lookahead == 62) {
			state = 143
			goto nextState
		}
		return result
	case 99:
		result = true
		lexer.ResultSymbol = 49
		lexer.MarkEnd()
		if (lookahead == 62) {
			state = 143
			goto nextState
		}
		return result
	case 100:
		result = true
		lexer.ResultSymbol = 50
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 175
			goto nextState
		}
		if (lookahead == 47) {
			state = 161
			goto nextState
		}
		if (lookahead == 61) {
			state = 116
			goto nextState
		}
		return result
	case 101:
		result = true
		lexer.ResultSymbol = 51
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 117
			goto nextState
		}
		return result
	case 102:
		result = true
		lexer.ResultSymbol = 52
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 118
			goto nextState
		}
		return result
	case 103:
		result = true
		lexer.ResultSymbol = 53
		lexer.MarkEnd()
		return result
	case 104:
		result = true
		lexer.ResultSymbol = 53
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 127
			goto nextState
		}
		return result
	case 105:
		result = true
		lexer.ResultSymbol = 54
		lexer.MarkEnd()
		return result
	case 106:
		result = true
		lexer.ResultSymbol = 54
		lexer.MarkEnd()
		if (lookahead == 38) {
			state = 109
			goto nextState
		}
		if (lookahead == 61) {
			state = 119
			goto nextState
		}
		return result
	case 107:
		result = true
		lexer.ResultSymbol = 55
		lexer.MarkEnd()
		return result
	case 108:
		result = true
		lexer.ResultSymbol = 55
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 120
			goto nextState
		}
		if (lookahead == 124) {
			state = 110
			goto nextState
		}
		return result
	case 109:
		result = true
		lexer.ResultSymbol = 56
		lexer.MarkEnd()
		return result
	case 110:
		result = true
		lexer.ResultSymbol = 57
		lexer.MarkEnd()
		return result
	case 111:
		result = true
		lexer.ResultSymbol = 58
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 121
			goto nextState
		}
		return result
	case 112:
		result = true
		lexer.ResultSymbol = 59
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 122
			goto nextState
		}
		return result
	case 113:
		result = true
		lexer.ResultSymbol = 60
		lexer.MarkEnd()
		return result
	case 114:
		result = true
		lexer.ResultSymbol = 61
		lexer.MarkEnd()
		return result
	case 115:
		result = true
		lexer.ResultSymbol = 62
		lexer.MarkEnd()
		return result
	case 116:
		result = true
		lexer.ResultSymbol = 63
		lexer.MarkEnd()
		return result
	case 117:
		result = true
		lexer.ResultSymbol = 64
		lexer.MarkEnd()
		return result
	case 118:
		result = true
		lexer.ResultSymbol = 65
		lexer.MarkEnd()
		return result
	case 119:
		result = true
		lexer.ResultSymbol = 66
		lexer.MarkEnd()
		return result
	case 120:
		result = true
		lexer.ResultSymbol = 67
		lexer.MarkEnd()
		return result
	case 121:
		result = true
		lexer.ResultSymbol = 68
		lexer.MarkEnd()
		return result
	case 122:
		result = true
		lexer.ResultSymbol = 69
		lexer.MarkEnd()
		return result
	case 123:
		result = true
		lexer.ResultSymbol = 70
		lexer.MarkEnd()
		return result
	case 124:
		result = true
		lexer.ResultSymbol = 70
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 126
			goto nextState
		}
		return result
	case 125:
		result = true
		lexer.ResultSymbol = 70
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 126
			goto nextState
		}
		if (lookahead == 62) {
			state = 83
			goto nextState
		}
		return result
	case 126:
		result = true
		lexer.ResultSymbol = 71
		lexer.MarkEnd()
		return result
	case 127:
		result = true
		lexer.ResultSymbol = 72
		lexer.MarkEnd()
		return result
	case 128:
		result = true
		lexer.ResultSymbol = 73
		lexer.MarkEnd()
		return result
	case 129:
		result = true
		lexer.ResultSymbol = 73
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 132
			goto nextState
		}
		if (lookahead == 62) {
			state = 112
			goto nextState
		}
		return result
	case 130:
		result = true
		lexer.ResultSymbol = 74
		lexer.MarkEnd()
		return result
	case 131:
		result = true
		lexer.ResultSymbol = 74
		lexer.MarkEnd()
		if (lookahead == 60) {
			state = 111
			goto nextState
		}
		if (lookahead == 61) {
			state = 133
			goto nextState
		}
		return result
	case 132:
		result = true
		lexer.ResultSymbol = 75
		lexer.MarkEnd()
		return result
	case 133:
		result = true
		lexer.ResultSymbol = 76
		lexer.MarkEnd()
		return result
	case 134:
		result = true
		lexer.ResultSymbol = 77
		lexer.MarkEnd()
		return result
	case 135:
		result = true
		lexer.ResultSymbol = 79
		lexer.MarkEnd()
		if (lookahead == 46) {
			state = 137
			goto nextState
		}
		return result
	case 136:
		result = true
		lexer.ResultSymbol = 80
		lexer.MarkEnd()
		return result
	case 137:
		result = true
		lexer.ResultSymbol = 80
		lexer.MarkEnd()
		if (lookahead == 46) {
			state = 139
			goto nextState
		}
		if (lookahead == 61) {
			state = 140
			goto nextState
		}
		return result
	case 138:
		result = true
		lexer.ResultSymbol = 80
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 140
			goto nextState
		}
		return result
	case 139:
		result = true
		lexer.ResultSymbol = 81
		lexer.MarkEnd()
		return result
	case 140:
		result = true
		lexer.ResultSymbol = 82
		lexer.MarkEnd()
		return result
	case 141:
		result = true
		lexer.ResultSymbol = 83
		lexer.MarkEnd()
		return result
	case 142:
		result = true
		lexer.ResultSymbol = 84
		lexer.MarkEnd()
		return result
	case 143:
		result = true
		lexer.ResultSymbol = 85
		lexer.MarkEnd()
		return result
	case 144:
		result = true
		lexer.ResultSymbol = 86
		lexer.MarkEnd()
		return result
	case 145:
		result = true
		lexer.ResultSymbol = 86
		lexer.MarkEnd()
		if (lookahead == 33) {
			state = 2
			goto nextState
		}
		return result
	case 146:
		result = true
		lexer.ResultSymbol = 87
		lexer.MarkEnd()
		return result
	case 147:
		result = true
		lexer.ResultSymbol = 87
		lexer.MarkEnd()
		if (lookahead == 39) {
			state = 159
			goto nextState
		}
		if (lookahead == 92) {
			state = 50
			goto nextState
		}
		if (lookahead != 0) {
			state = 28
			goto nextState
		}
		return result
	case 148:
		result = true
		lexer.ResultSymbol = 120
		lexer.MarkEnd()
		return result
	case 149:
		result = true
		lexer.ResultSymbol = 127
		lexer.MarkEnd()
		return result
	case 150:
		result = true
		lexer.ResultSymbol = 127
		lexer.MarkEnd()
		if (lookahead == 50) {
			state = 157
			goto nextState
		}
		if (lookahead == 102) {
			state = 151
			goto nextState
		}
		if (lookahead == 105) {
			state = 37
			goto nextState
		}
		if (lookahead == 117) {
			state = 37
			goto nextState
		}
		if (((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || (lookahead == 95)) || ((97 <= lookahead) && (lookahead <= 101))) {
			state = 157
			goto nextState
		}
		return result
	case 151:
		result = true
		lexer.ResultSymbol = 127
		lexer.MarkEnd()
		if (lookahead == 51) {
			state = 150
			goto nextState
		}
		if (lookahead == 54) {
			state = 152
			goto nextState
		}
		if (lookahead == 102) {
			state = 151
			goto nextState
		}
		if (lookahead == 105) {
			state = 37
			goto nextState
		}
		if (lookahead == 117) {
			state = 37
			goto nextState
		}
		if (((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || (lookahead == 95)) || ((97 <= lookahead) && (lookahead <= 101))) {
			state = 157
			goto nextState
		}
		return result
	case 152:
		result = true
		lexer.ResultSymbol = 127
		lexer.MarkEnd()
		if (lookahead == 52) {
			state = 157
			goto nextState
		}
		if (lookahead == 102) {
			state = 151
			goto nextState
		}
		if (lookahead == 105) {
			state = 37
			goto nextState
		}
		if (lookahead == 117) {
			state = 37
			goto nextState
		}
		if (((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || (lookahead == 95)) || ((97 <= lookahead) && (lookahead <= 101))) {
			state = 157
			goto nextState
		}
		return result
	case 153:
		result = true
		lexer.ResultSymbol = 127
		lexer.MarkEnd()
		if (lookahead == 98) {
			state = 56
			goto nextState
		}
		if (lookahead == 102) {
			state = 40
			goto nextState
		}
		if (lookahead == 105) {
			state = 37
			goto nextState
		}
		if (lookahead == 111) {
			state = 57
			goto nextState
		}
		if (lookahead == 117) {
			state = 37
			goto nextState
		}
		if (lookahead == 120) {
			state = 66
			goto nextState
		}
		if (((48 <= lookahead) && (lookahead <= 57)) || (lookahead == 95)) {
			state = 156
			goto nextState
		}
		return result
	case 154:
		result = true
		lexer.ResultSymbol = 127
		lexer.MarkEnd()
		if (lookahead == 102) {
			state = 40
			goto nextState
		}
		if (lookahead == 105) {
			state = 37
			goto nextState
		}
		if (lookahead == 117) {
			state = 37
			goto nextState
		}
		if (((lookahead == 48) || (lookahead == 49)) || (lookahead == 95)) {
			state = 154
			goto nextState
		}
		return result
	case 155:
		result = true
		lexer.ResultSymbol = 127
		lexer.MarkEnd()
		if (lookahead == 102) {
			state = 40
			goto nextState
		}
		if (lookahead == 105) {
			state = 37
			goto nextState
		}
		if (lookahead == 117) {
			state = 37
			goto nextState
		}
		if (((48 <= lookahead) && (lookahead <= 55)) || (lookahead == 95)) {
			state = 155
			goto nextState
		}
		return result
	case 156:
		result = true
		lexer.ResultSymbol = 127
		lexer.MarkEnd()
		if (lookahead == 102) {
			state = 40
			goto nextState
		}
		if (lookahead == 105) {
			state = 37
			goto nextState
		}
		if (lookahead == 117) {
			state = 37
			goto nextState
		}
		if (((48 <= lookahead) && (lookahead <= 57)) || (lookahead == 95)) {
			state = 156
			goto nextState
		}
		return result
	case 157:
		result = true
		lexer.ResultSymbol = 127
		lexer.MarkEnd()
		if (lookahead == 102) {
			state = 151
			goto nextState
		}
		if (lookahead == 105) {
			state = 37
			goto nextState
		}
		if (lookahead == 117) {
			state = 37
			goto nextState
		}
		if (((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || (lookahead == 95)) || ((97 <= lookahead) && (lookahead <= 101))) {
			state = 157
			goto nextState
		}
		return result
	case 158:
		result = true
		lexer.ResultSymbol = 128
		lexer.MarkEnd()
		return result
	case 159:
		result = true
		lexer.ResultSymbol = 129
		lexer.MarkEnd()
		return result
	case 160:
		result = true
		lexer.ResultSymbol = 130
		lexer.MarkEnd()
		return result
	case 161:
		result = true
		lexer.ResultSymbol = 133
		lexer.MarkEnd()
		return result
	case 162:
		result = true
		lexer.ResultSymbol = 133
		lexer.MarkEnd()
		if ((((lookahead != 0) && (lookahead != 42)) && (lookahead != 43)) && (lookahead != 63)) {
			state = 90
			goto nextState
		}
		return result
	case 163:
		result = true
		lexer.ResultSymbol = 133
		lexer.MarkEnd()
		if ((lookahead != 0) && (lookahead != 10)) {
			state = 167
			goto nextState
		}
		return result
	case 164:
		result = true
		lexer.ResultSymbol = 134
		lexer.MarkEnd()
		return result
	case 165:
		result = true
		lexer.ResultSymbol = 135
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 176
			goto nextState
		}
		if (lookahead == 47) {
			state = 163
			goto nextState
		}
		if ((lookahead != 0) && (lookahead != 10)) {
			state = 167
			goto nextState
		}
		return result
	case 166:
		result = true
		lexer.ResultSymbol = 135
		lexer.MarkEnd()
		if (lookahead == 47) {
			state = 165
			goto nextState
		}
		if (((lookahead == 9) || ((11 <= lookahead) && (lookahead <= 13))) || (lookahead == 32)) {
			state = 166
			goto nextState
		}
		if ((lookahead != 0) && ((lookahead < 9) || (13 < lookahead))) {
			state = 167
			goto nextState
		}
		return result
	case 167:
		result = true
		lexer.ResultSymbol = 135
		lexer.MarkEnd()
		if ((lookahead != 0) && (lookahead != 10)) {
			state = 167
			goto nextState
		}
		return result
	case 168:
		result = true
		lexer.ResultSymbol = 136
		lexer.MarkEnd()
		if (lookahead == 33) {
			state = 172
			goto nextState
		}
		if (lookahead == 47) {
			state = 174
			goto nextState
		}
		if (((lookahead == 9) || ((11 <= lookahead) && (lookahead <= 13))) || (lookahead == 32)) {
			state = 170
			goto nextState
		}
		if ((lookahead != 0) && ((lookahead < 9) || (13 < lookahead))) {
			state = 171
			goto nextState
		}
		return result
	case 169:
		result = true
		lexer.ResultSymbol = 136
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 171
			goto nextState
		}
		if (lookahead == 47) {
			state = 171
			goto nextState
		}
		if ((lookahead != 0) && (lookahead != 10)) {
			state = 171
			goto nextState
		}
		return result
	case 170:
		result = true
		lexer.ResultSymbol = 136
		lexer.MarkEnd()
		if (lookahead == 47) {
			state = 169
			goto nextState
		}
		if (((lookahead == 9) || ((11 <= lookahead) && (lookahead <= 13))) || (lookahead == 32)) {
			state = 170
			goto nextState
		}
		if ((lookahead != 0) && ((lookahead < 9) || (13 < lookahead))) {
			state = 171
			goto nextState
		}
		return result
	case 171:
		result = true
		lexer.ResultSymbol = 136
		lexer.MarkEnd()
		if ((lookahead != 0) && (lookahead != 10)) {
			state = 171
			goto nextState
		}
		return result
	case 172:
		result = true
		lexer.ResultSymbol = 137
		lexer.MarkEnd()
		return result
	case 173:
		result = true
		lexer.ResultSymbol = 138
		lexer.MarkEnd()
		return result
	case 174:
		result = true
		lexer.ResultSymbol = 138
		lexer.MarkEnd()
		if (lookahead == 47) {
			state = 164
			goto nextState
		}
		return result
	case 175:
		result = true
		lexer.ResultSymbol = 139
		lexer.MarkEnd()
		return result
	case 176:
		result = true
		lexer.ResultSymbol = 139
		lexer.MarkEnd()
		if ((lookahead != 0) && (lookahead != 10)) {
			state = 167
			goto nextState
		}
		return result
	case 177:
		result = true
		lexer.ResultSymbol = 140
		lexer.MarkEnd()
		return result
	case 178:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if (lookahead == 33) {
			state = 76
			goto nextState
		}
		if ts.SetContains(characterSets[1], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 179:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if (lookahead == 34) {
			state = 158
			goto nextState
		}
		if (lookahead == 39) {
			state = 29
			goto nextState
		}
		if ts.SetContains(characterSets[1], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 180:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if (lookahead == 34) {
			state = 158
			goto nextState
		}
		if ts.SetContains(characterSets[1], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 181:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if (lookahead == 35) {
			state = 68
			goto nextState
		}
		if ts.SetContains(characterSets[1], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 182:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if (lookahead == 95) {
			state = 189
			goto nextState
		}
		if ts.SetContains(characterSets[1], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 183:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if (lookahead == 97) {
			state = 184
			goto nextState
		}
		if ts.SetContains(characterSets[1], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 184:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if (lookahead == 99) {
			state = 188
			goto nextState
		}
		if ts.SetContains(characterSets[1], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 185:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if (lookahead == 101) {
			state = 190
			goto nextState
		}
		if ts.SetContains(characterSets[1], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 186:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if (lookahead == 108) {
			state = 185
			goto nextState
		}
		if ts.SetContains(characterSets[1], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 187:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if (lookahead == 111) {
			state = 182
			goto nextState
		}
		if ts.SetContains(characterSets[1], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 188:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if (lookahead == 114) {
			state = 187
			goto nextState
		}
		if ts.SetContains(characterSets[1], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 189:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if (lookahead == 114) {
			state = 191
			goto nextState
		}
		if ts.SetContains(characterSets[1], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 190:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if (lookahead == 115) {
			state = 178
			goto nextState
		}
		if ts.SetContains(characterSets[1], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 191:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if (lookahead == 117) {
			state = 186
			goto nextState
		}
		if ts.SetContains(characterSets[1], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 192:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if ts.SetContains(characterSets[1], lookahead) {
			state = 192
			goto nextState
		}
		return result
	case 193:
		result = true
		lexer.ResultSymbol = 141
		lexer.MarkEnd()
		return result
	case 194:
		result = true
		lexer.ResultSymbol = 145
		lexer.MarkEnd()
		if (((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 90))) || (lookahead == 95)) || ((97 <= lookahead) && (lookahead <= 122))) {
			state = 194
			goto nextState
		}
		return result
	default:
		return false
	}
}

func tsLexKeywords(lexer *ts.Lexer, state ts.StateID) bool {
	result := false
	skip := false
	eof := false
	var lookahead int32
	_, _ = eof, lookahead
	goto start
nextState:
	lexer.Advance(skip)
start:
	skip = false
	lookahead = lexer.Lookahead
	eof = lexer.EOF()
	switch state {
	case 0:
		switch lookahead {
		case 95:
			state = 1
			goto nextState
		case 97:
			state = 2
			goto nextState
		case 98:
			state = 3
			goto nextState
		case 99:
			state = 4
			goto nextState
		case 100:
			state = 5
			goto nextState
		case 101:
			state = 6
			goto nextState
		case 102:
			state = 7
			goto nextState
		case 103:
			state = 8
			goto nextState
		case 105:
			state = 9
			goto nextState
		case 108:
			state = 10
			goto nextState
		case 109:
			state = 11
			goto nextState
		case 112:
			state = 12
			goto nextState
		case 114:
			state = 13
			goto nextState
		case 115:
			state = 14
			goto nextState
		case 116:
			state = 15
			goto nextState
		case 117:
			state = 16
			goto nextState
		case 118:
			state = 17
			goto nextState
		case 119:
			state = 18
			goto nextState
		case 121:
			state = 19
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 0
			goto nextState
		}
		return result
	case 1:
		result = true
		lexer.ResultSymbol = 78
		lexer.MarkEnd()
		return result
	case 2:
		if (lookahead == 115) {
			state = 20
			goto nextState
		}
		if (lookahead == 119) {
			state = 21
			goto nextState
		}
		return result
	case 3:
		if (lookahead == 108) {
			state = 22
			goto nextState
		}
		if (lookahead == 111) {
			state = 23
			goto nextState
		}
		if (lookahead == 114) {
			state = 24
			goto nextState
		}
		return result
	case 4:
		if (lookahead == 104) {
			state = 25
			goto nextState
		}
		if (lookahead == 111) {
			state = 26
			goto nextState
		}
		if (lookahead == 114) {
			state = 27
			goto nextState
		}
		return result
	case 5:
		if (lookahead == 101) {
			state = 28
			goto nextState
		}
		if (lookahead == 121) {
			state = 29
			goto nextState
		}
		return result
	case 6:
		if (lookahead == 108) {
			state = 30
			goto nextState
		}
		if (lookahead == 110) {
			state = 31
			goto nextState
		}
		if (lookahead == 120) {
			state = 32
			goto nextState
		}
		return result
	case 7:
		if (lookahead == 51) {
			state = 33
			goto nextState
		}
		if (lookahead == 54) {
			state = 34
			goto nextState
		}
		if (lookahead == 97) {
			state = 35
			goto nextState
		}
		if (lookahead == 110) {
			state = 36
			goto nextState
		}
		if (lookahead == 111) {
			state = 37
			goto nextState
		}
		return result
	case 8:
		if (lookahead == 101) {
			state = 38
			goto nextState
		}
		return result
	case 9:
		switch lookahead {
		case 49:
			state = 39
			goto nextState
		case 51:
			state = 40
			goto nextState
		case 54:
			state = 41
			goto nextState
		case 56:
			state = 42
			goto nextState
		case 100:
			state = 43
			goto nextState
		case 102:
			state = 44
			goto nextState
		case 109:
			state = 45
			goto nextState
		case 110:
			state = 46
			goto nextState
		case 115:
			state = 47
			goto nextState
		case 116:
			state = 48
			goto nextState
		}
		return result
	case 10:
		if (lookahead == 101) {
			state = 49
			goto nextState
		}
		if (lookahead == 105) {
			state = 50
			goto nextState
		}
		if (lookahead == 111) {
			state = 51
			goto nextState
		}
		return result
	case 11:
		if (lookahead == 97) {
			state = 52
			goto nextState
		}
		if (lookahead == 101) {
			state = 53
			goto nextState
		}
		if (lookahead == 111) {
			state = 54
			goto nextState
		}
		if (lookahead == 117) {
			state = 55
			goto nextState
		}
		return result
	case 12:
		if (lookahead == 97) {
			state = 56
			goto nextState
		}
		if (lookahead == 117) {
			state = 57
			goto nextState
		}
		return result
	case 13:
		if (lookahead == 97) {
			state = 58
			goto nextState
		}
		if (lookahead == 101) {
			state = 59
			goto nextState
		}
		return result
	case 14:
		if (lookahead == 101) {
			state = 60
			goto nextState
		}
		if (lookahead == 116) {
			state = 61
			goto nextState
		}
		if (lookahead == 117) {
			state = 62
			goto nextState
		}
		return result
	case 15:
		if (lookahead == 114) {
			state = 63
			goto nextState
		}
		if (lookahead == 116) {
			state = 64
			goto nextState
		}
		if (lookahead == 121) {
			state = 65
			goto nextState
		}
		return result
	case 16:
		if (lookahead == 49) {
			state = 66
			goto nextState
		}
		if (lookahead == 51) {
			state = 67
			goto nextState
		}
		if (lookahead == 54) {
			state = 68
			goto nextState
		}
		if (lookahead == 56) {
			state = 69
			goto nextState
		}
		if (lookahead == 110) {
			state = 70
			goto nextState
		}
		if (lookahead == 115) {
			state = 71
			goto nextState
		}
		return result
	case 17:
		if (lookahead == 105) {
			state = 72
			goto nextState
		}
		return result
	case 18:
		if (lookahead == 104) {
			state = 73
			goto nextState
		}
		return result
	case 19:
		if (lookahead == 105) {
			state = 74
			goto nextState
		}
		return result
	case 20:
		result = true
		lexer.ResultSymbol = 88
		lexer.MarkEnd()
		if (lookahead == 121) {
			state = 75
			goto nextState
		}
		return result
	case 21:
		if (lookahead == 97) {
			state = 76
			goto nextState
		}
		return result
	case 22:
		if (lookahead == 111) {
			state = 77
			goto nextState
		}
		return result
	case 23:
		if (lookahead == 111) {
			state = 78
			goto nextState
		}
		return result
	case 24:
		if (lookahead == 101) {
			state = 79
			goto nextState
		}
		return result
	case 25:
		if (lookahead == 97) {
			state = 80
			goto nextState
		}
		return result
	case 26:
		if (lookahead == 110) {
			state = 81
			goto nextState
		}
		return result
	case 27:
		if (lookahead == 97) {
			state = 82
			goto nextState
		}
		return result
	case 28:
		if (lookahead == 102) {
			state = 83
			goto nextState
		}
		return result
	case 29:
		if (lookahead == 110) {
			state = 84
			goto nextState
		}
		return result
	case 30:
		if (lookahead == 115) {
			state = 85
			goto nextState
		}
		return result
	case 31:
		if (lookahead == 117) {
			state = 86
			goto nextState
		}
		return result
	case 32:
		if (lookahead == 112) {
			state = 87
			goto nextState
		}
		if (lookahead == 116) {
			state = 88
			goto nextState
		}
		return result
	case 33:
		if (lookahead == 50) {
			state = 89
			goto nextState
		}
		return result
	case 34:
		if (lookahead == 52) {
			state = 90
			goto nextState
		}
		return result
	case 35:
		if (lookahead == 108) {
			state = 91
			goto nextState
		}
		return result
	case 36:
		result = true
		lexer.ResultSymbol = 96
		lexer.MarkEnd()
		return result
	case 37:
		if (lookahead == 114) {
			state = 92
			goto nextState
		}
		return result
	case 38:
		if (lookahead == 110) {
			state = 93
			goto nextState
		}
		return result
	case 39:
		if (lookahead == 50) {
			state = 94
			goto nextState
		}
		if (lookahead == 54) {
			state = 95
			goto nextState
		}
		return result
	case 40:
		if (lookahead == 50) {
			state = 96
			goto nextState
		}
		return result
	case 41:
		if (lookahead == 52) {
			state = 97
			goto nextState
		}
		return result
	case 42:
		result = true
		lexer.ResultSymbol = 33
		lexer.MarkEnd()
		return result
	case 43:
		if (lookahead == 101) {
			state = 98
			goto nextState
		}
		return result
	case 44:
		result = true
		lexer.ResultSymbol = 99
		lexer.MarkEnd()
		return result
	case 45:
		if (lookahead == 112) {
			state = 99
			goto nextState
		}
		return result
	case 46:
		result = true
		lexer.ResultSymbol = 119
		lexer.MarkEnd()
		return result
	case 47:
		if (lookahead == 105) {
			state = 100
			goto nextState
		}
		return result
	case 48:
		if (lookahead == 101) {
			state = 101
			goto nextState
		}
		return result
	case 49:
		if (lookahead == 116) {
			state = 102
			goto nextState
		}
		return result
	case 50:
		if (lookahead == 102) {
			state = 103
			goto nextState
		}
		if (lookahead == 116) {
			state = 104
			goto nextState
		}
		return result
	case 51:
		if (lookahead == 111) {
			state = 105
			goto nextState
		}
		return result
	case 52:
		if (lookahead == 116) {
			state = 106
			goto nextState
		}
		return result
	case 53:
		if (lookahead == 116) {
			state = 107
			goto nextState
		}
		return result
	case 54:
		if (lookahead == 100) {
			state = 108
			goto nextState
		}
		if (lookahead == 118) {
			state = 109
			goto nextState
		}
		return result
	case 55:
		if (lookahead == 116) {
			state = 110
			goto nextState
		}
		return result
	case 56:
		if (lookahead == 116) {
			state = 111
			goto nextState
		}
		return result
	case 57:
		if (lookahead == 98) {
			state = 112
			goto nextState
		}
		return result
	case 58:
		if (lookahead == 119) {
			state = 113
			goto nextState
		}
		return result
	case 59:
		if (lookahead == 102) {
			state = 114
			goto nextState
		}
		if (lookahead == 116) {
			state = 115
			goto nextState
		}
		return result
	case 60:
		if (lookahead == 108) {
			state = 116
			goto nextState
		}
		return result
	case 61:
		if (lookahead == 97) {
			state = 117
			goto nextState
		}
		if (lookahead == 109) {
			state = 118
			goto nextState
		}
		if (lookahead == 114) {
			state = 119
			goto nextState
		}
		return result
	case 62:
		if (lookahead == 112) {
			state = 120
			goto nextState
		}
		return result
	case 63:
		if (lookahead == 97) {
			state = 121
			goto nextState
		}
		if (lookahead == 117) {
			state = 122
			goto nextState
		}
		if (lookahead == 121) {
			state = 123
			goto nextState
		}
		return result
	case 64:
		result = true
		lexer.ResultSymbol = 29
		lexer.MarkEnd()
		return result
	case 65:
		result = true
		lexer.ResultSymbol = 30
		lexer.MarkEnd()
		if (lookahead == 112) {
			state = 124
			goto nextState
		}
		return result
	case 66:
		if (lookahead == 50) {
			state = 125
			goto nextState
		}
		if (lookahead == 54) {
			state = 126
			goto nextState
		}
		return result
	case 67:
		if (lookahead == 50) {
			state = 127
			goto nextState
		}
		return result
	case 68:
		if (lookahead == 52) {
			state = 128
			goto nextState
		}
		return result
	case 69:
		result = true
		lexer.ResultSymbol = 32
		lexer.MarkEnd()
		return result
	case 70:
		if (lookahead == 105) {
			state = 129
			goto nextState
		}
		if (lookahead == 115) {
			state = 130
			goto nextState
		}
		return result
	case 71:
		if (lookahead == 101) {
			state = 131
			goto nextState
		}
		if (lookahead == 105) {
			state = 132
			goto nextState
		}
		return result
	case 72:
		if (lookahead == 115) {
			state = 133
			goto nextState
		}
		return result
	case 73:
		if (lookahead == 101) {
			state = 134
			goto nextState
		}
		if (lookahead == 105) {
			state = 135
			goto nextState
		}
		return result
	case 74:
		if (lookahead == 101) {
			state = 136
			goto nextState
		}
		return result
	case 75:
		if (lookahead == 110) {
			state = 137
			goto nextState
		}
		return result
	case 76:
		if (lookahead == 105) {
			state = 138
			goto nextState
		}
		return result
	case 77:
		if (lookahead == 99) {
			state = 139
			goto nextState
		}
		return result
	case 78:
		if (lookahead == 108) {
			state = 140
			goto nextState
		}
		return result
	case 79:
		if (lookahead == 97) {
			state = 141
			goto nextState
		}
		return result
	case 80:
		if (lookahead == 114) {
			state = 142
			goto nextState
		}
		return result
	case 81:
		if (lookahead == 115) {
			state = 143
			goto nextState
		}
		if (lookahead == 116) {
			state = 144
			goto nextState
		}
		return result
	case 82:
		if (lookahead == 116) {
			state = 145
			goto nextState
		}
		return result
	case 83:
		if (lookahead == 97) {
			state = 146
			goto nextState
		}
		return result
	case 84:
		result = true
		lexer.ResultSymbol = 121
		lexer.MarkEnd()
		return result
	case 85:
		if (lookahead == 101) {
			state = 147
			goto nextState
		}
		return result
	case 86:
		if (lookahead == 109) {
			state = 148
			goto nextState
		}
		return result
	case 87:
		if (lookahead == 114) {
			state = 149
			goto nextState
		}
		return result
	case 88:
		if (lookahead == 101) {
			state = 150
			goto nextState
		}
		return result
	case 89:
		result = true
		lexer.ResultSymbol = 44
		lexer.MarkEnd()
		return result
	case 90:
		result = true
		lexer.ResultSymbol = 45
		lexer.MarkEnd()
		return result
	case 91:
		if (lookahead == 115) {
			state = 151
			goto nextState
		}
		return result
	case 92:
		result = true
		lexer.ResultSymbol = 97
		lexer.MarkEnd()
		return result
	case 93:
		result = true
		lexer.ResultSymbol = 98
		lexer.MarkEnd()
		return result
	case 94:
		if (lookahead == 56) {
			state = 152
			goto nextState
		}
		return result
	case 95:
		result = true
		lexer.ResultSymbol = 35
		lexer.MarkEnd()
		return result
	case 96:
		result = true
		lexer.ResultSymbol = 37
		lexer.MarkEnd()
		return result
	case 97:
		result = true
		lexer.ResultSymbol = 39
		lexer.MarkEnd()
		return result
	case 98:
		if (lookahead == 110) {
			state = 153
			goto nextState
		}
		return result
	case 99:
		if (lookahead == 108) {
			state = 154
			goto nextState
		}
		return result
	case 100:
		if (lookahead == 122) {
			state = 155
			goto nextState
		}
		return result
	case 101:
		if (lookahead == 109) {
			state = 156
			goto nextState
		}
		return result
	case 102:
		result = true
		lexer.ResultSymbol = 101
		lexer.MarkEnd()
		return result
	case 103:
		if (lookahead == 101) {
			state = 157
			goto nextState
		}
		return result
	case 104:
		if (lookahead == 101) {
			state = 158
			goto nextState
		}
		return result
	case 105:
		if (lookahead == 112) {
			state = 159
			goto nextState
		}
		return result
	case 106:
		if (lookahead == 99) {
			state = 160
			goto nextState
		}
		return result
	case 107:
		if (lookahead == 97) {
			state = 161
			goto nextState
		}
		return result
	case 108:
		result = true
		lexer.ResultSymbol = 104
		lexer.MarkEnd()
		return result
	case 109:
		if (lookahead == 101) {
			state = 162
			goto nextState
		}
		return result
	case 110:
		result = true
		lexer.ResultSymbol = 122
		lexer.MarkEnd()
		return result
	case 111:
		result = true
		lexer.ResultSymbol = 25
		lexer.MarkEnd()
		if (lookahead == 95) {
			state = 163
			goto nextState
		}
		if (lookahead == 104) {
			state = 164
			goto nextState
		}
		return result
	case 112:
		result = true
		lexer.ResultSymbol = 105
		lexer.MarkEnd()
		return result
	case 113:
		result = true
		lexer.ResultSymbol = 123
		lexer.MarkEnd()
		return result
	case 114:
		result = true
		lexer.ResultSymbol = 117
		lexer.MarkEnd()
		return result
	case 115:
		if (lookahead == 117) {
			state = 165
			goto nextState
		}
		return result
	case 116:
		if (lookahead == 102) {
			state = 166
			goto nextState
		}
		return result
	case 117:
		if (lookahead == 116) {
			state = 167
			goto nextState
		}
		return result
	case 118:
		if (lookahead == 116) {
			state = 168
			goto nextState
		}
		return result
	case 119:
		result = true
		lexer.ResultSymbol = 47
		lexer.MarkEnd()
		if (lookahead == 117) {
			state = 169
			goto nextState
		}
		return result
	case 120:
		if (lookahead == 101) {
			state = 170
			goto nextState
		}
		return result
	case 121:
		if (lookahead == 105) {
			state = 171
			goto nextState
		}
		return result
	case 122:
		if (lookahead == 101) {
			state = 172
			goto nextState
		}
		return result
	case 123:
		result = true
		lexer.ResultSymbol = 126
		lexer.MarkEnd()
		return result
	case 124:
		if (lookahead == 101) {
			state = 173
			goto nextState
		}
		return result
	case 125:
		if (lookahead == 56) {
			state = 174
			goto nextState
		}
		return result
	case 126:
		result = true
		lexer.ResultSymbol = 34
		lexer.MarkEnd()
		return result
	case 127:
		result = true
		lexer.ResultSymbol = 36
		lexer.MarkEnd()
		return result
	case 128:
		result = true
		lexer.ResultSymbol = 38
		lexer.MarkEnd()
		return result
	case 129:
		if (lookahead == 111) {
			state = 175
			goto nextState
		}
		return result
	case 130:
		if (lookahead == 97) {
			state = 176
			goto nextState
		}
		return result
	case 131:
		result = true
		lexer.ResultSymbol = 113
		lexer.MarkEnd()
		return result
	case 132:
		if (lookahead == 122) {
			state = 177
			goto nextState
		}
		return result
	case 133:
		result = true
		lexer.ResultSymbol = 31
		lexer.MarkEnd()
		return result
	case 134:
		if (lookahead == 114) {
			state = 178
			goto nextState
		}
		return result
	case 135:
		if (lookahead == 108) {
			state = 179
			goto nextState
		}
		return result
	case 136:
		if (lookahead == 108) {
			state = 180
			goto nextState
		}
		return result
	case 137:
		if (lookahead == 99) {
			state = 181
			goto nextState
		}
		return result
	case 138:
		if (lookahead == 116) {
			state = 182
			goto nextState
		}
		return result
	case 139:
		if (lookahead == 107) {
			state = 183
			goto nextState
		}
		return result
	case 140:
		result = true
		lexer.ResultSymbol = 46
		lexer.MarkEnd()
		return result
	case 141:
		if (lookahead == 107) {
			state = 184
			goto nextState
		}
		return result
	case 142:
		result = true
		lexer.ResultSymbol = 48
		lexer.MarkEnd()
		return result
	case 143:
		if (lookahead == 116) {
			state = 185
			goto nextState
		}
		return result
	case 144:
		if (lookahead == 105) {
			state = 186
			goto nextState
		}
		return result
	case 145:
		if (lookahead == 101) {
			state = 187
			goto nextState
		}
		return result
	case 146:
		if (lookahead == 117) {
			state = 188
			goto nextState
		}
		return result
	case 147:
		result = true
		lexer.ResultSymbol = 118
		lexer.MarkEnd()
		return result
	case 148:
		result = true
		lexer.ResultSymbol = 95
		lexer.MarkEnd()
		return result
	case 149:
		result = true
		lexer.ResultSymbol = 18
		lexer.MarkEnd()
		if (lookahead == 95) {
			state = 189
			goto nextState
		}
		return result
	case 150:
		if (lookahead == 114) {
			state = 190
			goto nextState
		}
		return result
	case 151:
		if (lookahead == 101) {
			state = 191
			goto nextState
		}
		return result
	case 152:
		result = true
		lexer.ResultSymbol = 41
		lexer.MarkEnd()
		return result
	case 153:
		if (lookahead == 116) {
			state = 192
			goto nextState
		}
		return result
	case 154:
		result = true
		lexer.ResultSymbol = 100
		lexer.MarkEnd()
		return result
	case 155:
		if (lookahead == 101) {
			state = 193
			goto nextState
		}
		return result
	case 156:
		result = true
		lexer.ResultSymbol = 21
		lexer.MarkEnd()
		return result
	case 157:
		if (lookahead == 116) {
			state = 194
			goto nextState
		}
		return result
	case 158:
		if (lookahead == 114) {
			state = 195
			goto nextState
		}
		return result
	case 159:
		result = true
		lexer.ResultSymbol = 102
		lexer.MarkEnd()
		return result
	case 160:
		if (lookahead == 104) {
			state = 196
			goto nextState
		}
		return result
	case 161:
		result = true
		lexer.ResultSymbol = 24
		lexer.MarkEnd()
		return result
	case 162:
		result = true
		lexer.ResultSymbol = 125
		lexer.MarkEnd()
		return result
	case 163:
		if (lookahead == 112) {
			state = 197
			goto nextState
		}
		return result
	case 164:
		result = true
		lexer.ResultSymbol = 27
		lexer.MarkEnd()
		return result
	case 165:
		if (lookahead == 114) {
			state = 198
			goto nextState
		}
		return result
	case 166:
		result = true
		lexer.ResultSymbol = 142
		lexer.MarkEnd()
		return result
	case 167:
		if (lookahead == 105) {
			state = 199
			goto nextState
		}
		return result
	case 168:
		result = true
		lexer.ResultSymbol = 28
		lexer.MarkEnd()
		return result
	case 169:
		if (lookahead == 99) {
			state = 200
			goto nextState
		}
		return result
	case 170:
		if (lookahead == 114) {
			state = 201
			goto nextState
		}
		return result
	case 171:
		if (lookahead == 116) {
			state = 202
			goto nextState
		}
		return result
	case 172:
		result = true
		lexer.ResultSymbol = 131
		lexer.MarkEnd()
		return result
	case 173:
		result = true
		lexer.ResultSymbol = 110
		lexer.MarkEnd()
		return result
	case 174:
		result = true
		lexer.ResultSymbol = 40
		lexer.MarkEnd()
		return result
	case 175:
		if (lookahead == 110) {
			state = 203
			goto nextState
		}
		return result
	case 176:
		if (lookahead == 102) {
			state = 204
			goto nextState
		}
		return result
	case 177:
		if (lookahead == 101) {
			state = 205
			goto nextState
		}
		return result
	case 178:
		if (lookahead == 101) {
			state = 206
			goto nextState
		}
		return result
	case 179:
		if (lookahead == 101) {
			state = 207
			goto nextState
		}
		return result
	case 180:
		if (lookahead == 100) {
			state = 208
			goto nextState
		}
		return result
	case 181:
		result = true
		lexer.ResultSymbol = 89
		lexer.MarkEnd()
		return result
	case 182:
		result = true
		lexer.ResultSymbol = 90
		lexer.MarkEnd()
		return result
	case 183:
		result = true
		lexer.ResultSymbol = 17
		lexer.MarkEnd()
		return result
	case 184:
		result = true
		lexer.ResultSymbol = 91
		lexer.MarkEnd()
		return result
	case 185:
		result = true
		lexer.ResultSymbol = 92
		lexer.MarkEnd()
		return result
	case 186:
		if (lookahead == 110) {
			state = 209
			goto nextState
		}
		return result
	case 187:
		result = true
		lexer.ResultSymbol = 144
		lexer.MarkEnd()
		return result
	case 188:
		if (lookahead == 108) {
			state = 210
			goto nextState
		}
		return result
	case 189:
		if (lookahead == 50) {
			state = 211
			goto nextState
		}
		return result
	case 190:
		if (lookahead == 110) {
			state = 212
			goto nextState
		}
		return result
	case 191:
		result = true
		lexer.ResultSymbol = 132
		lexer.MarkEnd()
		return result
	case 192:
		result = true
		lexer.ResultSymbol = 20
		lexer.MarkEnd()
		return result
	case 193:
		result = true
		lexer.ResultSymbol = 42
		lexer.MarkEnd()
		return result
	case 194:
		if (lookahead == 105) {
			state = 213
			goto nextState
		}
		return result
	case 195:
		if (lookahead == 97) {
			state = 214
			goto nextState
		}
		return result
	case 196:
		result = true
		lexer.ResultSymbol = 103
		lexer.MarkEnd()
		return result
	case 197:
		if (lookahead == 97) {
			state = 215
			goto nextState
		}
		return result
	case 198:
		if (lookahead == 110) {
			state = 216
			goto nextState
		}
		return result
	case 199:
		if (lookahead == 99) {
			state = 217
			goto nextState
		}
		return result
	case 200:
		if (lookahead == 116) {
			state = 218
			goto nextState
		}
		return result
	case 201:
		result = true
		lexer.ResultSymbol = 143
		lexer.MarkEnd()
		return result
	case 202:
		result = true
		lexer.ResultSymbol = 109
		lexer.MarkEnd()
		return result
	case 203:
		result = true
		lexer.ResultSymbol = 111
		lexer.MarkEnd()
		return result
	case 204:
		if (lookahead == 101) {
			state = 219
			goto nextState
		}
		return result
	case 205:
		result = true
		lexer.ResultSymbol = 43
		lexer.MarkEnd()
		return result
	case 206:
		result = true
		lexer.ResultSymbol = 114
		lexer.MarkEnd()
		return result
	case 207:
		result = true
		lexer.ResultSymbol = 115
		lexer.MarkEnd()
		return result
	case 208:
		result = true
		lexer.ResultSymbol = 124
		lexer.MarkEnd()
		return result
	case 209:
		if (lookahead == 117) {
			state = 220
			goto nextState
		}
		return result
	case 210:
		if (lookahead == 116) {
			state = 221
			goto nextState
		}
		return result
	case 211:
		if (lookahead == 48) {
			state = 222
			goto nextState
		}
		return result
	case 212:
		result = true
		lexer.ResultSymbol = 116
		lexer.MarkEnd()
		return result
	case 213:
		if (lookahead == 109) {
			state = 223
			goto nextState
		}
		return result
	case 214:
		if (lookahead == 108) {
			state = 224
			goto nextState
		}
		return result
	case 215:
		if (lookahead == 114) {
			state = 225
			goto nextState
		}
		return result
	case 216:
		result = true
		lexer.ResultSymbol = 106
		lexer.MarkEnd()
		return result
	case 217:
		result = true
		lexer.ResultSymbol = 107
		lexer.MarkEnd()
		return result
	case 218:
		result = true
		lexer.ResultSymbol = 108
		lexer.MarkEnd()
		return result
	case 219:
		result = true
		lexer.ResultSymbol = 112
		lexer.MarkEnd()
		return result
	case 220:
		if (lookahead == 101) {
			state = 226
			goto nextState
		}
		return result
	case 221:
		result = true
		lexer.ResultSymbol = 94
		lexer.MarkEnd()
		return result
	case 222:
		if (lookahead == 50) {
			state = 227
			goto nextState
		}
		return result
	case 223:
		if (lookahead == 101) {
			state = 228
			goto nextState
		}
		return result
	case 224:
		result = true
		lexer.ResultSymbol = 23
		lexer.MarkEnd()
		return result
	case 225:
		if (lookahead == 97) {
			state = 229
			goto nextState
		}
		return result
	case 226:
		result = true
		lexer.ResultSymbol = 93
		lexer.MarkEnd()
		return result
	case 227:
		if (lookahead == 49) {
			state = 230
			goto nextState
		}
		return result
	case 228:
		result = true
		lexer.ResultSymbol = 22
		lexer.MarkEnd()
		return result
	case 229:
		if (lookahead == 109) {
			state = 231
			goto nextState
		}
		return result
	case 230:
		result = true
		lexer.ResultSymbol = 19
		lexer.MarkEnd()
		return result
	case 231:
		result = true
		lexer.ResultSymbol = 26
		lexer.MarkEnd()
		return result
	default:
		return false
	}
}

func loadTables() *ts.Language {
	tables, err := ts.DecodeTables(tablesBlob)
	if err != nil {
		panic("rust: reading tables.zst: " + err.Error())
	}
	characterSets = tables.CharacterSets
	language := &tables.Language
	language.LexFn = tsLex
	language.KeywordLexFn = tsLexKeywords
	language.Scanner = grammar.Scanner()
	return language
}

var (
	loadOnce  sync.Once
	generated *ts.Language
)

// Language returns the rust grammar, decoding its tables when a
// parse needs them.
func Language() *ts.Language {
	loadOnce.Do(func() { generated = loadTables() })
	return generated
}
