package bashclean

import (
	"regexp"
	"testing"

	"github.com/stretchr/testify/assert"
)

// Ported from the shell suite this package replaced, so no finding is lost.
type cleanCase struct{ name, in, want string }

var rewriteCases = []cleanCase{
	{"simple trailing scrub", "ls /nope 2>/dev/null", "set -o pipefail\nls /nope"},
	{"mid-command scrub before &&", "grep foo file 2>/dev/null && ls found", "set -o pipefail\ngrep foo file && ls found"},
	{"all redirect variants in one command", "a 2>/dev/null; b 2> /dev/null; c 2>>/dev/null; d 2>> /dev/null; e 2>'/dev/null'; f 2>\"/dev/null\"", "set -o pipefail\na\nb\nc\nd\ne\nf"},
	{"adjacent pipe after scrub (canonical spacing)", "foo 2>/dev/null|bar", "set -o pipefail\nfoo | bar"},
	{"scrub between pipeline stages", "cmd 2>/dev/null | wc", "set -o pipefail\ncmd | wc"},
	{"multi-digit fd 12>/dev/null untouched", "foo 12>/dev/null", "set -o pipefail\nfoo 12>/dev/null"},
	{"fd 12 kept while fd 2 scrubbed", "foo 12>/dev/null 2>/dev/null", "set -o pipefail\nfoo 12>/dev/null"},
	{"redirect before the command word", "2>/dev/null ls", "set -o pipefail\nls"},
	{"scrub inside a command substitution", "echo $(ls /x 2>/dev/null)", "set -o pipefail\necho $(ls /x)"},
	{"multi-line command scrubbed per statement", "ls /a 2>/dev/null\nls /b 2>/dev/null", "set -o pipefail\nls /a\nls /b"},
	{"literal-string carrier containing 2>/dev/null untouched", ": \"silence with 2>/dev/null here\"", "set -o pipefail\n: \"silence with 2>/dev/null here\""},
	{"&>/dev/null demoted to >/dev/null", "ls /nope &>/dev/null", "set -o pipefail\nls /nope >/dev/null"},
	{"&>>/dev/null demoted to >>/dev/null", "ls /nope &>>/dev/null", "set -o pipefail\nls /nope >>/dev/null"},
	{">&/dev/null demoted to >/dev/null", "ls /nope >&/dev/null", "set -o pipefail\nls /nope >/dev/null"},
	{">/dev/null 2>&1 keeps the stdout discard", "ls /nope >/dev/null 2>&1", "set -o pipefail\nls /nope >/dev/null"},
	{"2>&1 before the stdout discard survives", "ls /nope 2>&1 >/dev/null", "set -o pipefail\nls /nope 2>&1 >/dev/null"},
	{"bare 2>&1 is a merge and survives", "git status 2>&1; git log", "set -o pipefail\ngit status 2>&1\ngit log"},
	{"stderr to a real file survives", "ls /nope 2>errors.log", "set -o pipefail\nls /nope 2>errors.log"},
	{"stderr appended to a real file survives", "ls /nope 2>>errors.log", "set -o pipefail\nls /nope 2>>errors.log"},
	{"discard inside a subshell inside a loop body", "for d in a b; do (cd \"$d\" && git status -sb 2>/dev/null); done", "set -o pipefail\nfor d in a b; do (cd \"$d\" && git status -sb); done"},
	{"herestring alone gets only pipefail", "grep x <<<\"data\"", "set -o pipefail\ngrep x <<<\"data\""},
	{"herestring kept while 2>/dev/null scrubbed", "grep x <<<\"data\" 2>/dev/null", "set -o pipefail\ngrep x <<<\"data\""},
	{"string literal containing <<EOF untouched", ": \"here is <<EOF in a string\"", "set -o pipefail\n: \"here is <<EOF in a string\""},
	{"arithmetic bit shift is not a heredoc", "echo $((1 << 2))", "set -o pipefail\necho $((1 << 2))"},
	{"stdout >/dev/null untouched by scrub and tee", "ls >/dev/null", "set -o pipefail\nls >/dev/null"},
	{"spaced fd (2 >/dev/null) is a stdout-to-/dev/null discard", "echo 2 >/dev/null", "set -o pipefail\necho 2 >/dev/null"},
	{"distinct path /dev/null2 not scrubbed", "cmd 2>/dev/null2", "set -o pipefail\ncmd 2>/dev/null2"},
	{"distinct path /dev/null.log not scrubbed", "cmd 2>/dev/null.log", "set -o pipefail\ncmd 2>/dev/null.log"},
	{"bare mid-command 2>&1 untouched", "cmd 2>&1 | wc", "set -o pipefail\ncmd 2>&1 | wc"},
	{"trailing 2>&1 stripped, >/dev/null kept", "foo >/dev/null 2>&1", "set -o pipefail\nfoo >/dev/null"},
	{"stdout > file becomes tee", "cmd > f", "set -o pipefail\ncmd | tee f"},
	{"stdout >> file becomes tee -a", "cmd >> f", "set -o pipefail\ncmd | tee -a f"},
	{"pipeline > file keeps its pipes", "a | b > f", "set -o pipefail\na | b | tee f"},
	{"quoted expansion target preserved verbatim", "cmd > \"$OUT\"", "set -o pipefail\ncmd | tee \"$OUT\""},
	{"prefix-position redirect rewritten", "> f cmd", "set -o pipefail\ncmd | tee f"},
	{"stdin redirect stays on the producer", "cmd < in > out", "set -o pipefail\ncmd <in | tee out"},
	{"tee not applied to a non-trailing && member", "cmd > f && next", "set -o pipefail\ncmd >f && next"},
	{"tee applies to the trailing && member", "next && cmd > f", "set -o pipefail\nnext && cmd | tee f"},
	{"trailing 2>&1 stripped before tee", "cmd > f 2>&1", "set -o pipefail\ncmd | tee f"},
	{"devnull scrub composes with tee", "x 2>/dev/null > f", "set -o pipefail\nx | tee f"},
	{"a tee stage with its own stdout redirect chains", "cmd | tee a > b", "set -o pipefail\ncmd | tee a | tee b"},
	{"stderr file redirect is not touched", "cmd 2> err.log", "set -o pipefail\ncmd 2>err.log"},
	{"tee not applied inside command substitution", "VAR=$(cmd > f)", "set -o pipefail\nVAR=$(cmd >f)"},
	{"double stdout redirect is skipped", "cmd > a > b", "set -o pipefail\ncmd >a >b"},
	{"process substitution target is skipped", "cmd > >(gzip)", "set -o pipefail\ncmd > >(gzip)"},
	{"bare command gets pipefail", "git status", "set -o pipefail\ngit status"},
	{"pipefail not duplicated when other rules fire", "set -o pipefail; ls -la 2>&1", "set -o pipefail\nls -la"},
	{"set -e; is preserved (pipefail goes in front)", "set -e; npm test", "set -o pipefail\nset -e\nnpm test"},
	{"set -e && chain is preserved", "set -e && npm test", "set -o pipefail\nset -e && npm test"},
	{"set -e on its own line is preserved", "set -e\nnpm test", "set -o pipefail\nset -e\nnpm test"},
	{"trailing |head without spaces", "foo file.txt|head -50", "set -o pipefail\nfoo file.txt"},
	{"trailing | sed -n line select stripped", "ls | sed -n '3p'", "set -o pipefail\nls"},
	{"trailing | sed -n range stripped", "ls | sed -n '1,5p'", "set -o pipefail\nls"},
	{"trailing | sed without -n preserved", "ls | sed 's/a/b/'", "set -o pipefail\nls | sed 's/a/b/'"},
	{"head then sed -n chain unwinds fully", "ls | head -3 | sed -n '1p'", "set -o pipefail\nls"},
	{"trailing | head -c 4k", "foo file.txt | head -c 4k", "set -o pipefail\nfoo file.txt"},
	{"trailing | tail -f", "foo /var/log/syslog | tail -f", "set -o pipefail\nfoo /var/log/syslog"},
	{"trailing | tail -n +2", "foo file.txt | tail -n +2", "set -o pipefail\nfoo file.txt"},
	{"head then tail chain unwinds fully", "cmd | head -5 | tail -2", "set -o pipefail\ncmd"},
	{"deep alternating head/tail chain unwinds fully", "cmd | head -9 | tail -8 | head -7 | tail -6 | head -5 | tail -4 | head -3 | tail -2 | head -1 | tail -1 | head -2 | tail -3", "set -o pipefail\ncmd"},
	{"deep same-filter chain unwinds fully", "cmd | head -1 | head -1 | head -1 | head -1 | head -1 | head -1 | head -1 | head -1 | head -1 | head -1 | head -1 | head -1", "set -o pipefail\ncmd"},
	{"grep-interleaved chain unwinds via iteration", "cmd | head -5 | grep x | tail -2", "set -o pipefail\ncmd"},
	{"head/tail stripped only in the trailing && member", "a | head -2 && b | tail -3", "set -o pipefail\na | head -2 && b"},
	{"scrub is tree-wide but head strip is trailing-only", "foo 2>/dev/null | head -3 && bar 2> /dev/null", "set -o pipefail\nfoo | head -3 && bar"},
	{"| headache untouched (word boundary)", "cmd | headache", "set -o pipefail\ncmd | headache"},
	{"| tailscale untouched (word boundary)", "cmd | tailscale status", "set -o pipefail\ncmd | tailscale status"},
	{"| head5 untouched (word boundary)", "cmd | head5", "set -o pipefail\ncmd | head5"},
	{"head inside $() capture preserved", "VAR=$(ls | head -1)", "set -o pipefail\nVAR=$(ls | head -1)"},
	{"head inside plain command substitution preserved", "echo $(ls | head -1)", "set -o pipefail\necho $(ls | head -1)"},
	{"head inside process substitution preserved", "diff <(ls | head -2) file", "set -o pipefail\ndiff <(ls | head -2) file"},
	{"literal-string carrier containing | head untouched", ": \"foo | head\"", "set -o pipefail\n: \"foo | head\""},
	{"single-quoted trailing | head untouched", ": 'try: cmd | head -3'", "set -o pipefail\n: 'try: cmd | head -3'"},
	{"head on a non-final line preserved", "foo | head -3\nls done", "set -o pipefail\nfoo | head -3\nls done"},
	{"tail on a non-final line preserved", "ls -1 \"$D\" | tail -12\nls done", "set -o pipefail\nls -1 \"$D\" | tail -12\nls done"},
	{"stdout redirect on a non-final line preserved", "make >build.log\nwc -l build.log", "set -o pipefail\nmake >build.log\nwc -l build.log"},
	{"tail on final line is trailing", "foo\nbar | tail -5", "set -o pipefail\nfoo\nbar"},
	{"multi-line mix of all rules (set -e preserved)", "set -e; ls /x 2>/dev/null | head -3\ngrep -r pat . 2>>/dev/null || true", "set -o pipefail\nset -e\nls /x | head -3\ngrep -r pat ."},
	{"sed without -n transforms, not reads", "sed 's/a/b/' file.txt", "set -o pipefail\nsed 's/a/b/' file.txt"},
	{"sed -n on /proc allowed", "sed -n '1p' /proc/meminfo", "set -o pipefail\nsed -n '1p' /proc/meminfo"},
	{"cat /proc file allowed", "cat /proc/meminfo", "set -o pipefail\ncat /proc/meminfo"},
	{"cat /sys file allowed", "cat /sys/class/net/eth0/address", "set -o pipefail\ncat /sys/class/net/eth0/address"},
	{"bounded read of /dev/urandom allowed (and NOT rewritten)", "head -c 100 /dev/urandom", "set -o pipefail\nhead -c 100 /dev/urandom"},
	{"head -n 20 on /proc: 20 is a value, not a file", "head -n 20 /proc/meminfo", "set -o pipefail\nhead -n 20 /proc/meminfo"},
	{"bare cat (stdin) allowed", "x | cat", "set -o pipefail\nx | cat"},
	{"cat - (explicit stdin) allowed", "foo | cat -", "set -o pipefail\nfoo | cat -"},
	{"cat process substitution allowed", "cat <(ls)", "set -o pipefail\ncat <(ls)"},
	{"cat expansion operand allowed (not statically known)", "cat \"$F\"", "set -o pipefail\ncat \"$F\""},
	{"head with no operands mid-pipeline untouched", "cmd | head -5 | wc", "set -o pipefail\ncmd | head -5 | wc"},
	{"cat capture is word-internal (non-goal)", "x=$(cat f)", "set -o pipefail\nx=$(cat f)"},
	{"cat in command substitution is word-internal (non-goal)", "echo $(cat f)", "set -o pipefail\necho $(cat f)"},
	{"catalog is a different command", "catalog f", "set -o pipefail\ncatalog f"},
	{"headache is a different command", "headache -5 f", "set -o pipefail\nheadache -5 f"},
	{"head5 is a different command", "head5 f", "set -o pipefail\nhead5 f"},
	{"command -v cat is a lookup", "command -v cat", "set -o pipefail\ncommand -v cat"},
	{"cat as a grep argument untouched", "grep cat file2", "set -o pipefail\ngrep cat file2"},
	{"rm -rf two targets", "rm -rf a b", "set -o pipefail\nrecycler trash a b"},
	{"plain rm", "rm file.txt", "set -o pipefail\nrecycler trash file.txt"},
	{"rm -r directory", "rm -r build/", "set -o pipefail\nrecycler trash build/"},
	{"rm -R capital recursive", "rm -R build/", "set -o pipefail\nrecycler trash build/"},
	{"rm --recursive --force long forms", "rm --recursive --force build/", "set -o pipefail\nrecycler trash build/"},
	{"rm -v verbose dropped", "rm -v a", "set -o pipefail\nrecycler trash a"},
	{"rm -i interactive dropped", "rm -i a", "set -o pipefail\nrecycler trash a"},
	{"rm -I dropped", "rm -I a b c", "set -o pipefail\nrecycler trash a b c"},
	{"rm bundled -fr cluster", "rm -fr a", "set -o pipefail\nrecycler trash a"},
	{"rm bundled -rfv cluster", "rm -rfv a", "set -o pipefail\nrecycler trash a"},
	{"rm with no targets", "rm", "set -o pipefail\nrecycler trash"},
	{"rm expansion target passed through", "rm -rf \"$DIR\"", "set -o pipefail\nrecycler trash \"$DIR\""},
	{"rm glob target passed through (shell expands it)", "rm -f *.tmp", "set -o pipefail\nrecycler trash *.tmp"},
	{"lone dash is a filename not a flag", "rm -", "set -o pipefail\nrecycler trash -"},
	{"the incident: rm chained onto its own verification", "rm -f budget-guard.js && node budget-guard.ts --verify", "set -o pipefail\nrecycler trash budget-guard.js && node budget-guard.ts --verify"},
	{"-- separator kept for a dash-leading filename", "rm -- -weirdname", "set -o pipefail\nrecycler trash -- -weirdname"},
	{"-- dropped when no target needs it", "rm -rf -- build/", "set -o pipefail\nrecycler trash build/"},
	{"rm on a non-final line rewritten", "rm -f stale.txt\nmake", "set -o pipefail\nrecycler trash stale.txt\nmake"},
	{"rm inside a loop body rewritten", "ls | while read f; do rm -f \"$f\"; done", "set -o pipefail\nls | while read f; do recycler trash \"$f\"; done"},
	{"rm inside a function body rewritten", "clean() { rm -rf build; }", "set -o pipefail\nclean() { recycler trash build; }"},
	{"rm inside a command substitution rewritten", "x=$(rm -f a)", "set -o pipefail\nx=$(recycler trash a)"},
	{"rm in an if branch rewritten", "if stale; then rm -f a; fi", "set -o pipefail\nif stale; then recycler trash a; fi"},
	{"command rm wrapper resolved", "command rm -f x", "set -o pipefail\ncommand recycler trash x"},
	{"backslash rm resolved", "\\rm -f x", "set -o pipefail\nrecycler trash x"},
	{"xargs rm", "xargs rm", "set -o pipefail\nxargs recycler trash"},
	{"xargs -0 rm -f after find -print0", "find . -name \"*.o\" -print0 | xargs -0 rm -f", "set -o pipefail\nfind . -name \"*.o\" -print0 | xargs -0 recycler trash"},
	{"xargs -n 1 rm (separated flag value skipped)", "xargs -n 1 rm", "set -o pipefail\nxargs -n 1 recycler trash"},
	{"xargs -I{} rm {}", "xargs -I{} rm {}", "set -o pipefail\nxargs -I{} recycler trash {}"},
	{"xargs with a different utility untouched", "xargs ls", "set -o pipefail\nxargs ls"},
	{"recycler trash passes through", "recycler trash a", "set -o pipefail\nrecycler trash a"},
	{"recycler restore passes through", "recycler restore a", "set -o pipefail\nrecycler restore a"},
	{"string literal containing rm -rf / untouched", "echo \"rm -rf /\"", "set -o pipefail\n:"},
	{"quoted rm in a grep pattern untouched", "grep \"rm -rf\" script.sh", "set -o pipefail\ngrep \"rm -rf\" script.sh"},
	{"rm as a grep argument untouched", "grep rm file", "set -o pipefail\ngrep rm file"},
	{"rmdir is a different command", "rmdir empty/", "set -o pipefail\nrmdir empty/"},
	{"string containing --nonsense is not a flag", "grep \"rm --nonsense\" f", "set -o pipefail\ngrep \"rm --nonsense\" f"},
	{"find -delete recycles", "find . -name \"*.tmp\" -delete", "set -o pipefail\nfind . -name \"*.tmp\" -exec recycler trash {} +"},
	{"find -delete mid-chain recycles", "cd /tmp && find . -name \"*.o\" -delete", "set -o pipefail\ncd /tmp && find . -name \"*.o\" -exec recycler trash {} +"},
	{"a primary after -delete keeps its place", "find /var -type f -delete -print", "set -o pipefail\nfind /var -type f -exec recycler trash {} + -print"},
	{"truncate -s 0 recycles", "truncate -s 0 build.log", "set -o pipefail\nrecycler trash build.log"},
	{"truncate --size=0 recycles", "truncate --size=0 build.log", "set -o pipefail\nrecycler trash build.log"},
	{"truncate -s0 (joined) recycles", "truncate -s0 build.log", "set -o pipefail\nrecycler trash build.log"},
	{"truncate --size 0 (separated) recycles", "truncate --size 0 build.log", "set -o pipefail\nrecycler trash build.log"},
	{"truncate -s 0 with several targets recycles all of them", "truncate -s 0 a.log b.log", "set -o pipefail\nrecycler trash a.log b.log"},
	{"truncate mid-chain recycles", "cd /tmp && truncate -s 0 out.log", "set -o pipefail\ncd /tmp && recycler trash out.log"},
	{"truncate of a dash-leading name keeps the separator", "truncate -s 0 -- -weird.log", "set -o pipefail\nrecycler trash -- -weird.log"},
	{"git rm --cached passes through", "git rm --cached foo", "set -o pipefail\ngit rm --cached foo"},
	{"git rm -r --cached passes through", "git rm -r --cached src/", "set -o pipefail\ngit rm -r --cached src/"},
	{"find without -delete untouched", "find . -name \"*.tmp\"", "set -o pipefail\nfind . -name \"*.tmp\""},
	{"truncate to a nonzero size untouched", "truncate -s 100 f", "set -o pipefail\ntruncate -s 100 f"},
	{"git rm as a string argument untouched", "grep \"git rm\" notes", "set -o pipefail\ngrep \"git rm\" notes"},
	{"git commit -m rm is not git rm", "git commit -m rm", "set -o pipefail\ngit commit -m rm"},
	{"git log --grep rm is not git rm", "git log --grep rm", "set -o pipefail\ngit log --grep rm"},
	{"shredder is a different command", "shredder f", "set -o pipefail\nshredder f"},
	{"nonexistent target rewrites the same as an existing one", "rm -f /nonexistent/path/that/does/not/exist.txt", "set -o pipefail\nrecycler trash /nonexistent/path/that/does/not/exist.txt"},
	{"trailing 2>&1 removed", "ls -la 2>&1", "set -o pipefail\nls -la"},
	{"trailing || true", "rm -f foo || true", "set -o pipefail\nrecycler trash foo"},
	{"trailing | head", "foo file.txt | head", "set -o pipefail\nfoo file.txt"},
	{"trailing | head -5", "foo file.txt | head -5", "set -o pipefail\nfoo file.txt"},
	{"trailing | head -n 20", "foo file.txt | head -n 20", "set -o pipefail\nfoo file.txt"},
	{"trailing | tail", "foo file.txt | tail", "set -o pipefail\nfoo file.txt"},
	{"trailing | tail -10", "foo file.txt | tail -10", "set -o pipefail\nfoo file.txt"},
	{"trailing | tail -n +5", "foo file.txt | tail -n +5", "set -o pipefail\nfoo file.txt"},
	{"trailing | grep foo", "foo file.txt | grep foo", "set -o pipefail\nfoo file.txt"},
	{"trailing | grep -i foo", "foo file.txt | grep -i foo", "set -o pipefail\nfoo file.txt"},
	{"trailing | grep -v -i foo", "foo file.txt | grep -v -i foo", "set -o pipefail\nfoo file.txt"},
	{"trailing | grep -A 3 foo", "foo file.txt | grep -A 3 foo", "set -o pipefail\nfoo file.txt"},
	{"trailing | grep -E pattern", "foo file.txt | grep -E pattern", "set -o pipefail\nfoo file.txt"},
	{"grep after 2>&1", "ls -la 2>&1 | grep foo", "set -o pipefail\nls -la"},
	{"grep then head chain", "foo file.txt | grep foo | head -5", "set -o pipefail\nfoo file.txt"},
	{"2>&1 with || true", "cmd 2>&1 || true", "set -o pipefail\ncmd"},
	{"head after 2>&1", "ls -la 2>&1 | head -20", "set -o pipefail\nls -la"},
	{"tail then grep chain", "cmd | tail -10 | grep foo", "set -o pipefail\ncmd"},
	{"trailing grep with quoted pipe arg is stripped", "cmd | grep \"foo|bar\"", "set -o pipefail\ncmd"},
	{"|| true mid-command untouched", "cmd || true && ls done", "set -o pipefail\ncmd || true && ls done"},
	{"head mid-pipeline untouched", "cmd | head -5 | wc", "set -o pipefail\ncmd | head -5 | wc"},
	{"tail mid-pipeline untouched", "cmd | tail -10 | wc", "set -o pipefail\ncmd | tail -10 | wc"},
	{"grep mid-pipeline untouched", "cmd | grep foo | wc", "set -o pipefail\ncmd | grep foo | wc"},
	{"grep on a non-final line untouched", "cmd | grep x\nls done", "set -o pipefail\ncmd | grep x\nls done"},
	{"whitespace-only difference gets only pipefail", "  ls -la  ", "set -o pipefail\nls -la"},
	{"mid-script limiting pipes and redirects preserved", "x=1; ls | tail -2; foo f | head -3; du -sh . 2>&1; make >build.log; ls done", "set -o pipefail\nx=1\nls | tail -2\nfoo f | head -3\ndu -sh . 2>&1\nmake >build.log\nls done"},
	{"final statement still trailing in a multi-statement script", "x=1\nls | tail -2\nfoo f | head -3", "set -o pipefail\nx=1\nls | tail -2\nfoo f"},
	{"docker compose restart rewritten", "docker compose restart", "set -o pipefail\ndocker compose up -d --force-recreate"},
	{"docker compose restart preserves service arguments", "docker compose restart api worker", "set -o pipefail\ndocker compose up -d --force-recreate api worker"},
	{"docker compose restart rewritten everywhere", "docker compose restart api && x=$(docker compose restart worker)", "set -o pipefail\ndocker compose up -d --force-recreate api && x=$(docker compose up -d --force-recreate worker)"},
	{"docker compose restart composes with redirect cleanup", "docker compose restart api 2>/dev/null > deploy.log", "set -o pipefail\ndocker compose up -d --force-recreate api | tee deploy.log"},
	{"docker-compose executable is not rewritten", "docker-compose restart api", "set -o pipefail\ndocker-compose restart api"},
	{"docker compose text used as arguments is not rewritten", "grep docker compose restart", "set -o pipefail\ngrep docker compose restart"},
	{"gh run view --log-failed becomes a wait-ci log read", "gh run view 34000890670 --log-failed", "set -o pipefail\ngh wait-ci log 34000890670 --failed"},
	{"gh run view --log becomes a wait-ci log read", "gh run view 34000890670 --log", "set -o pipefail\ngh wait-ci log 34000890670"},
	{"gh run view becomes a wait-ci view", "gh run view 34000890670", "set -o pipefail\ngh wait-ci view 34000890670"},
	{"gh run watch becomes a bare wait-ci", "gh run watch 123", "set -o pipefail\ngh wait-ci 123"},
	{"gh run rerun keeps its flag", "gh run rerun 123 --failed", "set -o pipefail\ngh wait-ci rerun 123 --failed"},
	{"gh run list becomes wait-ci runs", "gh run list", "set -o pipefail\ngh wait-ci runs"},
	{"gh pr checks becomes wait-ci checks", "gh pr checks", "set -o pipefail\ngh wait-ci checks"},
	{"gh run list keeps its flags and their values", "gh run list --branch main --workflow ci.yml", "set -o pipefail\ngh wait-ci runs --branch main --workflow ci.yml"},
	{"gh run view keeps a trailing repo flag", "gh run view 999 --log-failed -R o/r", "set -o pipefail\ngh wait-ci log 999 --failed -R o/r"},
	{"gh run list is rewritten mid-chain too", "cd /repo && gh run list", "set -o pipefail\ncd /repo && gh wait-ci runs"},
	{"gh pr checks with a pull request number is left alone", "gh pr checks 42", "set -o pipefail\ngh pr checks 42"},
	{"gh run view with an expanded run id is left alone", "gh run view \"$ID\" --log-failed", "set -o pipefail\ngh run view \"$ID\" --log-failed"},
	{"an already-correct wait-ci call is never re-rewritten", "gh wait-ci log 123 --failed", "set -o pipefail\ngh wait-ci log 123 --failed"},
	{"non-Actions gh work is untouched", "gh pr list --repo o/r --json number", "set -o pipefail\ngh pr list --repo o/r --json number"},
	{"a gh release download is untouched", "gh release download v1 --repo o/r", "set -o pipefail\ngh release download v1 --repo o/r"},
	{"sleep over-cap integer capped", "sleep 30", "set -o pipefail\nsleep 3"},
	{"sleep over-cap float capped", "sleep 10.5", "set -o pipefail\nsleep 3"},
	{"sleep under cap kept", "sleep 2", "set -o pipefail\nsleep 2"},
	{"sleep boundary 3 kept", "sleep 3", "set -o pipefail\nsleep 3"},
	{"sleep 0.5s suffix under cap kept", "sleep 0.5s", "set -o pipefail\nsleep 0.5s"},
	{"sleep leading-dot float kept", "sleep .5", "set -o pipefail\nsleep .5"},
	{"sleep 30s capped", "sleep 30s", "set -o pipefail\nsleep 3"},
	{"sleep minutes capped", "sleep 1m", "set -o pipefail\nsleep 3"},
	{"sleep hours capped", "sleep 2h", "set -o pipefail\nsleep 3"},
	{"sleep days capped", "sleep 1d", "set -o pipefail\nsleep 3"},
	{"sleep multi-arg sum over cap", "sleep 1m 30", "set -o pipefail\nsleep 3"},
	{"sleep multi-arg sum under cap kept", "sleep 1 1", "set -o pipefail\nsleep 1 1"},
	{"sleep multi-arg float sum just over", "sleep 1.5 1.6", "set -o pipefail\nsleep 3"},
	{"sleep infinity capped", "sleep infinity", "set -o pipefail\nsleep 3"},
	{"sleep variable arg capped", "sleep $DELAY", "set -o pipefail\nsleep 3"},
	{"sleep cmdsubst arg capped", "sleep \"$(get_delay)\"", "set -o pipefail\nsleep 3"},
	{"sleep junk arg capped", "sleep abc", "set -o pipefail\nsleep 3"},
	{"sleep scientific notation is junk", "sleep 1e-3", "set -o pipefail\nsleep 3"},
	{"sleep zero args capped", "sleep", "set -o pipefail\nsleep 3"},
	{"sleep quoted literal under cap kept", "sleep \"2\"", "set -o pipefail\nsleep \"2\""},
	{"sleep quoted suffix capped", "sleep '1m'", "set -o pipefail\nsleep 3"},
	{"sleep prefix assignment preserved", "FOO=1 sleep 30", "set -o pipefail\nFOO=1 sleep 3"},
	{"sleep redirect preserved", "sleep 30 2>>err.log", "set -o pipefail\nsleep 3 2>>err.log"},
	{"sleep capped inside while-loop retry", "while ! nc -z h 22; do sleep 30; done", "set -o pipefail\nwhile ! nc -z h 22; do sleep 3; done"},
	{"sleep capped inside command substitution", "VAR=$(sleep 30)", "set -o pipefail\nVAR=$(sleep 3)"},
	{"sleep capped inside subshell", "(sleep 45)", "set -o pipefail\n(sleep 3)"},
	{"sleep capped inside function body", "f() { sleep 60; }", "set -o pipefail\nf() { sleep 3; }"},
	{"sleep capped in || branch", "nc -z h 22 || sleep 30", "set -o pipefail\nnc -z h 22 || sleep 3"},
	{"sleep cap is per command not per script", "sleep 2 && sleep 2", "set -o pipefail\nsleep 2 && sleep 2"},
	{"sleep as timeout arg untouched", "timeout 5 sleep 30", "set -o pipefail\ntimeout 5 sleep 30"},
	{"sleep inside string word untouched", "grep \"sleep 30\" app.log", "set -o pipefail\ngrep \"sleep 30\" app.log"},
	{"echo separator pattern removed", "echo \"=== section ===\"", "set -o pipefail\n:"},
	{"echo unquoted narration removed", "echo starting build now", "set -o pipefail\n:"},
	{"echo -n flag dropped with removal", "echo -n \"x\"", "set -o pipefail\n:"},
	{"bare echo removed", "echo", "set -o pipefail\n:"},
	{"echo empty string removed", "echo \"\"", "set -o pipefail\n:"},
	{"echo ansi-c quoting is constant", "echo $'a\\nb'", "set -o pipefail\n:"},
	{"echo with spaces and quotes removed", "echo \"has spaces and 'quotes'\"", "set -o pipefail\n:"},
	{"echo removed in && member", "echo done && rm -f x", "set -o pipefail\n: && recycler trash x"},
	{"echo removed as final pipe stage", "x | echo foo", "set -o pipefail\nx | :"},
	{"echo removed in if condition", "if echo checking; then ls; fi", "set -o pipefail\nif :; then ls; fi"},
	{"echo removed in for-loop body", "for i in a b; do echo checking; done", "set -o pipefail\nfor i in a b; do :; done"},
	{"echo removed in until-loop body", "until ready; do echo waiting; done", "set -o pipefail\nuntil ready; do :; done"},
	{"echo removed in elif/else chain", "if a; then echo x; elif b; then echo y; else echo z; fi", "set -o pipefail\nif a; then :; elif b; then :; else :; fi"},
	{"echo removed in case items", "case $x in a) echo one ;; *) echo other ;; esac", "set -o pipefail\ncase $x in a) : ;; *) : ;; esac"},
	{"echo removed under time", "time echo hi", "set -o pipefail\ntime :"},
	{"negated echo keeps negation", "! echo ok", "set -o pipefail\n! :"},
	{"echo removed in nested while+if", "while x; do if y; then echo deep; fi; done", "set -o pipefail\nwhile x; do if y; then :; fi; done"},
	{"echo removed in subshell", "(echo hi)", "set -o pipefail\n(:)"},
	{"echo stderr redirect kept, command removed", "echo warn 2>>err.log", "set -o pipefail\n: 2>>err.log"},
	{"head-strip then echo removal compose", "echo foo | head -1", "set -o pipefail\n:"},
	{"echo variable untouched", "echo \"$VAR\"", "set -o pipefail\necho \"$VAR\""},
	{"echo cmdsubst untouched", "echo $(date)", "set -o pipefail\necho $(date)"},
	{"echo arithmetic untouched", "echo $((1 + 2))", "set -o pipefail\necho $((1 + 2))"},
	{"echo glob untouched", "echo *.txt", "set -o pipefail\necho *.txt"},
	{"echo tilde untouched", "echo ~", "set -o pipefail\necho ~"},
	{"echo assignment capture untouched", "X=$(echo abc)", "set -o pipefail\nX=$(echo abc)"},
	{"echo pipe feed untouched", "echo foo | cat", "set -o pipefail\necho foo | cat"},
	{"echo data into jq untouched", "echo '{\"x\":1}' | jq .x", "set -o pipefail\necho '{\"x\":1}' | jq .x"},
	{"echo stderr dup >&2 untouched", "echo foo >&2", "set -o pipefail\necho foo >&2"},
	{"echo stdout file redirect gets tee only", "echo foo > file", "set -o pipefail\necho foo | tee file"},
	{"redirected block group stays data", "{ echo a; } > f", "set -o pipefail\n{ echo a; } | tee f"},
	{"redirected for-loop stays data", "for i in a; do echo x; done > log", "set -o pipefail\nfor i in a; do echo x; done | tee log"},
	{"echo in function body untouched", "f() { echo hi; }", "set -o pipefail\nf() { echo hi; }"},
	{"echo in coproc untouched", "coproc echo hi", "set -o pipefail\ncoproc echo hi"},
	{"echo in process substitution untouched", "foo | tee >(echo inside)", "set -o pipefail\nfoo | tee >(echo inside)"},
	{"printf bare literal removed", "printf 'hi'", "set -o pipefail\n:"},
	{"printf literal with escape removed", "printf 'done\\n'", "set -o pipefail\n:"},
	{"printf separator pattern removed", "printf \"=== section ===\"", "set -o pipefail\n:"},
	{"printf removed in && member", "printf done && rm -f x", "set -o pipefail\n: && recycler trash x"},
	{"printf removed as final pipe stage", "x | printf foo", "set -o pipefail\nx | :"},
	{"printf stderr redirect kept, command removed", "printf warn 2>>err.log", "set -o pipefail\n: 2>>err.log"},
	{"printf %s format removed", "printf '%s\\n' hi", "set -o pipefail\n:"},
	{"printf %d format removed", "printf '%d' 5", "set -o pipefail\n:"},
	{"printf %s with two constant args removed", "printf '%s' a b", "set -o pipefail\n:"},
	{"printf escaped %% removed", "printf 'a%%b'", "set -o pipefail\n:"},
	{"printf lone %s removed", "printf '%s'", "set -o pipefail\n:"},
	{"printf multi-arg narration removed", "printf starting build now", "set -o pipefail\n:"},
	{"printf -- separator removed", "printf -- '--- build ---\\n'", "set -o pipefail\n:"},
	{"printf variable untouched", "printf \"$VAR\"", "set -o pipefail\nprintf \"$VAR\""},
	{"printf pipe feed untouched", "printf foo | cat", "set -o pipefail\nprintf foo | cat"},
	{"printf stdout file redirect gets tee only", "printf foo > out.txt", "set -o pipefail\nprintf foo | tee out.txt"},
	{"printf cmdsubst untouched", "printf \"$(date)\"", "set -o pipefail\nprintf \"$(date)\""},
	{"printf in function body untouched", "f() { printf hi; }", "set -o pipefail\nf() { printf hi; }"},
	{"printf in coproc untouched", "coproc printf hi", "set -o pipefail\ncoproc printf hi"},
	{"printf %s payload into pipe untouched (heredoc-deny form)", "printf '%s' payload | cat", "set -o pipefail\nprintf '%s' payload | cat"},
	{"command echo removed", "command echo hi", "set -o pipefail\n:"},
	{"builtin printf literal removed", "builtin printf 'hi'", "set -o pipefail\n:"},
	{"command -p echo removed", "command -p echo hi", "set -o pipefail\n:"},
	{"backslash echo removed", "\\echo hi", "set -o pipefail\n:"},
	{"backslash printf removed", "\\printf hi", "set -o pipefail\n:"},
	{"quoted printf word removed", "\"printf\" hi", "set -o pipefail\n:"},
	{"split-quoted printf word removed", "pri'ntf' hi", "set -o pipefail\n:"},
	{"command command echo removed", "command command echo hi", "set -o pipefail\n:"},
	{"command printf format removed", "command printf '%s\\n' x", "set -o pipefail\n:"},
	{"command -v printf is a lookup", "command -v printf", "set -o pipefail\ncommand -v printf"},
	{"command -V echo is a lookup", "command -V echo", "set -o pipefail\ncommand -V echo"},
	{"perlcritic is a different command", "perlcritic file", "set -o pipefail\nperlcritic file"},
	{"perl as a grep argument untouched", "grep perl file", "set -o pipefail\ngrep perl file"},
	{"command -v perl is a lookup", "command -v perl", "set -o pipefail\ncommand -v perl"},
	{"perl inside command substitution not denied", "echo $(perl -e 1)", "set -o pipefail\necho $(perl -e 1)"},
	{"combined script preserves all statements", "echo \"=== deploy ===\"\nscp app host:/srv/ 2>/dev/null\nwhile ! ssh host ok; do sleep 30; done\nout=$(echo probe)\necho done | tee -a log\necho finished", "set -o pipefail\n:\nscp app host:/srv/\nwhile ! ssh host ok; do sleep 3; done\nout=$(echo probe)\necho done | tee -a log\n:"},
	{"narration_remove + sleep_cap + final head_tail compose", "echo start\nsleep 10\nls | tail -5", "set -o pipefail\n:\nsleep 3\nls"},
	{"splat repro keeps every statement (tail -12 and 2>&1 intact)", "cd /Users/mhaynie/repos/splat/splat-vulkan\nPRE=/private/tmp/claude-501/-Users-mhaynie-repos-splat/10878a52-8108-4974-ae5c-3ecf2bb62d3f/scratchpad/premerge-wt/splat-vulkan/build/test-out/t5b\nPOST=build/test-out/t5b\necho \"=== files present ===\"; ls -1 \"$PRE\" \"$POST\" 2>&1 | tail -12\necho \"=== REF: pre-merge vs post-merge ===\"; ./build/splat-compare \"$PRE/odd-size-ref.png\" \"$POST/odd-size-ref.png\" --within 2 --pct 99 --mean 0.5\necho \"=== FROXEL: pre-merge vs post-merge ===\"; ./build/splat-compare \"$PRE/odd-size-froxel.png\" \"$POST/odd-size-froxel.png\" --within 2 --pct 99 --mean 0.5", "set -o pipefail\ncd /Users/mhaynie/repos/splat/splat-vulkan\nPRE=/private/tmp/claude-501/-Users-mhaynie-repos-splat/10878a52-8108-4974-ae5c-3ecf2bb62d3f/scratchpad/premerge-wt/splat-vulkan/build/test-out/t5b\nPOST=build/test-out/t5b\n:\nls -1 \"$PRE\" \"$POST\" 2>&1 | tail -12\n:\n./build/splat-compare \"$PRE/odd-size-ref.png\" \"$POST/odd-size-ref.png\" --within 2 --pct 99 --mean 0.5\n:\n./build/splat-compare \"$PRE/odd-size-froxel.png\" \"$POST/odd-size-froxel.png\" --within 2 --pct 99 --mean 0.5"},
}

var noopCases = []cleanCase{
	{"set -o pipefail already present", "set -o pipefail; ls", ""},
	{"set -eo pipefail recognized", "set -eo pipefail; ls", ""},
	{"set -euo pipefail recognized (and never stripped)", "set -euo pipefail; ls", ""},
	{"set -e -o pipefail recognized", "set -e -o pipefail; ls", ""},
	{"multiple -o pairs recognized", "set -o errexit -o pipefail; ls", ""},
	{"set -o pipefail && chain recognized", "set -o pipefail && ls", ""},
	{"recycler trash is not re-rewritten", "set -o pipefail\nrecycler trash a", ""},
	{"narration removal output is a fixpoint", "set -o pipefail\n:", ""},
	{"sleep cap output is a fixpoint", "set -o pipefail\nsleep 3", ""},
	{"unparseable bash fails open (no injection)", "if true; then", ""},
}

var denyCases = []cleanCase{
	{"plain heredoc denied", "cat <<EOF > /tmp/f\nhello\nEOF", "Write"},
	{"dash heredoc (<<-) denied", "cat <<-EOF\n\thello\nEOF", "Write"},
	{"quoted-delimiter heredoc denied", "cat <<'EOF'\nhello\nEOF", "Write"},
	{"heredoc inside command substitution denied", "x=$(cat <<INNER\nhi\nINNER\n)", "Write"},
	{"heredoc plus 2>/dev/null is denied, not rewritten", "cat <<EOF 2>/dev/null\nsome text\nEOF", "Write"},
	{"direct head after cd && (the incident)", "cd /Users/mhaynie/repos/model-benchmark-ue5/model-benchmark && head -60 src/usage.test.ts", "Use the Read tool"},
	{"file-read deny names Read's offset and limit parameters", "head -60 src/usage.test.ts", "offset and limit"},
	{"sed -n line select on a file denied", "sed -n '3p' file.txt", "Use the Read tool"},
	{"sed -n range select on a file denied", "sed -n '1,10p' file.txt", "Use the Read tool"},
	{"sed --quiet on a file denied", "sed --quiet '3p' file.txt", "Use the Read tool"},
	{"sed -ne cluster on a file denied", "sed -ne '3p' file.txt", "Use the Read tool"},
	{"cat on a file denied", "cat file.txt", "Use the Read tool"},
	{"cat on multiple files denied", "cat notes.md extra.md", "Use the Read tool"},
	{"cat with flag still names a file", "cat -n file.txt", "Use the Read tool"},
	{"head old-style -60 denied", "head -60 file.txt", "Use the Read tool"},
	{"head -n 20 (separated value) denied", "head -n 20 file.txt", "Use the Read tool"},
	{"head --lines=20 denied", "head --lines=20 file.txt", "Use the Read tool"},
	{"tail -20 denied", "tail -20 build.log", "Use the Read tool"},
	{"tail -f on a regular file denied", "tail -f /var/log/syslog", "Use the Read tool"},
	{"cat feeding a pipe still denied", "cat config.json | jq .x", "Use the Read tool"},
	{"head feeding a pipe still denied", "head -1 f | wc", "Use the Read tool"},
	{"cat in a non-leaf && member denied", "foo && cat f && bar", "Use the Read tool"},
	{"cat to a file redirect (concatenation) denied", "cat a.txt b.txt > merged.txt", "Use the Read tool"},
	{"cat inside a function body denied", "f() { cat secret.txt; }", "Use the Read tool"},
	{"cat inside an if branch denied", "if true; then cat f; fi", "Use the Read tool"},
	{"cat on a mid-script line denied", "cat notes.txt\nmake", "Use the Read tool"},
	{"command cat wrapper denied", "command cat f", "Use the Read tool"},
	{"backslash head denied", "\\head -5 f", "Use the Read tool"},
	{"deny beats rewrite (2>/dev/null not scrubbed)", "cat file.txt 2>/dev/null", "Use the Read tool"},
	{"dev lookalike path is not magic", "cat /development/f", "Use the Read tool"},
	{"rm --nonsense denied", "rm --nonsense a", "cannot be translated to recycler trash"},
	{"rm -d (remove empty dirs) denied", "rm -d empty", "cannot be translated to recycler trash"},
	{"rm --one-file-system denied", "rm -rf --one-file-system /mnt/x", "cannot be translated to recycler trash"},
	{"rm --no-preserve-root denied", "rm -rf --no-preserve-root /", "cannot be translated to recycler trash"},
	{"bundled cluster with an unknown letter denied", "rm -rd a", "cannot be translated to recycler trash"},
	{"unknown flag inside a command substitution denied", "x=$(rm --nonsense a)", "cannot be translated to recycler trash"},
	{"xargs rm with an unknown flag denied", "xargs rm --nonsense", "cannot be translated to recycler trash"},
	{"shred denied", "shred /tmp/secret", "recycler trash"},
	{"srm denied", "srm /tmp/secret", "recycler trash"},
	{"git rm denied", "git rm foo", "recycler trash <path> && git add -A"},
	{"git rm -r denied", "git rm -r src/old", "recycler trash"},
	{"git -C dir rm denied (pre-subcommand flag skipped)", "git -C /repo rm foo", "recycler trash"},
	{"truncate -s 0 -r keeps denying", "truncate -r ref.log -s 0 build.log", "recycler trash"},
	{"truncate -s 0 with an unknown flag keeps denying", "truncate -c -s 0 build.log", "recycler trash"},
	{"plain perl denied", "perl -e 'print 1'", "perl is banned"},
	{"versioned perl5.36 denied", "perl5.36 -e 1", "perl is banned"},
	{"command perl wrapper denied", "command perl -e 1", "perl is banned"},
	{"backslash perl denied", "\\perl -e 1", "perl is banned"},
}

func TestRewrites(t *testing.T) {
	for _, tc := range rewriteCases {
		got := Transform(tc.in)
		assert.False(t, got.Denied, "%s: unexpected deny (%s)", tc.name, got.Reason)
		assert.Equal(t, tc.want+"\n", got.Command, "%s", tc.name)
	}
}

func TestNoops(t *testing.T) {
	for _, tc := range noopCases {
		got := Transform(tc.in)
		assert.False(t, got.Denied, "%s: unexpected deny (%s)", tc.name, got.Reason)
		assert.False(t, got.Changed, "%s: expected no change, got %q", tc.name, got.Command)
	}
}

func TestDenies(t *testing.T) {
	for _, tc := range denyCases {
		got := Transform(tc.in)
		if !assert.True(t, got.Denied, "%s: expected a deny", tc.name) {
			continue
		}
		assert.Regexp(t, regexp.MustCompile(tc.want), denyReason(got.Reason), "%s", tc.name)
	}
}
