package ste_test

// capSentences are the ste/sentence-length sentences the blocked fork job
// reported. Each must divide under the cap with both halves whole sentences.
var capSentences = []string{
	"No pre-commit hook covers Go, so this is the only thing holding both trees this fork adds to the formatting the rest of them already uses.",
	"The cgo directives name the library but not the directory it sits in, and the Makefile's CGO_LDFLAGS is what supplies it, so a `go build` of the example binaries outside make cannot link.",
	"Everything the wheel is built from: the AOT source tree (submodule pins included), the archs, and the CUDA and Python versions fork-sgl-kernel-wheel passes to build.sh.",
	"The image installs only this fork's kernel build, so a PyPI wheel of the same version does not count: it lacks the fork's ops and archs.",
	"The project defaults to this repository's name, so the default branch serves at https://sglang.pazer.site/ and every other branch at https://sglang.pazer.site/@<branch>/ (slashes flattened to `-`).",
	"Steps: apply machine-applicable fixes, then fail on anything left (combining --fix with -D warnings can abort the fix phase), then cover sglang-mm's PyO3 bindings + rayon fan-out — both sit behind non-default features, so `--workspace` alone never compiles them.",
	"The -runtime and -devel layers also carry NPP, which nothing in this image links, static archives that no build here links, the Nsight Compute GUI, and a cuDNN that torch never loads (it uses the pip cuDNN).",
	"Package mirrors (Ubuntu, NVIDIA) serve a truncated or mismatched index while a mirror sync is in progress, and apt fails the whole build on that one fetch (\"File has unexpected size ...",
	"Override it with `--build-context sgl_kernel_wheels=<dir of sglang_kernel-*.whl>` to install the kernel built from this checkout, e.g. before that version is published; SGL_KERNEL_WHEEL_REQUIRED=1 then fails the build instead of falling back to PyPI.",
	"flashinfer downloads any cubin it cannot find, and JIT-builds any jit-cache module it cannot find, so an image run on another GPU still works.",
	"The cgo directives name the library but not the directory it sits in; LIB_DIR is this file's answer, so the Go side is built and vetted here.",
	"The ranks connect to the go-ipc service of the given name; the process exits non-zero when the ranks diverge, once every rank has heard why.",
	"A rank that diverges, that exits, or that does not arrive within the lockstep timeout fails the group: every rank hears the reason as a call error instead of hanging.",
	"A production log (timestamped lines, several boots) adds sections: the boots it holds, every cold prompt with its measured stall beside the policies, and a replay of each stalled boot's own traffic through the engine.",
	"A pool with no host tier loses an evicted prefix outright, so the next turn of that conversation recomputes its whole input; a host tier that can hold it turns the same eviction into a reload.",
	"Package kv models the device KV cache and the HiCache host tier the scheduler admits against: one cached prefix per conversation, whole-prefix eviction to host, and the reload or recompute an evicted prefix costs.",
	"A prefix larger than the whole host tier is lost outright, and so is each host copy dropped for it; both come back as evictions the caller prices.",
	"CountRecompute records what a request found on arrival: a conversation that had been served before and now matches less than half of its input is paying for its whole prefix again.",
	"Package report renders the parsed log facts and both models' results as a side-by-side before/after, and states which numbers are measured, which are derived, and which the log cannot supply at all.",
	"The prefill share is the balancer's split knob, so changing it must change how the window is divided: a larger prefill share means a faster prefill and less generation, monotonically.",
	"Since batch-size scaling of decode cost is not measurable from this log, the default model charges a flat cost per step, and the consequence must be exactly what \"flat\" means: the batch generates proportionally more while each conversation's rate is unchanged.",
	"Mixed-chunk tokens ride on top of decode's half and never replace it: a chunk that gives each running request one token is still followed by pure decode worth its own time, so no stream collapses to a token per chunk.",
	"timeBalance implements the shipped balancer: it keeps a running balance of measured prefill seconds minus measured decode seconds, settled only while both classes contend, and defers prefill while the balance is positive.",
	"burst counts prefill tokens since decode last caught up; a chunk continuation runs only once it is zero, and no batch runs once it reaches a chunk.",
	"The cold chunks are exactly the steps of the isolated stretch, so their costs are measured rather than modelled, and the decode cost is the measured median decode step.",
	"StreamSeconds is the time every stream in the run spent past its first token and inside the window: the denominator a throughput has to be divided by before it can be compared between policies that admit streams at different times.",
	"SingleTokenSamples counts the per-token inter-token samples that came from a one-token delivery, and the total sample count, for the streams the ITL percentiles are measured over: with speculative decoding a delivery of N tokens contributes N samples of gap/N, so a delivery's share of a percentile depends on how many tokens it carried, not only on how long the wait was.",
	"Cost per prefill token rises with the context attention reads, so a token bound alone lets a chunked prompt's later chunks stall decode for several times the seconds one chunk promises.",
	"The continuation's cap is the GPU seconds one chunk is worth at the measured average rate, priced at the marginal rate of the batch that ran.",
	"The prefill rates are prefill measurements: a decode batch also reports extend tokens (one per running request) and costs an order of magnitude more per token, so letting one in would price prefill work at decode cost and un-bind every continuation cap.",
	"The debt floors are the line both balancers differ on besides the stall bound: a decode slice longer than the prefill it faces can never become credit under PREV, and under NEW is credit up to one decode batch.",
	"TestFeaturesTablePinsTheModes guards the comparison itself: each mode's rule set is what the Python at its own commit does, and those must differ only where the ports say they do.",
	"A chunk continuation may not run while any prefill tokens are unrepaid, and a fresh prefill may run only inside the bound; the token budget then caps what the next batch may take.",
	"Balancer is PrefillDecodeBalancer (prefill_decode_balancer.py), shared by both balancing modes: Prev selects the balance floored at zero with no token bound and no piggyback credit, and the default selects HEAD's rules.",
	"Without contention the balance is cleared and nothing is deferred; continuesChunk says the pending prefill work is the next chunk of a request already being chunked.",
	"A cold prompt whose run ended before it reached a first token has no arrival-to-first-token interval, and must not be priced as if it did.",
	"SeedValues lists one metric's value for each seed of one policy, in seed order, so a comparison can be read against the spread across seeds rather than against a single pooled number.",
	"Judge compares one metric between the new policy and another, returning the shortfall as a fraction of the other value: positive only when the new policy is worse by more than TieRelative.",
	"Deficient reports how far a falls short of b under the metric's direction, as a fraction of b: positive when a is worse, negative when a is better.",
	"The workload's conversations do not exist until their cold prompts are prefilled, so the tokens a policy can deliver are bounded by the stream-seconds its admissions bought; the rate per stream-second is the comparable quantity.",
	"boundName is the derivation that claims a cell, or \"\" for one none does: an unclaimed loss fails the test, which is the honest outcome for a metric that could have improved.",
	"boundCell returns the check for a losing cell, keyed by the mechanism rather than by the scenario, so a cell can only be excused by an argument that applies to it.",
	"The cold TTFT bounds below rest only on the priced ones, so the count is part of the evidence; a seed that excluded any is listed on its own line with the reason.",
	"Pairing is what makes both accounts comparable; the difference of their terms is the whole content of the bounds below, and a window either policy failed to serve is counted.",
	"TestContractEveryScenarioEveryMetric is the comparison's contract: NEW is at least as good as OLD and as PREV on each of the metrics, in that metric's better direction.",
	"Cells that fall inside TieRelative are ties; cells beyond it must be wins or must be argued in the derivation named beside them, which this test then checks instead of the win.",
	"GPU to a saturating cold prefill, so it reaches first token after the prompt's own prefill work and nothing else, while any policy that keeps streams generating spends that window on prefill and decode together.",
	"The bound is arithmetic, from docs/derivation-cold-ttft-vs-old.md: the same prompt's own prefill work is identical under both policies, and NEW's extra wait must equal the time it spent on decode, on the follow-ups the cede admitted beside the chunk, and on idle, with nothing else left over.",
	"The prompt's own work must be the same quantity under both policies; if it is not, the comparison is not of scheduling but of what got computed.",
	"OLD must have spent only a stated share of the cold windows on decode; that is what makes \"OLD handed the prompt the whole GPU\" the mechanism at work rather than a story told after the fact.",
	"So the cell is arguable only if NEW delivered at least as many agent tokens in those windows, and the loss is then arithmetically the extra seconds those tokens spread over.",
	"Those seconds are bounded from below by the mixed channel's own price: a stream riding a prefill batch earns one token per pass, so no stream-second served that way can return more than one token per batch.",
	"If NEW's extra seconds returned less than the channel's floor, they were life-support and not service, and this bound says so rather than excusing the cell.",
	"rowTokenFloor is the highest rate a stream can hold while it is only ever served as a mixed batch's decode row: one token per forward pass, so one over the longest pass NEW launched inside the cold windows.",
	"boundColdTTFTvsPrev argues a cell of a different kind: PREV runs the same balancer on the same prompt, so there is no whole-GPU asymmetry to invoke.",
	"Both accounts close by construction, so subtracting them is an identity over the buckets and the bound's whole content is which of them may carry the gap.",
	"NEW may be later than PREV by the follow-up prefill its cede let in beside the chunk, by the decode rows it folded into the cold prompt's batches, by the per-pass overhead and reload copy those batch-mates made the pass pay, and by the decode those follow-ups kept alive.",
	"Own is the prompt's chunks priced on their own, with no overhead and no batch-mates in it, so a policy cannot move it by scheduling.",
	"The percentile is taken over per-token samples, and a delivery of N tokens contributes N samples of gap/N, so which delivery the named sample came from is a count, not a guess: the class that fills the p(1-q) tail owns the reported number.",
	"A mixed delivery is one token carried by a prefill batch, so it files that batch's whole wall clock as one sample; a policy that serves its streams only in decode batches files one sample per batch covering several tokens.",
	"When that class alone reaches the tail's slot count the named sample is a ride, and the bound is that it is not longer than one of NEW's own forward passes -- the stall bound in another unit.",
	"itlBand is the population one inter-token percentile is drawn from, split by the delivery each sample came from and by the prefill passes its gap waited out.",
	"itlPassBand measures the band over NEW's runs and the opponent's, per run: the batches of one seed cannot be attributed to another seed's deliveries, so the populations are reduced per run and summed, never pooled into one trace.",
	"checkPassCost states the arithmetic of a tail made of samples that waited out one prefill pass: the wait is one pass and one step, its whole length is work some other request was served, and NEW's own decode steps are still the faster ones.",
	"boundTailAdmissible is the shared test that the policy being beaten was withholding tokens outright: delivered volume inside the cold prefills is the direct measure of that.",
	"The stream rate is not: it divides that volume by stream-seconds the policy chose for itself, so a policy serving strictly more tokens can post a lower rate.",
	"mixedRowTally counts the decode rows NEW's prefill batches carried and the longest forward pass NEW launched: the population that can file a one-token sample at prefill cost, and the ceiling on such a sample.",
	"Every turn there misses its prefix, so the prefill batches are long, and NEW folds one decode row per running request into each of them: a served token is charged the whole batch.",
	"The bound is therefore that NEW's percentile is a forward pass it launched itself, and that the samples which put it there are no more numerous than the rows.",
	"A bound whose document is missing, or a document no bound reads, means the excuse in the test and the argument on disk have drifted apart -- the test would keep passing while the reasoning it cites no longer exists.",
	"boundName is consulted for every scenario the suite measures, so the set it can return is fixed by the table rather than by which cells happen to lose on this run.",
	"The engine records a row's token at its mixed batch's end and a decode step's accepted tokens at that batch's end, so (request, time) names one batch.",
	"A mixed batch hands one token per riding request where a decode step hands the sampled accept length, so the same wall-clock wait is divided differently.",
	"The tail lines name the class the reported p99 and p99.9 fall in, which is decided by each class's weight in samples, not its delivery count.",
	"WriteGapDiagnostic prints the inter-token gap distribution and the batch sequence around the widest gaps, so a latency difference can be traced to the batches that caused it rather than argued about.",
	"decodeWait is the GPU time held between the decode batch before the stretch and the decode batch after it: the whole window a stream sees no decode step.",
	"prefillBatch is get_new_batch_prefill: the chunked request's next chunk first, capped by the cede and the balancer's token budget, then the waiting queue in order until a request cannot be added.",
	"advanceRows steps the requests a mixed prefill batch decodes and drops the ones that ran out: speculative decoding degrades to a plain decode inside a mixed step, so every row is one token.",
	"cedeFair is the revised cede: it amortizes the half over the chunked request's progress since it first ceded, so a chunk it ran alone banks room for a follow-up of up to a whole chunk in one step.",
	"MixedItems is the composition of the batch that finished C1: its tail, the follow-up's uncached work, and what is left of the chunk budget for the next cold prompt.",
	"TestMergedTraceAttributesEverySeed checks the merge against the seeds it joined: the per-class sample counts must be the sum of what each run produced on its own, because a delivery counted once as \"mixed\" in one run cannot arrive in the merged trace as \"decode\", and one lost to a key collision cannot reappear anywhere.",
	"TestGapDiagnosticScenarioB dumps, for each policy, where scenario B's inter-token latency comes from: the gap distribution, the class of batch that delivered each token, the cost of a single prefill batch, and the batch sequence around the widest gaps.",
	"classifyDeliveries keys a delivery by (request id, delivery time) because within one run that pair names exactly one batch, but ids are assigned per seed, so seeds can present the same pair with different classes and the merged map would label both with whichever batch wrote last.",
	"Lines that follow a prefill are excluded because their throughput window contains the prefill; they are reported, not fitted, and the gap between both populations is the reason.",
	"TestRunIsDeterministic pins the entry point's promise: the same scenario, policy and seed produce byte-identical tables, and a parallel suite reports what a serial one does.",
	"The composition depends on the page rounding, the token budget, the cede's half-chunk rule and which prefix the pool reports for the follow-up, so it fails if any of those drift.",
	"One line is one request; a line with #new-seq n and pending tokens holds one chunked prompt that took the chunk and n-1 follow-ups that took the rest, which the log does not itemise, so they share it evenly.",
	"chainTokens sums the chunks that continue the prompt started at prefill[i]: the following lines with one sequence and no prefix hit, up to and including the first that is not a full chunk or leaves nothing pending.",
	"OnFinish releases the conversation's next turn at its measured arrival, or now if the reply it follows finished later than the log's own run did: a client cannot send its next turn before it has the answer.",
	"A line admitting several requests does not itemise their prefix hits, but each follow-up is some conversation's next turn: the most recently idle conversations whose last prompts add up to the line's hit are the ones, and each's hit is its own last prompt.",
	"A prompt that never reached its first token keeps a window that runs to the end of the measurement, so the streams it crowded out are still counted against the policy that left it unserved.",
	"stalledFraction is the share of stream time spent inside a stall longer than a second, which separates one unlucky stream from a system that stalls always.",
	"Package sim runs the scheduler as a discrete-event simulation: requests arrive, batches are formed by the shipped batch-formation rules, each batch costs the GPU time the production log calibrated, and those scheduler policies choose between prefill and decode under their own control laws.",
	"The policies are the only difference between multiple runs of the same scenario: arrivals, batch formation, admission against the KV pool, the cost model and the acceptance draws are shared, so a metric that moves is a policy effect.",
	"If PREV ever stopped differing from NEW -- a rule ported as a no-op, a feature flag wired to the wrong mode -- every comparison against it would still pass while proving nothing, because a policy cannot lose to a copy of itself.",
	"The dense cold cadence and the busy short-chat scenario land above the line, the sparse cadence below it, and that is the whole difference between NEW winning p99 in one and losing it in the other.",
	"TestScenarioBBalanceWinsAgainstPrev pins the scenario-B comparisons the balancer decides, over the committed seeds: a change to the control law that gives one of them back fails the build instead of costing a re-read of the printed table.",
	"ITL p99 is absent on purpose: docs/derivation-itl-percentiles-under-mixed-chunk.md derives that cell from the delivery accounting rather than from the schedule.",
	"TestMixedRideIsWhatDecidesTheP99Cell runs scenario B with mixed chunked prefill on and off for the interleaving policies, to separate what the control law costs from what the delivery form costs.",
	"The ride hands each running request one token per prefill batch, so it halves the longest stall and, because the metric divides a gap by the tokens it carried, raises that policy's own ITL p99.",
	"A prefill batch's seconds are linear in every prefill term, so the scheduler's own ratios -- average and marginal seconds per token, which is what the continuation cap and the token budget divide -- are unchanged; only the wall clock each prefill batch occupies moves, by the factor itself.",
	"A cold prompt's own prefill is part of its time to first token, and every chunk a stream waits out is prefill wall clock, so both must grow with the prefill cost.",
	"OLD is the cleaner case: it runs prefill whenever one can be formed, so its stall is prefill seconds with no feedback loop to argue with.",
	"The sweep and every scenario number are only evidence about the real cost model if the model is what drives them: perturbing a calibrated cost has to move the reported metrics in the direction that cost implies.",
	"The first variant is the reference the others are read against and perturbs nothing by design; every other row has to change something, or it measures the reference twice.",
	"TestSweepCoversThePerturbations pins the sensitivity sweep's breadth: one-at-a-time perturbations of the calibrated cost terms, the scheduler's own knobs and the workload, each compared across the policies.",
	"SweepVariants returns the one-at-a-time perturbations: the calibrated cost terms, the speculative and overlap settings, the chunk size, the queue policy, the traffic shape, and the cache tiers.",
	"ShouldHold is should_hold: a request whose own conversation is already resident on device is never held, only the first eviction-triggering candidate of a pass is adjudicated, and a held head goes through once it has waited longer than rebuilding the device pool would take.",
	"Every prompt that held the GPU for a few seconds with requests running is a stall, measured from its first chunk to the decode step after its last.",
	"A production log is many process lifetimes in one file: every restart prints a new server_args line, workers overlap during a rolling update, and a cold run of chunks that straddles a restart is prompts.",
	"A server_args line opens a boot for the worker that printed it; every later line from that worker belongs to it until the worker prints another server_args line.",
	"Lines with no worker (the bare format) belong to the most recently opened boot, and a log with no server_args line at all is one boot with ArgsKnown=false, whose",
	"A stretch is what a stall measures: the GPU ran nothing but prefill from its first step to the decode step after it, however many prompts arrived and joined in the meantime.",
	"Tokens count every prefill step's work, its RunningAtStart is #running-req on the first step that had any, and its CtxStart is the first cold run's.",
	"Cold runs never cross a boot; the largest run anywhere is the fit set and every other run of at least minHoldoutChunks chunks is a holdout.",
	"The decode step time pools steady single-request lines from every boot, and the pool size is reported per boot (boots with different --context-length carry different pools) with the fit boot's used for the calibration.",
	"The quadratic form is a claim about the log, not a constant: the second cold run was never looked at by the fit and must still be predicted closely, and a linear form must be visibly worse on it.",
	"A cost model that is not increasing in the work it prices cannot be a cost model; this fails if a fit coefficient ever goes negative on a longer context.",
	"FitDecode solves the step time of the log's steady single-stream decodes, where the line before it was also a decode line: step seconds are the accepted tokens over the gen throughput that line reports.",
	"DevicePoolTokens derives the KV pool capacity from the log: every decode line reports both the tokens held and the fraction of the pool that is, so their ratio is the capacity.",
	"MeanCtx is the context of the steady single-request lines the base term was solved at, so a term can be re-scaled without moving the fitted.",
	"Runs in the log are isolated cold prompts, the first with nothing running and the second with requests running, which makes the second a genuine holdout for the fit.",
	"FitPrefill fits the quadratic in mid-context to the logged cold chunks, using the first run as the fit set and the second as the holdout.",
	"The collapsed rate reads back as a share of steps: the band the operator reported is partial starvation, well under the total starvation the log shows.",
	"The cold window must be the incident's C1: what its first chunk left pending, every one of its full chunks, and the isolation the log shows: full chunks, no cache reuse, nothing else on the GPU.",
	"The prefill sag is measured, not invented: the steady band is the log's second chunk and the bottom its deepest one, each the rate the line printed.",
	"Package trace parses a live serving log into the sequence of scheduler steps it records, so a simulation can be driven by measured timings instead of constants chosen to produce a desired answer.",
	"The first chunk of a fresh sequence runs cold-start work, so the steady band and the sag's bottom are taken from the chunks after it.",
	"ColdChunks writes a prompt of tokens prefilled from context ctx0 in chunks: every full chunk alone, with no prefix hit, and a final partial chunk when tokens is not a multiple of chunk.",
	"Package tracetest writes serving logs in the production format for tests: timestamped, worker-prefixed lines with the server_args header, batch lines, completions, kernel compiles and the signals that end a boot.",
	"ColdPrompt writes a chunked cold prompt of tokens, running behind running decoding requests: the first chunk reports the whole prompt pending, each later chunk what is left.",
	"Stalled is a canned boot: server_args, a warm-up, a few conversations decoding, a cold prompt of chunks*4096 tokens that stalls them, and a return to decoding, ending in a drain.",
	"DefaultTraffic is a boot of conversations whose contexts stay far apart, so every turn names its conversation unambiguously: a returning prompt, a long turn on a cached prefix and fresh cold prompts larger than any conversation.",
	"Corpus is a deployment's log across restarts: a boot at the shorter context length that crashes, a boot that compiles kernels while serving and drains, a hierarchical-cache boot carrying the longest cold prompt, and a boot the log stops in the middle of.",
	"Up to a chunk it is one line; past that the first line carries the hit and a full chunk and every later chunk reuses nothing, with #pending-token counting what is left.",
	"Admission evicts the least recently used idle prefixes, whole, when the free space is short; an optional host tier keeps what was evicted, and a hit there is reloaded instead of recomputed.",
	"The resident prefix stays in device memory for the run (it moves from the cached total to the reservation), a host hit is reloaded into device memory, and the rest is computed: device space is needed for everything but the resident prefix.",
	"Each stream draws from its own generator, so both engines see the same turn sizes and think times whatever order they finish in; the random cold prompts are a precomputed schedule both engines share.",
	"A burst of at most one chunk's tokens runs before decode must catch up; a chunk continuing a long prompt is bounded in GPU seconds at its marginal (context-inflated) rate.",
	"An allowlist rather than a deny-list because the flags that matter are the ones that turn a read into a write: `-X POST`, `--method`, `--field`, `--input`.",
	"Compiled under `cfg(test)` off Linux as well, because the emitted argv IS the contract (the option order is what makes a later bind win, and what keeps the CI host-worker fd an option rather than a program argument) and an ordering only one host can assert is one that regresses quietly everywhere else.",
	"The whole point of the fd contract, end to end on macOS: a process inside the real Seatbelt jail, holding only the fd number the jail handed it, reaches the real host worker — the shipped worker loop running as a real unsandboxed child — and gets a framed answer back.",
	"Then `(deny file-read*)` and `(deny file-write*)` take every file access away, and the rules that follow give each kind of access back only for the paths the jail is supposed to expose: - `/dev` (a terminal, a PTY, `/dev/null`) — read and write. - a `--rw` mount — read and write. - a `--ro` mount — read only. - the read-only system base (including the macOS `/System`,",
	"An idp that writes both the snake_case and the camelCase principal key — which is what a token relayed through a translating gateway looks like — must still be readable, not rejected as a duplicate field.",
}
