// Code generated by ts-translate. DO NOT EDIT.

package typescript

import (
	_ "embed"
	"sync"

	ts "github.com/wow-look-at-my/go-tree-sitter"
	grammar "github.com/wow-look-at-my/go-tree-sitter/grammars/typescript"
)

//go:embed tables.zst
var tablesBlob []byte

var characterSets [][]ts.CharacterRange

func tsLex(lexer *ts.Lexer, state ts.StateID) bool {
	result := false
	skip := false
	eof := false
	var lookahead int32
	_, _ = eof, lookahead
	goto start
nextState:
	lexer.Advance(skip)
start:
	skip = false
	lookahead = lexer.Lookahead
	eof = lexer.EOF()
	switch state {
	case 0:
		if eof {
			state = 76
			goto nextState
		}
		switch lookahead {
		case 33:
			state = 89
			goto nextState
		case 34:
			state = 169
			goto nextState
		case 35:
			state = 6
			goto nextState
		case 36:
			state = 206
			goto nextState
		case 37:
			state = 149
			goto nextState
		case 38:
			state = 128
			goto nextState
		case 39:
			state = 170
			goto nextState
		case 40:
			state = 90
			goto nextState
		case 41:
			state = 92
			goto nextState
		case 42:
			state = 79
			goto nextState
		case 43:
			state = 141
			goto nextState
		case 44:
			state = 86
			goto nextState
		case 45:
			state = 145
			goto nextState
		case 46:
			state = 97
			goto nextState
		case 47:
			state = 192
			goto nextState
		case 48:
			state = 197
			goto nextState
		case 58:
			state = 93
			goto nextState
		case 59:
			state = 91
			goto nextState
		case 60:
			state = 153
			goto nextState
		case 61:
			state = 82
			goto nextState
		case 62:
			state = 162
			goto nextState
		case 63:
			state = 212
			goto nextState
		case 64:
			state = 209
			goto nextState
		case 91:
			state = 94
			goto nextState
		case 92:
			state = 33
			goto nextState
		case 93:
			state = 95
			goto nextState
		case 94:
			state = 131
			goto nextState
		case 96:
			state = 190
			goto nextState
		case 123:
			state = 85
			goto nextState
		case 124:
			state = 134
			goto nextState
		case 125:
			state = 87
			goto nextState
		case 126:
			state = 166
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 198
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 73
			goto nextState
		}
		if (lookahead > 64) {
			state = 207
			goto nextState
		}
		return result
	case 1:
		if (lookahead == 10) {
			skip = true
			state = 24
			goto nextState
		}
		if (lookahead == 47) {
			state = 17
			goto nextState
		}
		if (lookahead == 91) {
			state = 32
			goto nextState
		}
		if (lookahead == 92) {
			state = 72
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 193
			goto nextState
		}
		if (lookahead != 0) {
			state = 194
			goto nextState
		}
		return result
	case 2:
		switch lookahead {
		case 33:
			state = 89
			goto nextState
		case 34:
			state = 169
			goto nextState
		case 35:
			state = 31
			goto nextState
		case 37:
			state = 149
			goto nextState
		case 38:
			state = 128
			goto nextState
		case 39:
			state = 170
			goto nextState
		case 40:
			state = 90
			goto nextState
		case 41:
			state = 92
			goto nextState
		case 42:
			state = 79
			goto nextState
		case 43:
			state = 140
			goto nextState
		case 44:
			state = 86
			goto nextState
		case 45:
			state = 144
			goto nextState
		case 46:
			state = 97
			goto nextState
		case 47:
			state = 147
			goto nextState
		case 48:
			state = 197
			goto nextState
		case 58:
			state = 93
			goto nextState
		case 59:
			state = 91
			goto nextState
		case 60:
			state = 153
			goto nextState
		case 61:
			state = 82
			goto nextState
		case 62:
			state = 162
			goto nextState
		case 63:
			state = 212
			goto nextState
		case 64:
			state = 209
			goto nextState
		case 91:
			state = 94
			goto nextState
		case 92:
			state = 35
			goto nextState
		case 93:
			state = 95
			goto nextState
		case 94:
			state = 131
			goto nextState
		case 96:
			state = 190
			goto nextState
		case 123:
			state = 85
			goto nextState
		case 124:
			state = 134
			goto nextState
		case 125:
			state = 87
			goto nextState
		case 126:
			state = 166
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 198
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 2
			goto nextState
		}
		if (lookahead > 35) {
			state = 207
			goto nextState
		}
		return result
	case 3:
		switch lookahead {
		case 33:
			state = 89
			goto nextState
		case 34:
			state = 169
			goto nextState
		case 35:
			state = 31
			goto nextState
		case 37:
			state = 149
			goto nextState
		case 38:
			state = 128
			goto nextState
		case 39:
			state = 170
			goto nextState
		case 40:
			state = 90
			goto nextState
		case 41:
			state = 92
			goto nextState
		case 42:
			state = 79
			goto nextState
		case 43:
			state = 140
			goto nextState
		case 44:
			state = 86
			goto nextState
		case 45:
			state = 144
			goto nextState
		case 46:
			state = 97
			goto nextState
		case 47:
			state = 147
			goto nextState
		case 48:
			state = 197
			goto nextState
		case 58:
			state = 93
			goto nextState
		case 59:
			state = 91
			goto nextState
		case 60:
			state = 153
			goto nextState
		case 61:
			state = 82
			goto nextState
		case 62:
			state = 162
			goto nextState
		case 63:
			state = 212
			goto nextState
		case 64:
			state = 209
			goto nextState
		case 91:
			state = 94
			goto nextState
		case 92:
			state = 35
			goto nextState
		case 93:
			state = 95
			goto nextState
		case 94:
			state = 131
			goto nextState
		case 96:
			state = 190
			goto nextState
		case 123:
			state = 84
			goto nextState
		case 124:
			state = 133
			goto nextState
		case 125:
			state = 87
			goto nextState
		case 126:
			state = 166
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 198
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 3
			goto nextState
		}
		if (lookahead > 35) {
			state = 207
			goto nextState
		}
		return result
	case 4:
		switch lookahead {
		case 33:
			state = 89
			goto nextState
		case 37:
			state = 148
			goto nextState
		case 38:
			state = 129
			goto nextState
		case 40:
			state = 90
			goto nextState
		case 41:
			state = 92
			goto nextState
		case 42:
			state = 80
			goto nextState
		case 43:
			state = 139
			goto nextState
		case 44:
			state = 86
			goto nextState
		case 45:
			state = 143
			goto nextState
		case 46:
			state = 96
			goto nextState
		case 47:
			state = 146
			goto nextState
		case 58:
			state = 93
			goto nextState
		case 59:
			state = 91
			goto nextState
		case 60:
			state = 154
			goto nextState
		case 61:
			state = 28
			goto nextState
		case 62:
			state = 163
			goto nextState
		case 63:
			state = 21
			goto nextState
		case 91:
			state = 94
			goto nextState
		case 92:
			state = 35
			goto nextState
		case 93:
			state = 95
			goto nextState
		case 94:
			state = 130
			goto nextState
		case 96:
			state = 190
			goto nextState
		case 123:
			state = 84
			goto nextState
		case 124:
			state = 135
			goto nextState
		case 125:
			state = 87
			goto nextState
		}
		if ((97 <= lookahead) && (lookahead <= 122)) {
			state = 195
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 5
			goto nextState
		}
		if (((lookahead > 35) && ((lookahead < 37) || (64 < lookahead))) && ((lookahead < 96) || (126 < lookahead))) {
			state = 207
			goto nextState
		}
		return result
	case 5:
		switch lookahead {
		case 33:
			state = 89
			goto nextState
		case 37:
			state = 148
			goto nextState
		case 38:
			state = 129
			goto nextState
		case 40:
			state = 90
			goto nextState
		case 41:
			state = 92
			goto nextState
		case 42:
			state = 80
			goto nextState
		case 43:
			state = 139
			goto nextState
		case 44:
			state = 86
			goto nextState
		case 45:
			state = 143
			goto nextState
		case 46:
			state = 96
			goto nextState
		case 47:
			state = 146
			goto nextState
		case 58:
			state = 93
			goto nextState
		case 59:
			state = 91
			goto nextState
		case 60:
			state = 154
			goto nextState
		case 61:
			state = 28
			goto nextState
		case 62:
			state = 163
			goto nextState
		case 63:
			state = 21
			goto nextState
		case 91:
			state = 94
			goto nextState
		case 92:
			state = 35
			goto nextState
		case 93:
			state = 95
			goto nextState
		case 94:
			state = 130
			goto nextState
		case 96:
			state = 190
			goto nextState
		case 123:
			state = 84
			goto nextState
		case 124:
			state = 135
			goto nextState
		case 125:
			state = 87
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 5
			goto nextState
		}
		if (((lookahead > 35) && ((lookahead < 37) || (64 < lookahead))) && ((lookahead < 123) || (126 < lookahead))) {
			state = 207
			goto nextState
		}
		return result
	case 6:
		if (lookahead == 33) {
			state = 77
			goto nextState
		}
		if (lookahead == 92) {
			state = 34
			goto nextState
		}
		if ts.SetContains(characterSets[1], lookahead) {
			state = 208
			goto nextState
		}
		return result
	case 7:
		switch lookahead {
		case 33:
			state = 88
			goto nextState
		case 34:
			state = 169
			goto nextState
		case 35:
			state = 31
			goto nextState
		case 38:
			state = 127
			goto nextState
		case 39:
			state = 170
			goto nextState
		case 40:
			state = 90
			goto nextState
		case 41:
			state = 92
			goto nextState
		case 42:
			state = 78
			goto nextState
		case 43:
			state = 139
			goto nextState
		case 44:
			state = 86
			goto nextState
		case 45:
			state = 143
			goto nextState
		case 46:
			state = 97
			goto nextState
		case 47:
			state = 146
			goto nextState
		case 48:
			state = 197
			goto nextState
		case 58:
			state = 93
			goto nextState
		case 59:
			state = 91
			goto nextState
		case 60:
			state = 152
			goto nextState
		case 61:
			state = 83
			goto nextState
		case 62:
			state = 161
			goto nextState
		case 63:
			state = 211
			goto nextState
		case 64:
			state = 209
			goto nextState
		case 91:
			state = 94
			goto nextState
		case 92:
			state = 35
			goto nextState
		case 93:
			state = 95
			goto nextState
		case 96:
			state = 190
			goto nextState
		case 123:
			state = 84
			goto nextState
		case 124:
			state = 137
			goto nextState
		case 125:
			state = 87
			goto nextState
		case 126:
			state = 166
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 198
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 7
			goto nextState
		}
		if (((lookahead > 35) && ((lookahead < 37) || (64 < lookahead))) && ((lookahead < 91) || (94 < lookahead))) {
			state = 207
			goto nextState
		}
		return result
	case 8:
		switch lookahead {
		case 33:
			state = 88
			goto nextState
		case 34:
			state = 169
			goto nextState
		case 35:
			state = 31
			goto nextState
		case 38:
			state = 127
			goto nextState
		case 39:
			state = 170
			goto nextState
		case 40:
			state = 90
			goto nextState
		case 41:
			state = 92
			goto nextState
		case 42:
			state = 78
			goto nextState
		case 43:
			state = 139
			goto nextState
		case 44:
			state = 86
			goto nextState
		case 45:
			state = 143
			goto nextState
		case 46:
			state = 97
			goto nextState
		case 47:
			state = 146
			goto nextState
		case 48:
			state = 197
			goto nextState
		case 60:
			state = 152
			goto nextState
		case 63:
			state = 210
			goto nextState
		case 64:
			state = 209
			goto nextState
		case 91:
			state = 94
			goto nextState
		case 92:
			state = 35
			goto nextState
		case 93:
			state = 95
			goto nextState
		case 96:
			state = 190
			goto nextState
		case 123:
			state = 85
			goto nextState
		case 124:
			state = 132
			goto nextState
		case 126:
			state = 166
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 198
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 8
			goto nextState
		}
		if ((((lookahead > 35) && ((lookahead < 37) || (64 < lookahead))) && ((lookahead < 91) || (94 < lookahead))) && ((lookahead < 123) || (126 < lookahead))) {
			state = 207
			goto nextState
		}
		return result
	case 9:
		switch lookahead {
		case 34:
			state = 169
			goto nextState
		case 35:
			state = 31
			goto nextState
		case 38:
			state = 127
			goto nextState
		case 39:
			state = 170
			goto nextState
		case 40:
			state = 90
			goto nextState
		case 42:
			state = 78
			goto nextState
		case 43:
			state = 138
			goto nextState
		case 44:
			state = 86
			goto nextState
		case 45:
			state = 142
			goto nextState
		case 46:
			state = 20
			goto nextState
		case 47:
			state = 17
			goto nextState
		case 48:
			state = 197
			goto nextState
		case 59:
			state = 91
			goto nextState
		case 60:
			state = 152
			goto nextState
		case 62:
			state = 161
			goto nextState
		case 63:
			state = 210
			goto nextState
		case 64:
			state = 209
			goto nextState
		case 91:
			state = 94
			goto nextState
		case 92:
			state = 35
			goto nextState
		case 93:
			state = 95
			goto nextState
		case 96:
			state = 190
			goto nextState
		case 123:
			state = 85
			goto nextState
		case 124:
			state = 137
			goto nextState
		case 125:
			state = 87
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 198
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 9
			goto nextState
		}
		if ((((lookahead > 35) && ((lookahead < 37) || (64 < lookahead))) && ((lookahead < 91) || (94 < lookahead))) && ((lookahead < 123) || (126 < lookahead))) {
			state = 207
			goto nextState
		}
		return result
	case 10:
		switch lookahead {
		case 34:
			state = 169
			goto nextState
		case 35:
			state = 31
			goto nextState
		case 39:
			state = 170
			goto nextState
		case 40:
			state = 90
			goto nextState
		case 42:
			state = 78
			goto nextState
		case 43:
			state = 138
			goto nextState
		case 44:
			state = 86
			goto nextState
		case 45:
			state = 142
			goto nextState
		case 46:
			state = 20
			goto nextState
		case 47:
			state = 17
			goto nextState
		case 48:
			state = 197
			goto nextState
		case 59:
			state = 91
			goto nextState
		case 60:
			state = 152
			goto nextState
		case 64:
			state = 209
			goto nextState
		case 91:
			state = 94
			goto nextState
		case 92:
			state = 35
			goto nextState
		case 123:
			state = 84
			goto nextState
		case 124:
			state = 45
			goto nextState
		case 125:
			state = 87
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 198
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 10
			goto nextState
		}
		if (((((lookahead > 35) && ((lookahead < 37) || (64 < lookahead))) && ((lookahead < 91) || (94 < lookahead))) && (lookahead != 96)) && ((lookahead < 123) || (126 < lookahead))) {
			state = 207
			goto nextState
		}
		return result
	case 11:
		if (lookahead == 34) {
			state = 169
			goto nextState
		}
		if (lookahead == 47) {
			state = 17
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 11
			goto nextState
		}
		return result
	case 12:
		if (lookahead == 34) {
			state = 169
			goto nextState
		}
		if (lookahead == 47) {
			state = 171
			goto nextState
		}
		if (lookahead == 92) {
			state = 36
			goto nextState
		}
		if ((lookahead == 10) || (lookahead == 13)) {
			skip = true
			state = 11
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 174
			goto nextState
		}
		if (lookahead != 0) {
			state = 176
			goto nextState
		}
		return result
	case 13:
		switch lookahead {
		case 36:
			state = 37
			goto nextState
		case 43:
			state = 29
			goto nextState
		case 45:
			state = 30
			goto nextState
		case 47:
			state = 17
			goto nextState
		case 58:
			state = 93
			goto nextState
		case 63:
			state = 27
			goto nextState
		case 92:
			state = 36
			goto nextState
		case 96:
			state = 190
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 14
			goto nextState
		}
		return result
	case 14:
		if (lookahead == 36) {
			state = 37
			goto nextState
		}
		if (lookahead == 43) {
			state = 29
			goto nextState
		}
		if (lookahead == 45) {
			state = 30
			goto nextState
		}
		if (lookahead == 47) {
			state = 17
			goto nextState
		}
		if (lookahead == 58) {
			state = 93
			goto nextState
		}
		if (lookahead == 63) {
			state = 27
			goto nextState
		}
		if (lookahead == 96) {
			state = 190
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 14
			goto nextState
		}
		return result
	case 15:
		if (lookahead == 39) {
			state = 170
			goto nextState
		}
		if (lookahead == 47) {
			state = 17
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 15
			goto nextState
		}
		return result
	case 16:
		if (lookahead == 39) {
			state = 170
			goto nextState
		}
		if (lookahead == 47) {
			state = 177
			goto nextState
		}
		if (lookahead == 92) {
			state = 36
			goto nextState
		}
		if ((lookahead == 10) || (lookahead == 13)) {
			skip = true
			state = 15
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 180
			goto nextState
		}
		if (lookahead != 0) {
			state = 182
			goto nextState
		}
		return result
	case 17:
		if (lookahead == 42) {
			state = 19
			goto nextState
		}
		if (lookahead == 47) {
			state = 189
			goto nextState
		}
		return result
	case 18:
		if (lookahead == 42) {
			state = 18
			goto nextState
		}
		if (lookahead == 47) {
			state = 188
			goto nextState
		}
		if (lookahead != 0) {
			state = 19
			goto nextState
		}
		return result
	case 19:
		if (lookahead == 42) {
			state = 18
			goto nextState
		}
		if (lookahead != 0) {
			state = 19
			goto nextState
		}
		return result
	case 20:
		if (lookahead == 46) {
			state = 22
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 203
			goto nextState
		}
		return result
	case 21:
		if (lookahead == 46) {
			state = 100
			goto nextState
		}
		if (lookahead == 63) {
			state = 164
			goto nextState
		}
		return result
	case 22:
		if (lookahead == 46) {
			state = 116
			goto nextState
		}
		return result
	case 23:
		if (lookahead == 47) {
			state = 192
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 24
			goto nextState
		}
		return result
	case 24:
		if (lookahead == 47) {
			state = 17
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 24
			goto nextState
		}
		return result
	case 25:
		if (lookahead == 58) {
			state = 215
			goto nextState
		}
		return result
	case 26:
		if (lookahead == 58) {
			state = 214
			goto nextState
		}
		return result
	case 27:
		if (lookahead == 58) {
			state = 216
			goto nextState
		}
		return result
	case 28:
		if (lookahead == 61) {
			state = 156
			goto nextState
		}
		return result
	case 29:
		if (lookahead == 63) {
			state = 25
			goto nextState
		}
		return result
	case 30:
		if (lookahead == 63) {
			state = 26
			goto nextState
		}
		return result
	case 31:
		if (lookahead == 92) {
			state = 34
			goto nextState
		}
		if ts.SetContains(characterSets[1], lookahead) {
			state = 208
			goto nextState
		}
		return result
	case 32:
		if (lookahead == 92) {
			state = 71
			goto nextState
		}
		if (lookahead == 93) {
			state = 194
			goto nextState
		}
		if ((lookahead != 0) && (lookahead != 10)) {
			state = 32
			goto nextState
		}
		return result
	case 33:
		if (lookahead == 117) {
			state = 38
			goto nextState
		}
		if (lookahead == 120) {
			state = 63
			goto nextState
		}
		if ((lookahead == 13) || (lookahead == 63)) {
			state = 185
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 55)) {
			state = 187
			goto nextState
		}
		if (lookahead != 0) {
			state = 183
			goto nextState
		}
		return result
	case 34:
		if (lookahead == 117) {
			state = 39
			goto nextState
		}
		return result
	case 35:
		if (lookahead == 117) {
			state = 40
			goto nextState
		}
		return result
	case 36:
		if (lookahead == 117) {
			state = 41
			goto nextState
		}
		if (lookahead == 120) {
			state = 63
			goto nextState
		}
		if ((lookahead == 13) || (lookahead == 63)) {
			state = 185
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 55)) {
			state = 187
			goto nextState
		}
		if (lookahead != 0) {
			state = 183
			goto nextState
		}
		return result
	case 37:
		if (lookahead == 123) {
			state = 191
			goto nextState
		}
		return result
	case 38:
		if (lookahead == 123) {
			state = 58
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 68
			goto nextState
		}
		return result
	case 39:
		if (lookahead == 123) {
			state = 61
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 69
			goto nextState
		}
		return result
	case 40:
		if (lookahead == 123) {
			state = 62
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 70
			goto nextState
		}
		return result
	case 41:
		if (lookahead == 123) {
			state = 64
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 60
			goto nextState
		}
		return result
	case 42:
		if (lookahead == 125) {
			state = 207
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 42
			goto nextState
		}
		return result
	case 43:
		if (lookahead == 125) {
			state = 208
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 43
			goto nextState
		}
		return result
	case 44:
		if (lookahead == 125) {
			state = 183
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 44
			goto nextState
		}
		return result
	case 45:
		if (lookahead == 125) {
			state = 218
			goto nextState
		}
		return result
	case 46:
		if (lookahead == 125) {
			state = 184
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 46
			goto nextState
		}
		return result
	case 47:
		if ((lookahead == 43) || (lookahead == 45)) {
			state = 53
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 204
			goto nextState
		}
		return result
	case 48:
		if ((lookahead == 48) || (lookahead == 49)) {
			state = 200
			goto nextState
		}
		return result
	case 49:
		if ((48 <= lookahead) && (lookahead <= 55)) {
			state = 201
			goto nextState
		}
		return result
	case 50:
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 198
			goto nextState
		}
		return result
	case 51:
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 203
			goto nextState
		}
		return result
	case 52:
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 199
			goto nextState
		}
		return result
	case 53:
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 204
			goto nextState
		}
		return result
	case 54:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 207
			goto nextState
		}
		return result
	case 55:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 208
			goto nextState
		}
		return result
	case 56:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 183
			goto nextState
		}
		return result
	case 57:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 202
			goto nextState
		}
		return result
	case 58:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 46
			goto nextState
		}
		return result
	case 59:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 184
			goto nextState
		}
		return result
	case 60:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 63
			goto nextState
		}
		return result
	case 61:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 43
			goto nextState
		}
		return result
	case 62:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 42
			goto nextState
		}
		return result
	case 63:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 56
			goto nextState
		}
		return result
	case 64:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 44
			goto nextState
		}
		return result
	case 65:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 59
			goto nextState
		}
		return result
	case 66:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 55
			goto nextState
		}
		return result
	case 67:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 54
			goto nextState
		}
		return result
	case 68:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 65
			goto nextState
		}
		return result
	case 69:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 66
			goto nextState
		}
		return result
	case 70:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 67
			goto nextState
		}
		return result
	case 71:
		if ((lookahead != 0) && (lookahead != 10)) {
			state = 32
			goto nextState
		}
		return result
	case 72:
		if ((lookahead != 0) && (lookahead != 10)) {
			state = 194
			goto nextState
		}
		return result
	case 73:
		if eof {
			state = 76
			goto nextState
		}
		switch lookahead {
		case 33:
			state = 89
			goto nextState
		case 34:
			state = 169
			goto nextState
		case 35:
			state = 6
			goto nextState
		case 36:
			state = 206
			goto nextState
		case 37:
			state = 149
			goto nextState
		case 38:
			state = 128
			goto nextState
		case 39:
			state = 170
			goto nextState
		case 40:
			state = 90
			goto nextState
		case 41:
			state = 92
			goto nextState
		case 42:
			state = 79
			goto nextState
		case 43:
			state = 141
			goto nextState
		case 44:
			state = 86
			goto nextState
		case 45:
			state = 145
			goto nextState
		case 46:
			state = 97
			goto nextState
		case 47:
			state = 147
			goto nextState
		case 48:
			state = 197
			goto nextState
		case 58:
			state = 93
			goto nextState
		case 59:
			state = 91
			goto nextState
		case 60:
			state = 153
			goto nextState
		case 61:
			state = 82
			goto nextState
		case 62:
			state = 162
			goto nextState
		case 63:
			state = 212
			goto nextState
		case 64:
			state = 209
			goto nextState
		case 91:
			state = 94
			goto nextState
		case 92:
			state = 35
			goto nextState
		case 93:
			state = 95
			goto nextState
		case 94:
			state = 131
			goto nextState
		case 96:
			state = 190
			goto nextState
		case 123:
			state = 85
			goto nextState
		case 124:
			state = 134
			goto nextState
		case 125:
			state = 87
			goto nextState
		case 126:
			state = 166
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 198
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 73
			goto nextState
		}
		if (lookahead > 64) {
			state = 207
			goto nextState
		}
		return result
	case 74:
		if eof {
			state = 76
			goto nextState
		}
		switch lookahead {
		case 33:
			state = 89
			goto nextState
		case 34:
			state = 169
			goto nextState
		case 35:
			state = 31
			goto nextState
		case 37:
			state = 148
			goto nextState
		case 38:
			state = 129
			goto nextState
		case 39:
			state = 170
			goto nextState
		case 40:
			state = 90
			goto nextState
		case 41:
			state = 92
			goto nextState
		case 42:
			state = 80
			goto nextState
		case 43:
			state = 139
			goto nextState
		case 44:
			state = 86
			goto nextState
		case 45:
			state = 143
			goto nextState
		case 46:
			state = 98
			goto nextState
		case 47:
			state = 146
			goto nextState
		case 48:
			state = 197
			goto nextState
		case 58:
			state = 93
			goto nextState
		case 59:
			state = 91
			goto nextState
		case 60:
			state = 154
			goto nextState
		case 61:
			state = 81
			goto nextState
		case 62:
			state = 163
			goto nextState
		case 63:
			state = 213
			goto nextState
		case 64:
			state = 209
			goto nextState
		case 91:
			state = 94
			goto nextState
		case 92:
			state = 35
			goto nextState
		case 93:
			state = 95
			goto nextState
		case 94:
			state = 130
			goto nextState
		case 96:
			state = 190
			goto nextState
		case 123:
			state = 84
			goto nextState
		case 124:
			state = 136
			goto nextState
		case 125:
			state = 87
			goto nextState
		case 126:
			state = 166
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 198
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 74
			goto nextState
		}
		if (lookahead > 35) {
			state = 207
			goto nextState
		}
		return result
	case 75:
		if eof {
			state = 76
			goto nextState
		}
		switch lookahead {
		case 33:
			state = 88
			goto nextState
		case 34:
			state = 169
			goto nextState
		case 35:
			state = 6
			goto nextState
		case 38:
			state = 127
			goto nextState
		case 39:
			state = 170
			goto nextState
		case 40:
			state = 90
			goto nextState
		case 41:
			state = 92
			goto nextState
		case 42:
			state = 78
			goto nextState
		case 43:
			state = 139
			goto nextState
		case 44:
			state = 86
			goto nextState
		case 45:
			state = 143
			goto nextState
		case 46:
			state = 97
			goto nextState
		case 47:
			state = 146
			goto nextState
		case 48:
			state = 197
			goto nextState
		case 58:
			state = 93
			goto nextState
		case 59:
			state = 91
			goto nextState
		case 60:
			state = 152
			goto nextState
		case 61:
			state = 83
			goto nextState
		case 62:
			state = 161
			goto nextState
		case 63:
			state = 210
			goto nextState
		case 64:
			state = 209
			goto nextState
		case 91:
			state = 94
			goto nextState
		case 92:
			state = 35
			goto nextState
		case 93:
			state = 95
			goto nextState
		case 96:
			state = 190
			goto nextState
		case 123:
			state = 84
			goto nextState
		case 124:
			state = 137
			goto nextState
		case 125:
			state = 87
			goto nextState
		case 126:
			state = 166
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 198
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 75
			goto nextState
		}
		if (((lookahead > 35) && ((lookahead < 37) || (64 < lookahead))) && ((lookahead < 91) || (94 < lookahead))) {
			state = 207
			goto nextState
		}
		return result
	case 76:
		result = true
		lexer.ResultSymbol = 0
		lexer.MarkEnd()
		return result
	case 77:
		result = true
		lexer.ResultSymbol = 2
		lexer.MarkEnd()
		if ((lookahead != 0) && (lookahead != 10)) {
			state = 77
			goto nextState
		}
		return result
	case 78:
		result = true
		lexer.ResultSymbol = 4
		lexer.MarkEnd()
		return result
	case 79:
		result = true
		lexer.ResultSymbol = 4
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 151
			goto nextState
		}
		if (lookahead == 61) {
			state = 103
			goto nextState
		}
		return result
	case 80:
		result = true
		lexer.ResultSymbol = 4
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 150
			goto nextState
		}
		return result
	case 81:
		result = true
		lexer.ResultSymbol = 7
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 156
			goto nextState
		}
		return result
	case 82:
		result = true
		lexer.ResultSymbol = 7
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 156
			goto nextState
		}
		if (lookahead == 62) {
			state = 99
			goto nextState
		}
		return result
	case 83:
		result = true
		lexer.ResultSymbol = 7
		lexer.MarkEnd()
		if (lookahead == 62) {
			state = 99
			goto nextState
		}
		return result
	case 84:
		result = true
		lexer.ResultSymbol = 10
		lexer.MarkEnd()
		return result
	case 85:
		result = true
		lexer.ResultSymbol = 10
		lexer.MarkEnd()
		if (lookahead == 124) {
			state = 217
			goto nextState
		}
		return result
	case 86:
		result = true
		lexer.ResultSymbol = 11
		lexer.MarkEnd()
		return result
	case 87:
		result = true
		lexer.ResultSymbol = 12
		lexer.MarkEnd()
		return result
	case 88:
		result = true
		lexer.ResultSymbol = 21
		lexer.MarkEnd()
		return result
	case 89:
		result = true
		lexer.ResultSymbol = 21
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 158
			goto nextState
		}
		return result
	case 90:
		result = true
		lexer.ResultSymbol = 26
		lexer.MarkEnd()
		return result
	case 91:
		result = true
		lexer.ResultSymbol = 27
		lexer.MarkEnd()
		return result
	case 92:
		result = true
		lexer.ResultSymbol = 28
		lexer.MarkEnd()
		return result
	case 93:
		result = true
		lexer.ResultSymbol = 40
		lexer.MarkEnd()
		return result
	case 94:
		result = true
		lexer.ResultSymbol = 45
		lexer.MarkEnd()
		return result
	case 95:
		result = true
		lexer.ResultSymbol = 46
		lexer.MarkEnd()
		return result
	case 96:
		result = true
		lexer.ResultSymbol = 47
		lexer.MarkEnd()
		return result
	case 97:
		result = true
		lexer.ResultSymbol = 47
		lexer.MarkEnd()
		if (lookahead == 46) {
			state = 22
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 203
			goto nextState
		}
		return result
	case 98:
		result = true
		lexer.ResultSymbol = 47
		lexer.MarkEnd()
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 203
			goto nextState
		}
		return result
	case 99:
		result = true
		lexer.ResultSymbol = 51
		lexer.MarkEnd()
		return result
	case 100:
		result = true
		lexer.ResultSymbol = 52
		lexer.MarkEnd()
		return result
	case 101:
		result = true
		lexer.ResultSymbol = 55
		lexer.MarkEnd()
		return result
	case 102:
		result = true
		lexer.ResultSymbol = 56
		lexer.MarkEnd()
		return result
	case 103:
		result = true
		lexer.ResultSymbol = 57
		lexer.MarkEnd()
		return result
	case 104:
		result = true
		lexer.ResultSymbol = 58
		lexer.MarkEnd()
		return result
	case 105:
		result = true
		lexer.ResultSymbol = 59
		lexer.MarkEnd()
		return result
	case 106:
		result = true
		lexer.ResultSymbol = 60
		lexer.MarkEnd()
		return result
	case 107:
		result = true
		lexer.ResultSymbol = 61
		lexer.MarkEnd()
		return result
	case 108:
		result = true
		lexer.ResultSymbol = 62
		lexer.MarkEnd()
		return result
	case 109:
		result = true
		lexer.ResultSymbol = 63
		lexer.MarkEnd()
		return result
	case 110:
		result = true
		lexer.ResultSymbol = 64
		lexer.MarkEnd()
		return result
	case 111:
		result = true
		lexer.ResultSymbol = 65
		lexer.MarkEnd()
		return result
	case 112:
		result = true
		lexer.ResultSymbol = 66
		lexer.MarkEnd()
		return result
	case 113:
		result = true
		lexer.ResultSymbol = 67
		lexer.MarkEnd()
		return result
	case 114:
		result = true
		lexer.ResultSymbol = 68
		lexer.MarkEnd()
		return result
	case 115:
		result = true
		lexer.ResultSymbol = 69
		lexer.MarkEnd()
		return result
	case 116:
		result = true
		lexer.ResultSymbol = 70
		lexer.MarkEnd()
		return result
	case 117:
		result = true
		lexer.ResultSymbol = 71
		lexer.MarkEnd()
		return result
	case 118:
		result = true
		lexer.ResultSymbol = 71
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 113
			goto nextState
		}
		return result
	case 119:
		result = true
		lexer.ResultSymbol = 72
		lexer.MarkEnd()
		return result
	case 120:
		result = true
		lexer.ResultSymbol = 72
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 114
			goto nextState
		}
		return result
	case 121:
		result = true
		lexer.ResultSymbol = 73
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 109
			goto nextState
		}
		if (lookahead == 62) {
			state = 124
			goto nextState
		}
		return result
	case 122:
		result = true
		lexer.ResultSymbol = 73
		lexer.MarkEnd()
		if (lookahead == 62) {
			state = 123
			goto nextState
		}
		return result
	case 123:
		result = true
		lexer.ResultSymbol = 74
		lexer.MarkEnd()
		return result
	case 124:
		result = true
		lexer.ResultSymbol = 74
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 110
			goto nextState
		}
		return result
	case 125:
		result = true
		lexer.ResultSymbol = 75
		lexer.MarkEnd()
		return result
	case 126:
		result = true
		lexer.ResultSymbol = 75
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 111
			goto nextState
		}
		return result
	case 127:
		result = true
		lexer.ResultSymbol = 76
		lexer.MarkEnd()
		return result
	case 128:
		result = true
		lexer.ResultSymbol = 76
		lexer.MarkEnd()
		if (lookahead == 38) {
			state = 118
			goto nextState
		}
		if (lookahead == 61) {
			state = 107
			goto nextState
		}
		return result
	case 129:
		result = true
		lexer.ResultSymbol = 76
		lexer.MarkEnd()
		if (lookahead == 38) {
			state = 117
			goto nextState
		}
		return result
	case 130:
		result = true
		lexer.ResultSymbol = 77
		lexer.MarkEnd()
		return result
	case 131:
		result = true
		lexer.ResultSymbol = 77
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 106
			goto nextState
		}
		return result
	case 132:
		result = true
		lexer.ResultSymbol = 78
		lexer.MarkEnd()
		return result
	case 133:
		result = true
		lexer.ResultSymbol = 78
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 108
			goto nextState
		}
		if (lookahead == 124) {
			state = 120
			goto nextState
		}
		return result
	case 134:
		result = true
		lexer.ResultSymbol = 78
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 108
			goto nextState
		}
		if (lookahead == 124) {
			state = 120
			goto nextState
		}
		if (lookahead == 125) {
			state = 218
			goto nextState
		}
		return result
	case 135:
		result = true
		lexer.ResultSymbol = 78
		lexer.MarkEnd()
		if (lookahead == 124) {
			state = 119
			goto nextState
		}
		return result
	case 136:
		result = true
		lexer.ResultSymbol = 78
		lexer.MarkEnd()
		if (lookahead == 124) {
			state = 119
			goto nextState
		}
		if (lookahead == 125) {
			state = 218
			goto nextState
		}
		return result
	case 137:
		result = true
		lexer.ResultSymbol = 78
		lexer.MarkEnd()
		if (lookahead == 125) {
			state = 218
			goto nextState
		}
		return result
	case 138:
		result = true
		lexer.ResultSymbol = 79
		lexer.MarkEnd()
		return result
	case 139:
		result = true
		lexer.ResultSymbol = 79
		lexer.MarkEnd()
		if (lookahead == 43) {
			state = 167
			goto nextState
		}
		return result
	case 140:
		result = true
		lexer.ResultSymbol = 79
		lexer.MarkEnd()
		if (lookahead == 43) {
			state = 167
			goto nextState
		}
		if (lookahead == 61) {
			state = 101
			goto nextState
		}
		return result
	case 141:
		result = true
		lexer.ResultSymbol = 79
		lexer.MarkEnd()
		if (lookahead == 43) {
			state = 167
			goto nextState
		}
		if (lookahead == 61) {
			state = 101
			goto nextState
		}
		if (lookahead == 63) {
			state = 25
			goto nextState
		}
		return result
	case 142:
		result = true
		lexer.ResultSymbol = 80
		lexer.MarkEnd()
		return result
	case 143:
		result = true
		lexer.ResultSymbol = 80
		lexer.MarkEnd()
		if (lookahead == 45) {
			state = 168
			goto nextState
		}
		return result
	case 144:
		result = true
		lexer.ResultSymbol = 80
		lexer.MarkEnd()
		if (lookahead == 45) {
			state = 168
			goto nextState
		}
		if (lookahead == 61) {
			state = 102
			goto nextState
		}
		return result
	case 145:
		result = true
		lexer.ResultSymbol = 80
		lexer.MarkEnd()
		if (lookahead == 45) {
			state = 168
			goto nextState
		}
		if (lookahead == 61) {
			state = 102
			goto nextState
		}
		if (lookahead == 63) {
			state = 26
			goto nextState
		}
		return result
	case 146:
		result = true
		lexer.ResultSymbol = 81
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 19
			goto nextState
		}
		if (lookahead == 47) {
			state = 189
			goto nextState
		}
		return result
	case 147:
		result = true
		lexer.ResultSymbol = 81
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 19
			goto nextState
		}
		if (lookahead == 47) {
			state = 189
			goto nextState
		}
		if (lookahead == 61) {
			state = 104
			goto nextState
		}
		return result
	case 148:
		result = true
		lexer.ResultSymbol = 82
		lexer.MarkEnd()
		return result
	case 149:
		result = true
		lexer.ResultSymbol = 82
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 105
			goto nextState
		}
		return result
	case 150:
		result = true
		lexer.ResultSymbol = 83
		lexer.MarkEnd()
		return result
	case 151:
		result = true
		lexer.ResultSymbol = 83
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 112
			goto nextState
		}
		return result
	case 152:
		result = true
		lexer.ResultSymbol = 84
		lexer.MarkEnd()
		return result
	case 153:
		result = true
		lexer.ResultSymbol = 84
		lexer.MarkEnd()
		if (lookahead == 60) {
			state = 126
			goto nextState
		}
		if (lookahead == 61) {
			state = 155
			goto nextState
		}
		return result
	case 154:
		result = true
		lexer.ResultSymbol = 84
		lexer.MarkEnd()
		if (lookahead == 60) {
			state = 125
			goto nextState
		}
		if (lookahead == 61) {
			state = 155
			goto nextState
		}
		return result
	case 155:
		result = true
		lexer.ResultSymbol = 85
		lexer.MarkEnd()
		return result
	case 156:
		result = true
		lexer.ResultSymbol = 86
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 157
			goto nextState
		}
		return result
	case 157:
		result = true
		lexer.ResultSymbol = 87
		lexer.MarkEnd()
		return result
	case 158:
		result = true
		lexer.ResultSymbol = 88
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 159
			goto nextState
		}
		return result
	case 159:
		result = true
		lexer.ResultSymbol = 89
		lexer.MarkEnd()
		return result
	case 160:
		result = true
		lexer.ResultSymbol = 90
		lexer.MarkEnd()
		return result
	case 161:
		result = true
		lexer.ResultSymbol = 91
		lexer.MarkEnd()
		return result
	case 162:
		result = true
		lexer.ResultSymbol = 91
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 160
			goto nextState
		}
		if (lookahead == 62) {
			state = 121
			goto nextState
		}
		return result
	case 163:
		result = true
		lexer.ResultSymbol = 91
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 160
			goto nextState
		}
		if (lookahead == 62) {
			state = 122
			goto nextState
		}
		return result
	case 164:
		result = true
		lexer.ResultSymbol = 92
		lexer.MarkEnd()
		return result
	case 165:
		result = true
		lexer.ResultSymbol = 92
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 115
			goto nextState
		}
		return result
	case 166:
		result = true
		lexer.ResultSymbol = 94
		lexer.MarkEnd()
		return result
	case 167:
		result = true
		lexer.ResultSymbol = 97
		lexer.MarkEnd()
		return result
	case 168:
		result = true
		lexer.ResultSymbol = 98
		lexer.MarkEnd()
		return result
	case 169:
		result = true
		lexer.ResultSymbol = 99
		lexer.MarkEnd()
		return result
	case 170:
		result = true
		lexer.ResultSymbol = 100
		lexer.MarkEnd()
		return result
	case 171:
		result = true
		lexer.ResultSymbol = 101
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 173
			goto nextState
		}
		if (lookahead == 47) {
			state = 175
			goto nextState
		}
		if (((((lookahead != 0) && (lookahead != 10)) && (lookahead != 13)) && (lookahead != 34)) && (lookahead != 92)) {
			state = 176
			goto nextState
		}
		return result
	case 172:
		result = true
		lexer.ResultSymbol = 101
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 172
			goto nextState
		}
		if (lookahead == 47) {
			state = 176
			goto nextState
		}
		if (((((lookahead != 0) && (lookahead != 10)) && (lookahead != 13)) && (lookahead != 34)) && (lookahead != 92)) {
			state = 173
			goto nextState
		}
		return result
	case 173:
		result = true
		lexer.ResultSymbol = 101
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 172
			goto nextState
		}
		if (((((lookahead != 0) && (lookahead != 10)) && (lookahead != 13)) && (lookahead != 34)) && (lookahead != 92)) {
			state = 173
			goto nextState
		}
		return result
	case 174:
		result = true
		lexer.ResultSymbol = 101
		lexer.MarkEnd()
		if (lookahead == 47) {
			state = 171
			goto nextState
		}
		if ((ts.SetContains(characterSets[0], lookahead) && (lookahead != 10)) && (lookahead != 13)) {
			state = 174
			goto nextState
		}
		if ((((lookahead != 0) && ((lookahead < 9) || (13 < lookahead))) && (lookahead != 34)) && (lookahead != 92)) {
			state = 176
			goto nextState
		}
		return result
	case 175:
		result = true
		lexer.ResultSymbol = 101
		lexer.MarkEnd()
		if ((lookahead == 8232) || (lookahead == 8233)) {
			state = 176
			goto nextState
		}
		if (((((lookahead != 0) && (lookahead != 10)) && (lookahead != 13)) && (lookahead != 34)) && (lookahead != 92)) {
			state = 175
			goto nextState
		}
		return result
	case 176:
		result = true
		lexer.ResultSymbol = 101
		lexer.MarkEnd()
		if (((((lookahead != 0) && (lookahead != 10)) && (lookahead != 13)) && (lookahead != 34)) && (lookahead != 92)) {
			state = 176
			goto nextState
		}
		return result
	case 177:
		result = true
		lexer.ResultSymbol = 102
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 179
			goto nextState
		}
		if (lookahead == 47) {
			state = 181
			goto nextState
		}
		if (((((lookahead != 0) && (lookahead != 10)) && (lookahead != 13)) && (lookahead != 39)) && (lookahead != 92)) {
			state = 182
			goto nextState
		}
		return result
	case 178:
		result = true
		lexer.ResultSymbol = 102
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 178
			goto nextState
		}
		if (lookahead == 47) {
			state = 182
			goto nextState
		}
		if (((((lookahead != 0) && (lookahead != 10)) && (lookahead != 13)) && (lookahead != 39)) && (lookahead != 92)) {
			state = 179
			goto nextState
		}
		return result
	case 179:
		result = true
		lexer.ResultSymbol = 102
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 178
			goto nextState
		}
		if (((((lookahead != 0) && (lookahead != 10)) && (lookahead != 13)) && (lookahead != 39)) && (lookahead != 92)) {
			state = 179
			goto nextState
		}
		return result
	case 180:
		result = true
		lexer.ResultSymbol = 102
		lexer.MarkEnd()
		if (lookahead == 47) {
			state = 177
			goto nextState
		}
		if ((ts.SetContains(characterSets[0], lookahead) && (lookahead != 10)) && (lookahead != 13)) {
			state = 180
			goto nextState
		}
		if ((((lookahead != 0) && ((lookahead < 9) || (13 < lookahead))) && (lookahead != 39)) && (lookahead != 92)) {
			state = 182
			goto nextState
		}
		return result
	case 181:
		result = true
		lexer.ResultSymbol = 102
		lexer.MarkEnd()
		if ((lookahead == 8232) || (lookahead == 8233)) {
			state = 182
			goto nextState
		}
		if (((((lookahead != 0) && (lookahead != 10)) && (lookahead != 13)) && (lookahead != 39)) && (lookahead != 92)) {
			state = 181
			goto nextState
		}
		return result
	case 182:
		result = true
		lexer.ResultSymbol = 102
		lexer.MarkEnd()
		if (((((lookahead != 0) && (lookahead != 10)) && (lookahead != 13)) && (lookahead != 39)) && (lookahead != 92)) {
			state = 182
			goto nextState
		}
		return result
	case 183:
		result = true
		lexer.ResultSymbol = 103
		lexer.MarkEnd()
		return result
	case 184:
		result = true
		lexer.ResultSymbol = 103
		lexer.MarkEnd()
		if (lookahead == 92) {
			state = 35
			goto nextState
		}
		if ts.SetContains(characterSets[2], lookahead) {
			state = 207
			goto nextState
		}
		return result
	case 185:
		result = true
		lexer.ResultSymbol = 103
		lexer.MarkEnd()
		if (((lookahead == 10) || (lookahead == 8232)) || (lookahead == 8233)) {
			state = 183
			goto nextState
		}
		return result
	case 186:
		result = true
		lexer.ResultSymbol = 103
		lexer.MarkEnd()
		if ((48 <= lookahead) && (lookahead <= 55)) {
			state = 183
			goto nextState
		}
		return result
	case 187:
		result = true
		lexer.ResultSymbol = 103
		lexer.MarkEnd()
		if ((48 <= lookahead) && (lookahead <= 55)) {
			state = 186
			goto nextState
		}
		return result
	case 188:
		result = true
		lexer.ResultSymbol = 104
		lexer.MarkEnd()
		return result
	case 189:
		result = true
		lexer.ResultSymbol = 104
		lexer.MarkEnd()
		if (((((lookahead != 0) && (lookahead != 10)) && (lookahead != 13)) && (lookahead != 8232)) && (lookahead != 8233)) {
			state = 189
			goto nextState
		}
		return result
	case 190:
		result = true
		lexer.ResultSymbol = 105
		lexer.MarkEnd()
		return result
	case 191:
		result = true
		lexer.ResultSymbol = 106
		lexer.MarkEnd()
		return result
	case 192:
		result = true
		lexer.ResultSymbol = 107
		lexer.MarkEnd()
		return result
	case 193:
		result = true
		lexer.ResultSymbol = 108
		lexer.MarkEnd()
		if (lookahead == 10) {
			skip = true
			state = 24
			goto nextState
		}
		if (lookahead == 47) {
			state = 17
			goto nextState
		}
		if (lookahead == 91) {
			state = 32
			goto nextState
		}
		if (lookahead == 92) {
			state = 72
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 193
			goto nextState
		}
		if (lookahead != 0) {
			state = 194
			goto nextState
		}
		return result
	case 194:
		result = true
		lexer.ResultSymbol = 108
		lexer.MarkEnd()
		if (lookahead == 91) {
			state = 32
			goto nextState
		}
		if (lookahead == 92) {
			state = 72
			goto nextState
		}
		if (((lookahead != 0) && (lookahead != 10)) && (lookahead != 47)) {
			state = 194
			goto nextState
		}
		return result
	case 195:
		result = true
		lexer.ResultSymbol = 109
		lexer.MarkEnd()
		if (lookahead == 92) {
			state = 35
			goto nextState
		}
		if ((97 <= lookahead) && (lookahead <= 122)) {
			state = 195
			goto nextState
		}
		if ts.SetContains(characterSets[2], lookahead) {
			state = 207
			goto nextState
		}
		return result
	case 196:
		result = true
		lexer.ResultSymbol = 110
		lexer.MarkEnd()
		return result
	case 197:
		result = true
		lexer.ResultSymbol = 110
		lexer.MarkEnd()
		switch lookahead {
		case 46:
			state = 205
			goto nextState
		case 48:
			state = 199
			goto nextState
		case 95:
			state = 52
			goto nextState
		case 110:
			state = 196
			goto nextState
		case 66:
			state = 48
			goto nextState
		case 98:
			state = 48
			goto nextState
		case 69:
			state = 47
			goto nextState
		case 101:
			state = 47
			goto nextState
		case 79:
			state = 49
			goto nextState
		case 111:
			state = 49
			goto nextState
		case 88:
			state = 57
			goto nextState
		case 120:
			state = 57
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 198
			goto nextState
		}
		return result
	case 198:
		result = true
		lexer.ResultSymbol = 110
		lexer.MarkEnd()
		if (lookahead == 46) {
			state = 205
			goto nextState
		}
		if (lookahead == 95) {
			state = 50
			goto nextState
		}
		if (lookahead == 110) {
			state = 196
			goto nextState
		}
		if ((lookahead == 69) || (lookahead == 101)) {
			state = 47
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 198
			goto nextState
		}
		return result
	case 199:
		result = true
		lexer.ResultSymbol = 110
		lexer.MarkEnd()
		if (lookahead == 95) {
			state = 52
			goto nextState
		}
		if (lookahead == 110) {
			state = 196
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 199
			goto nextState
		}
		return result
	case 200:
		result = true
		lexer.ResultSymbol = 110
		lexer.MarkEnd()
		if (lookahead == 95) {
			state = 48
			goto nextState
		}
		if (lookahead == 110) {
			state = 196
			goto nextState
		}
		if ((lookahead == 48) || (lookahead == 49)) {
			state = 200
			goto nextState
		}
		return result
	case 201:
		result = true
		lexer.ResultSymbol = 110
		lexer.MarkEnd()
		if (lookahead == 95) {
			state = 49
			goto nextState
		}
		if (lookahead == 110) {
			state = 196
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 55)) {
			state = 201
			goto nextState
		}
		return result
	case 202:
		result = true
		lexer.ResultSymbol = 110
		lexer.MarkEnd()
		if (lookahead == 95) {
			state = 57
			goto nextState
		}
		if (lookahead == 110) {
			state = 196
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 202
			goto nextState
		}
		return result
	case 203:
		result = true
		lexer.ResultSymbol = 110
		lexer.MarkEnd()
		if (lookahead == 95) {
			state = 51
			goto nextState
		}
		if ((lookahead == 69) || (lookahead == 101)) {
			state = 47
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 203
			goto nextState
		}
		return result
	case 204:
		result = true
		lexer.ResultSymbol = 110
		lexer.MarkEnd()
		if (lookahead == 95) {
			state = 53
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 204
			goto nextState
		}
		return result
	case 205:
		result = true
		lexer.ResultSymbol = 110
		lexer.MarkEnd()
		if ((lookahead == 69) || (lookahead == 101)) {
			state = 47
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 203
			goto nextState
		}
		return result
	case 206:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if (lookahead == 92) {
			state = 35
			goto nextState
		}
		if (lookahead == 123) {
			state = 191
			goto nextState
		}
		if ts.SetContains(characterSets[2], lookahead) {
			state = 207
			goto nextState
		}
		return result
	case 207:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if (lookahead == 92) {
			state = 35
			goto nextState
		}
		if ts.SetContains(characterSets[2], lookahead) {
			state = 207
			goto nextState
		}
		return result
	case 208:
		result = true
		lexer.ResultSymbol = 111
		lexer.MarkEnd()
		if (lookahead == 92) {
			state = 34
			goto nextState
		}
		if ts.SetContains(characterSets[2], lookahead) {
			state = 208
			goto nextState
		}
		return result
	case 209:
		result = true
		lexer.ResultSymbol = 120
		lexer.MarkEnd()
		return result
	case 210:
		result = true
		lexer.ResultSymbol = 125
		lexer.MarkEnd()
		return result
	case 211:
		result = true
		lexer.ResultSymbol = 125
		lexer.MarkEnd()
		if (lookahead == 46) {
			state = 100
			goto nextState
		}
		return result
	case 212:
		result = true
		lexer.ResultSymbol = 125
		lexer.MarkEnd()
		if (lookahead == 46) {
			state = 100
			goto nextState
		}
		if (lookahead == 63) {
			state = 165
			goto nextState
		}
		return result
	case 213:
		result = true
		lexer.ResultSymbol = 125
		lexer.MarkEnd()
		if (lookahead == 46) {
			state = 100
			goto nextState
		}
		if (lookahead == 63) {
			state = 164
			goto nextState
		}
		return result
	case 214:
		result = true
		lexer.ResultSymbol = 147
		lexer.MarkEnd()
		return result
	case 215:
		result = true
		lexer.ResultSymbol = 148
		lexer.MarkEnd()
		return result
	case 216:
		result = true
		lexer.ResultSymbol = 149
		lexer.MarkEnd()
		return result
	case 217:
		result = true
		lexer.ResultSymbol = 157
		lexer.MarkEnd()
		return result
	case 218:
		result = true
		lexer.ResultSymbol = 158
		lexer.MarkEnd()
		return result
	default:
		return false
	}
}

func tsLexKeywords(lexer *ts.Lexer, state ts.StateID) bool {
	result := false
	skip := false
	eof := false
	var lookahead int32
	_, _ = eof, lookahead
	goto start
nextState:
	lexer.Advance(skip)
start:
	skip = false
	lookahead = lexer.Lookahead
	eof = lexer.EOF()
	switch state {
	case 0:
		switch lookahead {
		case 97:
			state = 1
			goto nextState
		case 98:
			state = 2
			goto nextState
		case 99:
			state = 3
			goto nextState
		case 100:
			state = 4
			goto nextState
		case 101:
			state = 5
			goto nextState
		case 102:
			state = 6
			goto nextState
		case 103:
			state = 7
			goto nextState
		case 105:
			state = 8
			goto nextState
		case 107:
			state = 9
			goto nextState
		case 108:
			state = 10
			goto nextState
		case 109:
			state = 11
			goto nextState
		case 110:
			state = 12
			goto nextState
		case 111:
			state = 13
			goto nextState
		case 112:
			state = 14
			goto nextState
		case 114:
			state = 15
			goto nextState
		case 115:
			state = 16
			goto nextState
		case 116:
			state = 17
			goto nextState
		case 117:
			state = 18
			goto nextState
		case 118:
			state = 19
			goto nextState
		case 119:
			state = 20
			goto nextState
		case 121:
			state = 21
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			skip = true
			state = 0
			goto nextState
		}
		return result
	case 1:
		if (lookahead == 98) {
			state = 22
			goto nextState
		}
		if (lookahead == 99) {
			state = 23
			goto nextState
		}
		if (lookahead == 110) {
			state = 24
			goto nextState
		}
		if (lookahead == 115) {
			state = 25
			goto nextState
		}
		if (lookahead == 119) {
			state = 26
			goto nextState
		}
		return result
	case 2:
		if (lookahead == 111) {
			state = 27
			goto nextState
		}
		if (lookahead == 114) {
			state = 28
			goto nextState
		}
		return result
	case 3:
		if (lookahead == 97) {
			state = 29
			goto nextState
		}
		if (lookahead == 108) {
			state = 30
			goto nextState
		}
		if (lookahead == 111) {
			state = 31
			goto nextState
		}
		return result
	case 4:
		if (lookahead == 101) {
			state = 32
			goto nextState
		}
		if (lookahead == 111) {
			state = 33
			goto nextState
		}
		return result
	case 5:
		if (lookahead == 108) {
			state = 34
			goto nextState
		}
		if (lookahead == 110) {
			state = 35
			goto nextState
		}
		if (lookahead == 120) {
			state = 36
			goto nextState
		}
		return result
	case 6:
		if (lookahead == 97) {
			state = 37
			goto nextState
		}
		if (lookahead == 105) {
			state = 38
			goto nextState
		}
		if (lookahead == 111) {
			state = 39
			goto nextState
		}
		if (lookahead == 114) {
			state = 40
			goto nextState
		}
		if (lookahead == 117) {
			state = 41
			goto nextState
		}
		return result
	case 7:
		if (lookahead == 101) {
			state = 42
			goto nextState
		}
		if (lookahead == 108) {
			state = 43
			goto nextState
		}
		return result
	case 8:
		if (lookahead == 102) {
			state = 44
			goto nextState
		}
		if (lookahead == 109) {
			state = 45
			goto nextState
		}
		if (lookahead == 110) {
			state = 46
			goto nextState
		}
		if (lookahead == 115) {
			state = 47
			goto nextState
		}
		return result
	case 9:
		if (lookahead == 101) {
			state = 48
			goto nextState
		}
		return result
	case 10:
		if (lookahead == 101) {
			state = 49
			goto nextState
		}
		return result
	case 11:
		if (lookahead == 101) {
			state = 50
			goto nextState
		}
		if (lookahead == 111) {
			state = 51
			goto nextState
		}
		return result
	case 12:
		if (lookahead == 97) {
			state = 52
			goto nextState
		}
		if (lookahead == 101) {
			state = 53
			goto nextState
		}
		if (lookahead == 117) {
			state = 54
			goto nextState
		}
		return result
	case 13:
		if (lookahead == 98) {
			state = 55
			goto nextState
		}
		if (lookahead == 102) {
			state = 56
			goto nextState
		}
		if (lookahead == 118) {
			state = 57
			goto nextState
		}
		return result
	case 14:
		if (lookahead == 114) {
			state = 58
			goto nextState
		}
		if (lookahead == 117) {
			state = 59
			goto nextState
		}
		return result
	case 15:
		if (lookahead == 101) {
			state = 60
			goto nextState
		}
		return result
	case 16:
		if (lookahead == 97) {
			state = 61
			goto nextState
		}
		if (lookahead == 101) {
			state = 62
			goto nextState
		}
		if (lookahead == 116) {
			state = 63
			goto nextState
		}
		if (lookahead == 117) {
			state = 64
			goto nextState
		}
		if (lookahead == 119) {
			state = 65
			goto nextState
		}
		if (lookahead == 121) {
			state = 66
			goto nextState
		}
		return result
	case 17:
		if (lookahead == 97) {
			state = 67
			goto nextState
		}
		if (lookahead == 104) {
			state = 68
			goto nextState
		}
		if (lookahead == 114) {
			state = 69
			goto nextState
		}
		if (lookahead == 121) {
			state = 70
			goto nextState
		}
		return result
	case 18:
		if (lookahead == 110) {
			state = 71
			goto nextState
		}
		if (lookahead == 115) {
			state = 72
			goto nextState
		}
		return result
	case 19:
		if (lookahead == 97) {
			state = 73
			goto nextState
		}
		if (lookahead == 111) {
			state = 74
			goto nextState
		}
		return result
	case 20:
		if (lookahead == 104) {
			state = 75
			goto nextState
		}
		if (lookahead == 105) {
			state = 76
			goto nextState
		}
		return result
	case 21:
		if (lookahead == 105) {
			state = 77
			goto nextState
		}
		return result
	case 22:
		if (lookahead == 115) {
			state = 78
			goto nextState
		}
		return result
	case 23:
		if (lookahead == 99) {
			state = 79
			goto nextState
		}
		return result
	case 24:
		if (lookahead == 121) {
			state = 80
			goto nextState
		}
		return result
	case 25:
		result = true
		lexer.ResultSymbol = 8
		lexer.MarkEnd()
		if (lookahead == 115) {
			state = 81
			goto nextState
		}
		if (lookahead == 121) {
			state = 82
			goto nextState
		}
		return result
	case 26:
		if (lookahead == 97) {
			state = 83
			goto nextState
		}
		return result
	case 27:
		if (lookahead == 111) {
			state = 84
			goto nextState
		}
		return result
	case 28:
		if (lookahead == 101) {
			state = 85
			goto nextState
		}
		return result
	case 29:
		if (lookahead == 115) {
			state = 86
			goto nextState
		}
		if (lookahead == 116) {
			state = 87
			goto nextState
		}
		return result
	case 30:
		if (lookahead == 97) {
			state = 88
			goto nextState
		}
		return result
	case 31:
		if (lookahead == 110) {
			state = 89
			goto nextState
		}
		return result
	case 32:
		if (lookahead == 98) {
			state = 90
			goto nextState
		}
		if (lookahead == 99) {
			state = 91
			goto nextState
		}
		if (lookahead == 102) {
			state = 92
			goto nextState
		}
		if (lookahead == 108) {
			state = 93
			goto nextState
		}
		return result
	case 33:
		result = true
		lexer.ResultSymbol = 33
		lexer.MarkEnd()
		return result
	case 34:
		if (lookahead == 115) {
			state = 94
			goto nextState
		}
		return result
	case 35:
		if (lookahead == 117) {
			state = 95
			goto nextState
		}
		return result
	case 36:
		if (lookahead == 112) {
			state = 96
			goto nextState
		}
		if (lookahead == 116) {
			state = 97
			goto nextState
		}
		return result
	case 37:
		if (lookahead == 108) {
			state = 98
			goto nextState
		}
		return result
	case 38:
		if (lookahead == 110) {
			state = 99
			goto nextState
		}
		return result
	case 39:
		if (lookahead == 114) {
			state = 100
			goto nextState
		}
		return result
	case 40:
		if (lookahead == 111) {
			state = 101
			goto nextState
		}
		return result
	case 41:
		if (lookahead == 110) {
			state = 102
			goto nextState
		}
		return result
	case 42:
		if (lookahead == 116) {
			state = 103
			goto nextState
		}
		return result
	case 43:
		if (lookahead == 111) {
			state = 104
			goto nextState
		}
		return result
	case 44:
		result = true
		lexer.ResultSymbol = 23
		lexer.MarkEnd()
		return result
	case 45:
		if (lookahead == 112) {
			state = 105
			goto nextState
		}
		return result
	case 46:
		result = true
		lexer.ResultSymbol = 30
		lexer.MarkEnd()
		if (lookahead == 102) {
			state = 106
			goto nextState
		}
		if (lookahead == 115) {
			state = 107
			goto nextState
		}
		if (lookahead == 116) {
			state = 108
			goto nextState
		}
		return result
	case 47:
		result = true
		lexer.ResultSymbol = 152
		lexer.MarkEnd()
		return result
	case 48:
		if (lookahead == 121) {
			state = 109
			goto nextState
		}
		return result
	case 49:
		if (lookahead == 116) {
			state = 110
			goto nextState
		}
		return result
	case 50:
		if (lookahead == 116) {
			state = 111
			goto nextState
		}
		return result
	case 51:
		if (lookahead == 100) {
			state = 112
			goto nextState
		}
		return result
	case 52:
		if (lookahead == 109) {
			state = 113
			goto nextState
		}
		return result
	case 53:
		if (lookahead == 118) {
			state = 114
			goto nextState
		}
		if (lookahead == 119) {
			state = 115
			goto nextState
		}
		return result
	case 54:
		if (lookahead == 108) {
			state = 116
			goto nextState
		}
		if (lookahead == 109) {
			state = 117
			goto nextState
		}
		return result
	case 55:
		if (lookahead == 106) {
			state = 118
			goto nextState
		}
		return result
	case 56:
		result = true
		lexer.ResultSymbol = 31
		lexer.MarkEnd()
		return result
	case 57:
		if (lookahead == 101) {
			state = 119
			goto nextState
		}
		return result
	case 58:
		if (lookahead == 105) {
			state = 120
			goto nextState
		}
		if (lookahead == 111) {
			state = 121
			goto nextState
		}
		return result
	case 59:
		if (lookahead == 98) {
			state = 122
			goto nextState
		}
		return result
	case 60:
		if (lookahead == 97) {
			state = 123
			goto nextState
		}
		if (lookahead == 113) {
			state = 124
			goto nextState
		}
		if (lookahead == 116) {
			state = 125
			goto nextState
		}
		return result
	case 61:
		if (lookahead == 116) {
			state = 126
			goto nextState
		}
		return result
	case 62:
		if (lookahead == 116) {
			state = 127
			goto nextState
		}
		return result
	case 63:
		if (lookahead == 97) {
			state = 128
			goto nextState
		}
		if (lookahead == 114) {
			state = 129
			goto nextState
		}
		return result
	case 64:
		if (lookahead == 112) {
			state = 130
			goto nextState
		}
		return result
	case 65:
		if (lookahead == 105) {
			state = 131
			goto nextState
		}
		return result
	case 66:
		if (lookahead == 109) {
			state = 132
			goto nextState
		}
		return result
	case 67:
		if (lookahead == 114) {
			state = 133
			goto nextState
		}
		return result
	case 68:
		if (lookahead == 105) {
			state = 134
			goto nextState
		}
		if (lookahead == 114) {
			state = 135
			goto nextState
		}
		return result
	case 69:
		if (lookahead == 117) {
			state = 136
			goto nextState
		}
		if (lookahead == 121) {
			state = 137
			goto nextState
		}
		return result
	case 70:
		if (lookahead == 112) {
			state = 138
			goto nextState
		}
		return result
	case 71:
		if (lookahead == 100) {
			state = 139
			goto nextState
		}
		if (lookahead == 105) {
			state = 140
			goto nextState
		}
		if (lookahead == 107) {
			state = 141
			goto nextState
		}
		return result
	case 72:
		if (lookahead == 105) {
			state = 142
			goto nextState
		}
		return result
	case 73:
		if (lookahead == 114) {
			state = 143
			goto nextState
		}
		return result
	case 74:
		if (lookahead == 105) {
			state = 144
			goto nextState
		}
		return result
	case 75:
		if (lookahead == 105) {
			state = 145
			goto nextState
		}
		return result
	case 76:
		if (lookahead == 116) {
			state = 146
			goto nextState
		}
		return result
	case 77:
		if (lookahead == 101) {
			state = 147
			goto nextState
		}
		return result
	case 78:
		if (lookahead == 116) {
			state = 148
			goto nextState
		}
		return result
	case 79:
		if (lookahead == 101) {
			state = 149
			goto nextState
		}
		return result
	case 80:
		result = true
		lexer.ResultSymbol = 132
		lexer.MarkEnd()
		return result
	case 81:
		if (lookahead == 101) {
			state = 150
			goto nextState
		}
		return result
	case 82:
		if (lookahead == 110) {
			state = 151
			goto nextState
		}
		return result
	case 83:
		if (lookahead == 105) {
			state = 152
			goto nextState
		}
		return result
	case 84:
		if (lookahead == 108) {
			state = 153
			goto nextState
		}
		return result
	case 85:
		if (lookahead == 97) {
			state = 154
			goto nextState
		}
		return result
	case 86:
		if (lookahead == 101) {
			state = 155
			goto nextState
		}
		return result
	case 87:
		if (lookahead == 99) {
			state = 156
			goto nextState
		}
		return result
	case 88:
		if (lookahead == 115) {
			state = 157
			goto nextState
		}
		return result
	case 89:
		if (lookahead == 115) {
			state = 158
			goto nextState
		}
		if (lookahead == 116) {
			state = 159
			goto nextState
		}
		return result
	case 90:
		if (lookahead == 117) {
			state = 160
			goto nextState
		}
		return result
	case 91:
		if (lookahead == 108) {
			state = 161
			goto nextState
		}
		return result
	case 92:
		if (lookahead == 97) {
			state = 162
			goto nextState
		}
		return result
	case 93:
		if (lookahead == 101) {
			state = 163
			goto nextState
		}
		return result
	case 94:
		if (lookahead == 101) {
			state = 164
			goto nextState
		}
		return result
	case 95:
		if (lookahead == 109) {
			state = 165
			goto nextState
		}
		return result
	case 96:
		if (lookahead == 111) {
			state = 166
			goto nextState
		}
		return result
	case 97:
		if (lookahead == 101) {
			state = 167
			goto nextState
		}
		return result
	case 98:
		if (lookahead == 115) {
			state = 168
			goto nextState
		}
		return result
	case 99:
		if (lookahead == 97) {
			state = 169
			goto nextState
		}
		return result
	case 100:
		result = true
		lexer.ResultSymbol = 25
		lexer.MarkEnd()
		return result
	case 101:
		if (lookahead == 109) {
			state = 170
			goto nextState
		}
		return result
	case 102:
		if (lookahead == 99) {
			state = 171
			goto nextState
		}
		return result
	case 103:
		result = true
		lexer.ResultSymbol = 123
		lexer.MarkEnd()
		return result
	case 104:
		if (lookahead == 98) {
			state = 172
			goto nextState
		}
		return result
	case 105:
		if (lookahead == 108) {
			state = 173
			goto nextState
		}
		if (lookahead == 111) {
			state = 174
			goto nextState
		}
		return result
	case 106:
		if (lookahead == 101) {
			state = 175
			goto nextState
		}
		return result
	case 107:
		if (lookahead == 116) {
			state = 176
			goto nextState
		}
		return result
	case 108:
		if (lookahead == 101) {
			state = 177
			goto nextState
		}
		return result
	case 109:
		if (lookahead == 111) {
			state = 178
			goto nextState
		}
		return result
	case 110:
		result = true
		lexer.ResultSymbol = 19
		lexer.MarkEnd()
		return result
	case 111:
		if (lookahead == 97) {
			state = 179
			goto nextState
		}
		return result
	case 112:
		if (lookahead == 117) {
			state = 180
			goto nextState
		}
		return result
	case 113:
		if (lookahead == 101) {
			state = 181
			goto nextState
		}
		return result
	case 114:
		if (lookahead == 101) {
			state = 182
			goto nextState
		}
		return result
	case 115:
		result = true
		lexer.ResultSymbol = 53
		lexer.MarkEnd()
		return result
	case 116:
		if (lookahead == 108) {
			state = 183
			goto nextState
		}
		return result
	case 117:
		if (lookahead == 98) {
			state = 184
			goto nextState
		}
		return result
	case 118:
		if (lookahead == 101) {
			state = 185
			goto nextState
		}
		return result
	case 119:
		if (lookahead == 114) {
			state = 186
			goto nextState
		}
		return result
	case 120:
		if (lookahead == 118) {
			state = 187
			goto nextState
		}
		return result
	case 121:
		if (lookahead == 116) {
			state = 188
			goto nextState
		}
		return result
	case 122:
		if (lookahead == 108) {
			state = 189
			goto nextState
		}
		return result
	case 123:
		if (lookahead == 100) {
			state = 190
			goto nextState
		}
		return result
	case 124:
		if (lookahead == 117) {
			state = 191
			goto nextState
		}
		return result
	case 125:
		if (lookahead == 117) {
			state = 192
			goto nextState
		}
		return result
	case 126:
		if (lookahead == 105) {
			state = 193
			goto nextState
		}
		return result
	case 127:
		result = true
		lexer.ResultSymbol = 124
		lexer.MarkEnd()
		return result
	case 128:
		if (lookahead == 116) {
			state = 194
			goto nextState
		}
		return result
	case 129:
		if (lookahead == 105) {
			state = 195
			goto nextState
		}
		return result
	case 130:
		if (lookahead == 101) {
			state = 196
			goto nextState
		}
		return result
	case 131:
		if (lookahead == 116) {
			state = 197
			goto nextState
		}
		return result
	case 132:
		if (lookahead == 98) {
			state = 198
			goto nextState
		}
		return result
	case 133:
		if (lookahead == 103) {
			state = 199
			goto nextState
		}
		return result
	case 134:
		if (lookahead == 115) {
			state = 200
			goto nextState
		}
		return result
	case 135:
		if (lookahead == 111) {
			state = 201
			goto nextState
		}
		return result
	case 136:
		if (lookahead == 101) {
			state = 202
			goto nextState
		}
		return result
	case 137:
		result = true
		lexer.ResultSymbol = 34
		lexer.MarkEnd()
		return result
	case 138:
		if (lookahead == 101) {
			state = 203
			goto nextState
		}
		return result
	case 139:
		if (lookahead == 101) {
			state = 204
			goto nextState
		}
		return result
	case 140:
		if (lookahead == 113) {
			state = 205
			goto nextState
		}
		return result
	case 141:
		if (lookahead == 110) {
			state = 206
			goto nextState
		}
		return result
	case 142:
		if (lookahead == 110) {
			state = 207
			goto nextState
		}
		return result
	case 143:
		result = true
		lexer.ResultSymbol = 18
		lexer.MarkEnd()
		return result
	case 144:
		if (lookahead == 100) {
			state = 208
			goto nextState
		}
		return result
	case 145:
		if (lookahead == 108) {
			state = 209
			goto nextState
		}
		return result
	case 146:
		if (lookahead == 104) {
			state = 210
			goto nextState
		}
		return result
	case 147:
		if (lookahead == 108) {
			state = 211
			goto nextState
		}
		return result
	case 148:
		if (lookahead == 114) {
			state = 212
			goto nextState
		}
		return result
	case 149:
		if (lookahead == 115) {
			state = 213
			goto nextState
		}
		return result
	case 150:
		if (lookahead == 114) {
			state = 214
			goto nextState
		}
		return result
	case 151:
		if (lookahead == 99) {
			state = 215
			goto nextState
		}
		return result
	case 152:
		if (lookahead == 116) {
			state = 216
			goto nextState
		}
		return result
	case 153:
		if (lookahead == 101) {
			state = 217
			goto nextState
		}
		return result
	case 154:
		if (lookahead == 107) {
			state = 218
			goto nextState
		}
		return result
	case 155:
		result = true
		lexer.ResultSymbol = 41
		lexer.MarkEnd()
		return result
	case 156:
		if (lookahead == 104) {
			state = 219
			goto nextState
		}
		return result
	case 157:
		if (lookahead == 115) {
			state = 220
			goto nextState
		}
		return result
	case 158:
		if (lookahead == 116) {
			state = 221
			goto nextState
		}
		return result
	case 159:
		if (lookahead == 105) {
			state = 222
			goto nextState
		}
		return result
	case 160:
		if (lookahead == 103) {
			state = 223
			goto nextState
		}
		return result
	case 161:
		if (lookahead == 97) {
			state = 224
			goto nextState
		}
		return result
	case 162:
		if (lookahead == 117) {
			state = 225
			goto nextState
		}
		return result
	case 163:
		if (lookahead == 116) {
			state = 226
			goto nextState
		}
		return result
	case 164:
		result = true
		lexer.ResultSymbol = 22
		lexer.MarkEnd()
		return result
	case 165:
		result = true
		lexer.ResultSymbol = 146
		lexer.MarkEnd()
		return result
	case 166:
		if (lookahead == 114) {
			state = 227
			goto nextState
		}
		return result
	case 167:
		if (lookahead == 110) {
			state = 228
			goto nextState
		}
		return result
	case 168:
		if (lookahead == 101) {
			state = 229
			goto nextState
		}
		return result
	case 169:
		if (lookahead == 108) {
			state = 230
			goto nextState
		}
		return result
	case 170:
		result = true
		lexer.ResultSymbol = 15
		lexer.MarkEnd()
		return result
	case 171:
		if (lookahead == 116) {
			state = 231
			goto nextState
		}
		return result
	case 172:
		if (lookahead == 97) {
			state = 232
			goto nextState
		}
		return result
	case 173:
		if (lookahead == 101) {
			state = 233
			goto nextState
		}
		return result
	case 174:
		if (lookahead == 114) {
			state = 234
			goto nextState
		}
		return result
	case 175:
		if (lookahead == 114) {
			state = 235
			goto nextState
		}
		return result
	case 176:
		if (lookahead == 97) {
			state = 236
			goto nextState
		}
		return result
	case 177:
		if (lookahead == 114) {
			state = 237
			goto nextState
		}
		return result
	case 178:
		if (lookahead == 102) {
			state = 238
			goto nextState
		}
		return result
	case 179:
		result = true
		lexer.ResultSymbol = 113
		lexer.MarkEnd()
		return result
	case 180:
		if (lookahead == 108) {
			state = 239
			goto nextState
		}
		return result
	case 181:
		if (lookahead == 115) {
			state = 240
			goto nextState
		}
		return result
	case 182:
		if (lookahead == 114) {
			state = 241
			goto nextState
		}
		return result
	case 183:
		result = true
		lexer.ResultSymbol = 118
		lexer.MarkEnd()
		return result
	case 184:
		if (lookahead == 101) {
			state = 242
			goto nextState
		}
		return result
	case 185:
		if (lookahead == 99) {
			state = 243
			goto nextState
		}
		return result
	case 186:
		if (lookahead == 114) {
			state = 244
			goto nextState
		}
		return result
	case 187:
		if (lookahead == 97) {
			state = 245
			goto nextState
		}
		return result
	case 188:
		if (lookahead == 101) {
			state = 246
			goto nextState
		}
		return result
	case 189:
		if (lookahead == 105) {
			state = 247
			goto nextState
		}
		return result
	case 190:
		if (lookahead == 111) {
			state = 248
			goto nextState
		}
		return result
	case 191:
		if (lookahead == 105) {
			state = 249
			goto nextState
		}
		return result
	case 192:
		if (lookahead == 114) {
			state = 250
			goto nextState
		}
		return result
	case 193:
		if (lookahead == 115) {
			state = 251
			goto nextState
		}
		return result
	case 194:
		if (lookahead == 105) {
			state = 252
			goto nextState
		}
		return result
	case 195:
		if (lookahead == 110) {
			state = 253
			goto nextState
		}
		return result
	case 196:
		if (lookahead == 114) {
			state = 254
			goto nextState
		}
		return result
	case 197:
		if (lookahead == 99) {
			state = 255
			goto nextState
		}
		return result
	case 198:
		if (lookahead == 111) {
			state = 256
			goto nextState
		}
		return result
	case 199:
		if (lookahead == 101) {
			state = 257
			goto nextState
		}
		return result
	case 200:
		result = true
		lexer.ResultSymbol = 114
		lexer.MarkEnd()
		return result
	case 201:
		if (lookahead == 119) {
			state = 258
			goto nextState
		}
		return result
	case 202:
		result = true
		lexer.ResultSymbol = 116
		lexer.MarkEnd()
		return result
	case 203:
		result = true
		lexer.ResultSymbol = 6
		lexer.MarkEnd()
		if (lookahead == 111) {
			state = 259
			goto nextState
		}
		return result
	case 204:
		if (lookahead == 102) {
			state = 260
			goto nextState
		}
		return result
	case 205:
		if (lookahead == 117) {
			state = 261
			goto nextState
		}
		return result
	case 206:
		if (lookahead == 111) {
			state = 262
			goto nextState
		}
		return result
	case 207:
		if (lookahead == 103) {
			state = 263
			goto nextState
		}
		return result
	case 208:
		result = true
		lexer.ResultSymbol = 95
		lexer.MarkEnd()
		return result
	case 209:
		if (lookahead == 101) {
			state = 264
			goto nextState
		}
		return result
	case 210:
		result = true
		lexer.ResultSymbol = 16
		lexer.MarkEnd()
		return result
	case 211:
		if (lookahead == 100) {
			state = 265
			goto nextState
		}
		return result
	case 212:
		if (lookahead == 97) {
			state = 266
			goto nextState
		}
		return result
	case 213:
		if (lookahead == 115) {
			state = 267
			goto nextState
		}
		return result
	case 214:
		if (lookahead == 116) {
			state = 268
			goto nextState
		}
		return result
	case 215:
		result = true
		lexer.ResultSymbol = 49
		lexer.MarkEnd()
		return result
	case 216:
		result = true
		lexer.ResultSymbol = 29
		lexer.MarkEnd()
		return result
	case 217:
		if (lookahead == 97) {
			state = 269
			goto nextState
		}
		return result
	case 218:
		result = true
		lexer.ResultSymbol = 35
		lexer.MarkEnd()
		return result
	case 219:
		result = true
		lexer.ResultSymbol = 42
		lexer.MarkEnd()
		return result
	case 220:
		result = true
		lexer.ResultSymbol = 48
		lexer.MarkEnd()
		return result
	case 221:
		result = true
		lexer.ResultSymbol = 20
		lexer.MarkEnd()
		return result
	case 222:
		if (lookahead == 110) {
			state = 270
			goto nextState
		}
		return result
	case 223:
		if (lookahead == 103) {
			state = 271
			goto nextState
		}
		return result
	case 224:
		if (lookahead == 114) {
			state = 272
			goto nextState
		}
		return result
	case 225:
		if (lookahead == 108) {
			state = 273
			goto nextState
		}
		return result
	case 226:
		if (lookahead == 101) {
			state = 274
			goto nextState
		}
		return result
	case 227:
		if (lookahead == 116) {
			state = 275
			goto nextState
		}
		return result
	case 228:
		if (lookahead == 100) {
			state = 276
			goto nextState
		}
		return result
	case 229:
		result = true
		lexer.ResultSymbol = 117
		lexer.MarkEnd()
		return result
	case 230:
		if (lookahead == 108) {
			state = 277
			goto nextState
		}
		return result
	case 231:
		if (lookahead == 105) {
			state = 278
			goto nextState
		}
		return result
	case 232:
		if (lookahead == 108) {
			state = 279
			goto nextState
		}
		return result
	case 233:
		if (lookahead == 109) {
			state = 280
			goto nextState
		}
		return result
	case 234:
		if (lookahead == 116) {
			state = 281
			goto nextState
		}
		return result
	case 235:
		result = true
		lexer.ResultSymbol = 151
		lexer.MarkEnd()
		return result
	case 236:
		if (lookahead == 110) {
			state = 282
			goto nextState
		}
		return result
	case 237:
		if (lookahead == 102) {
			state = 283
			goto nextState
		}
		return result
	case 238:
		result = true
		lexer.ResultSymbol = 153
		lexer.MarkEnd()
		return result
	case 239:
		if (lookahead == 101) {
			state = 284
			goto nextState
		}
		return result
	case 240:
		if (lookahead == 112) {
			state = 285
			goto nextState
		}
		return result
	case 241:
		result = true
		lexer.ResultSymbol = 156
		lexer.MarkEnd()
		return result
	case 242:
		if (lookahead == 114) {
			state = 286
			goto nextState
		}
		return result
	case 243:
		if (lookahead == 116) {
			state = 287
			goto nextState
		}
		return result
	case 244:
		if (lookahead == 105) {
			state = 288
			goto nextState
		}
		return result
	case 245:
		if (lookahead == 116) {
			state = 289
			goto nextState
		}
		return result
	case 246:
		if (lookahead == 99) {
			state = 290
			goto nextState
		}
		return result
	case 247:
		if (lookahead == 99) {
			state = 291
			goto nextState
		}
		return result
	case 248:
		if (lookahead == 110) {
			state = 292
			goto nextState
		}
		return result
	case 249:
		if (lookahead == 114) {
			state = 293
			goto nextState
		}
		return result
	case 250:
		if (lookahead == 110) {
			state = 294
			goto nextState
		}
		return result
	case 251:
		if (lookahead == 102) {
			state = 295
			goto nextState
		}
		return result
	case 252:
		if (lookahead == 99) {
			state = 296
			goto nextState
		}
		return result
	case 253:
		if (lookahead == 103) {
			state = 297
			goto nextState
		}
		return result
	case 254:
		result = true
		lexer.ResultSymbol = 115
		lexer.MarkEnd()
		return result
	case 255:
		if (lookahead == 104) {
			state = 298
			goto nextState
		}
		return result
	case 256:
		if (lookahead == 108) {
			state = 299
			goto nextState
		}
		return result
	case 257:
		if (lookahead == 116) {
			state = 300
			goto nextState
		}
		return result
	case 258:
		result = true
		lexer.ResultSymbol = 39
		lexer.MarkEnd()
		return result
	case 259:
		if (lookahead == 102) {
			state = 301
			goto nextState
		}
		return result
	case 260:
		if (lookahead == 105) {
			state = 302
			goto nextState
		}
		return result
	case 261:
		if (lookahead == 101) {
			state = 303
			goto nextState
		}
		return result
	case 262:
		if (lookahead == 119) {
			state = 304
			goto nextState
		}
		return result
	case 263:
		result = true
		lexer.ResultSymbol = 54
		lexer.MarkEnd()
		return result
	case 264:
		result = true
		lexer.ResultSymbol = 32
		lexer.MarkEnd()
		return result
	case 265:
		result = true
		lexer.ResultSymbol = 44
		lexer.MarkEnd()
		return result
	case 266:
		if (lookahead == 99) {
			state = 305
			goto nextState
		}
		return result
	case 267:
		if (lookahead == 111) {
			state = 306
			goto nextState
		}
		return result
	case 268:
		result = true
		lexer.ResultSymbol = 17
		lexer.MarkEnd()
		if (lookahead == 115) {
			state = 307
			goto nextState
		}
		return result
	case 269:
		if (lookahead == 110) {
			state = 308
			goto nextState
		}
		return result
	case 270:
		if (lookahead == 117) {
			state = 309
			goto nextState
		}
		return result
	case 271:
		if (lookahead == 101) {
			state = 310
			goto nextState
		}
		return result
	case 272:
		if (lookahead == 101) {
			state = 311
			goto nextState
		}
		return result
	case 273:
		if (lookahead == 116) {
			state = 312
			goto nextState
		}
		return result
	case 274:
		result = true
		lexer.ResultSymbol = 96
		lexer.MarkEnd()
		return result
	case 275:
		result = true
		lexer.ResultSymbol = 3
		lexer.MarkEnd()
		return result
	case 276:
		if (lookahead == 115) {
			state = 313
			goto nextState
		}
		return result
	case 277:
		if (lookahead == 121) {
			state = 314
			goto nextState
		}
		return result
	case 278:
		if (lookahead == 111) {
			state = 315
			goto nextState
		}
		return result
	case 279:
		result = true
		lexer.ResultSymbol = 144
		lexer.MarkEnd()
		return result
	case 280:
		if (lookahead == 101) {
			state = 316
			goto nextState
		}
		return result
	case 281:
		result = true
		lexer.ResultSymbol = 14
		lexer.MarkEnd()
		return result
	case 282:
		if (lookahead == 99) {
			state = 317
			goto nextState
		}
		return result
	case 283:
		if (lookahead == 97) {
			state = 318
			goto nextState
		}
		return result
	case 284:
		result = true
		lexer.ResultSymbol = 131
		lexer.MarkEnd()
		return result
	case 285:
		if (lookahead == 97) {
			state = 319
			goto nextState
		}
		return result
	case 286:
		result = true
		lexer.ResultSymbol = 133
		lexer.MarkEnd()
		return result
	case 287:
		result = true
		lexer.ResultSymbol = 137
		lexer.MarkEnd()
		return result
	case 288:
		if (lookahead == 100) {
			state = 320
			goto nextState
		}
		return result
	case 289:
		if (lookahead == 101) {
			state = 321
			goto nextState
		}
		return result
	case 290:
		if (lookahead == 116) {
			state = 322
			goto nextState
		}
		return result
	case 291:
		result = true
		lexer.ResultSymbol = 127
		lexer.MarkEnd()
		return result
	case 292:
		if (lookahead == 108) {
			state = 323
			goto nextState
		}
		return result
	case 293:
		if (lookahead == 101) {
			state = 324
			goto nextState
		}
		return result
	case 294:
		result = true
		lexer.ResultSymbol = 38
		lexer.MarkEnd()
		return result
	case 295:
		if (lookahead == 105) {
			state = 325
			goto nextState
		}
		return result
	case 296:
		result = true
		lexer.ResultSymbol = 121
		lexer.MarkEnd()
		return result
	case 297:
		result = true
		lexer.ResultSymbol = 135
		lexer.MarkEnd()
		return result
	case 298:
		result = true
		lexer.ResultSymbol = 24
		lexer.MarkEnd()
		return result
	case 299:
		result = true
		lexer.ResultSymbol = 136
		lexer.MarkEnd()
		return result
	case 300:
		result = true
		lexer.ResultSymbol = 112
		lexer.MarkEnd()
		return result
	case 301:
		result = true
		lexer.ResultSymbol = 13
		lexer.MarkEnd()
		return result
	case 302:
		if (lookahead == 110) {
			state = 326
			goto nextState
		}
		return result
	case 303:
		result = true
		lexer.ResultSymbol = 154
		lexer.MarkEnd()
		return result
	case 304:
		if (lookahead == 110) {
			state = 327
			goto nextState
		}
		return result
	case 305:
		if (lookahead == 116) {
			state = 328
			goto nextState
		}
		return result
	case 306:
		if (lookahead == 114) {
			state = 329
			goto nextState
		}
		return result
	case 307:
		result = true
		lexer.ResultSymbol = 150
		lexer.MarkEnd()
		return result
	case 308:
		result = true
		lexer.ResultSymbol = 134
		lexer.MarkEnd()
		return result
	case 309:
		if (lookahead == 101) {
			state = 330
			goto nextState
		}
		return result
	case 310:
		if (lookahead == 114) {
			state = 331
			goto nextState
		}
		return result
	case 311:
		result = true
		lexer.ResultSymbol = 126
		lexer.MarkEnd()
		return result
	case 312:
		result = true
		lexer.ResultSymbol = 5
		lexer.MarkEnd()
		return result
	case 313:
		result = true
		lexer.ResultSymbol = 142
		lexer.MarkEnd()
		return result
	case 314:
		result = true
		lexer.ResultSymbol = 43
		lexer.MarkEnd()
		return result
	case 315:
		if (lookahead == 110) {
			state = 332
			goto nextState
		}
		return result
	case 316:
		if (lookahead == 110) {
			state = 333
			goto nextState
		}
		return result
	case 317:
		if (lookahead == 101) {
			state = 334
			goto nextState
		}
		return result
	case 318:
		if (lookahead == 99) {
			state = 335
			goto nextState
		}
		return result
	case 319:
		if (lookahead == 99) {
			state = 336
			goto nextState
		}
		return result
	case 320:
		if (lookahead == 101) {
			state = 337
			goto nextState
		}
		return result
	case 321:
		result = true
		lexer.ResultSymbol = 128
		lexer.MarkEnd()
		return result
	case 322:
		if (lookahead == 101) {
			state = 338
			goto nextState
		}
		return result
	case 323:
		if (lookahead == 121) {
			state = 339
			goto nextState
		}
		return result
	case 324:
		result = true
		lexer.ResultSymbol = 141
		lexer.MarkEnd()
		return result
	case 325:
		if (lookahead == 101) {
			state = 340
			goto nextState
		}
		return result
	case 326:
		if (lookahead == 101) {
			state = 341
			goto nextState
		}
		return result
	case 327:
		result = true
		lexer.ResultSymbol = 155
		lexer.MarkEnd()
		return result
	case 328:
		result = true
		lexer.ResultSymbol = 138
		lexer.MarkEnd()
		return result
	case 329:
		result = true
		lexer.ResultSymbol = 139
		lexer.MarkEnd()
		return result
	case 330:
		result = true
		lexer.ResultSymbol = 36
		lexer.MarkEnd()
		return result
	case 331:
		result = true
		lexer.ResultSymbol = 37
		lexer.MarkEnd()
		return result
	case 332:
		result = true
		lexer.ResultSymbol = 50
		lexer.MarkEnd()
		return result
	case 333:
		if (lookahead == 116) {
			state = 342
			goto nextState
		}
		return result
	case 334:
		if (lookahead == 111) {
			state = 343
			goto nextState
		}
		return result
	case 335:
		if (lookahead == 101) {
			state = 344
			goto nextState
		}
		return result
	case 336:
		if (lookahead == 101) {
			state = 345
			goto nextState
		}
		return result
	case 337:
		result = true
		lexer.ResultSymbol = 130
		lexer.MarkEnd()
		return result
	case 338:
		if (lookahead == 100) {
			state = 346
			goto nextState
		}
		return result
	case 339:
		result = true
		lexer.ResultSymbol = 122
		lexer.MarkEnd()
		return result
	case 340:
		if (lookahead == 115) {
			state = 347
			goto nextState
		}
		return result
	case 341:
		if (lookahead == 100) {
			state = 348
			goto nextState
		}
		return result
	case 342:
		if (lookahead == 115) {
			state = 349
			goto nextState
		}
		return result
	case 343:
		if (lookahead == 102) {
			state = 350
			goto nextState
		}
		return result
	case 344:
		result = true
		lexer.ResultSymbol = 145
		lexer.MarkEnd()
		return result
	case 345:
		result = true
		lexer.ResultSymbol = 9
		lexer.MarkEnd()
		return result
	case 346:
		result = true
		lexer.ResultSymbol = 129
		lexer.MarkEnd()
		return result
	case 347:
		result = true
		lexer.ResultSymbol = 140
		lexer.MarkEnd()
		return result
	case 348:
		result = true
		lexer.ResultSymbol = 119
		lexer.MarkEnd()
		return result
	case 349:
		result = true
		lexer.ResultSymbol = 143
		lexer.MarkEnd()
		return result
	case 350:
		result = true
		lexer.ResultSymbol = 93
		lexer.MarkEnd()
		return result
	default:
		return false
	}
}

func loadTables() *ts.Language {
	tables, err := ts.DecodeTables(tablesBlob)
	if err != nil {
		panic("typescript: reading tables.zst: " + err.Error())
	}
	characterSets = tables.CharacterSets
	language := &tables.Language
	language.LexFn = tsLex
	language.KeywordLexFn = tsLexKeywords
	language.Scanner = grammar.Scanner()
	return language
}

var (
	loadOnce  sync.Once
	generated *ts.Language
)

// Language returns the typescript grammar, decoding its tables when a
// parse needs them.
func Language() *ts.Language {
	loadOnce.Do(func() { generated = loadTables() })
	return generated
}
