// Code generated by ts-translate. DO NOT EDIT.

package typescript

import (
	_ "embed"
	"sync"

	ts "github.com/wow-look-at-my/go-tree-sitter"
	grammar "github.com/wow-look-at-my/go-tree-sitter/grammars/typescript"
)

//go:embed tables.zst
var tablesBlob []byte

func loadTables() *ts.Language {
	return ts.LoadGrammar("typescript", tablesBlob, grammar.Scanner())
}

var language = sync.OnceValue(loadTables)

// Language returns the grammar, decoding its tables when a parse needs them.
func Language() *ts.Language { return language() }
