// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: `(?s)(\s+([,.;:!?]))(?s:.*)`

package commentfix


import "github.com/wow-look-at-my/go-regex-compiler/match"



import "unicode/utf8"

// englishPat1At reports whether input fully matches the regex `(?s)(\s+([,.;:!?]))(?s:.*)`.
func englishPat1At(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		// Invalid UTF-8 decodes as (RuneError, 1) and is matched as U+FFFD,
		// exactly like regexp: each bad byte is one U+FFFD rune.
		r, size := utf8.DecodeRuneInString(input[i:])
		switch state {

		case 0:
			switch {
			case match.InRange(r, '\t', '\n'), match.InRange(r, '\f', '\r'), r == ' ': state = 1
			default: return false
			}
		case 1:
			switch {
			case match.InRange(r, '\t', '\n'), match.InRange(r, '\f', '\r'), r == ' ': state = 1
			case r == '!', r == ',', r == '.', match.InRange(r, ':', ';'), r == '?': state = 2
			default: return false
			}
		case 2:
			switch {
			case match.InRange(r, '\x00', '\U0010ffff'): state = 3
			default: return false
			}
		case 3:
			switch {
			case match.InRange(r, '\x00', '\U0010ffff'): state = 3
			default: return false
			}
		default:
			return false
		}
		i += size
	}

	switch state {
	case 2, 3:
		return true
	default:
		return false
	}
}


// englishPat1FindIndex returns the submatch index slice for the regex `(?s)(\s+([,.;:!?]))(?s:.*)`,
// or nil if the input does not match. It is a COMPILED one-pass automaton: a
// straight-line state machine that records capture-group byte offsets inline
// while consuming the input in a single left-to-right pass — no NFA program,
// thread lists, or epsilon-closure at run time. The slice layout matches
// regexp.Regexp.FindStringSubmatchIndex: pair (2*g, 2*g+1) is group g's
// [start, end) byte offsets, index 0 is the whole match, and a group that did
// not participate is (-1, -1). It allocates only the result slice and is safe
// for concurrent use (all state is local).
func englishPat1FindIndex(input string) []int {
	var caps [6]int
	for i := range caps {
		caps[i] = -1
	}
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return nil
		}
		switch state {
		case 0:
			if !(match.InRange(r, '\t', '\n') || match.InRange(r, '\f', '\r') || r == ' ') { return nil }
			caps[2] = i; state = 1
		case 1:
			switch {
			case match.InRange(r, '\t', '\n'), match.InRange(r, '\f', '\r'), r == ' ': state = 1
			case r == '!', r == ',', r == '.', match.InRange(r, ':', ';'), r == '?': caps[4] = i; state = 2
			default: return nil
			}
		case 2:
			switch {
			default: caps[3] = i; caps[5] = i; state = 3
			}
		case 3:
			switch {
			default: state = 3
			}
		default:
			return nil
		}
		i += size
	}
	switch state {
	case 2:
		caps[3] = len(input); caps[5] = len(input)
	case 3:
	default:
		return nil
	}
	result := make([]int, 6)
	copy(result, caps[:])
	result[0] = 0
	result[1] = len(input)
	return result
}

// englishPat1Find returns captured groups for the regex `(?s)(\s+([,.;:!?]))(?s:.*)`.
// Returns nil if the input does not match. Index 0 is the entire match,
// indices 1..N are capture groups. A group that did not participate in the
// match yields "" (parity with regexp.Regexp.FindStringSubmatch); use
// englishPat1FindIndex to distinguish an absent group (offset pair -1) from an
// empty one.
func englishPat1Find(input string) []string {
	idx := englishPat1FindIndex(input)
	if idx == nil {
		return nil
	}
	result := make([]string, 3)
	for g := 0; g < 3; g++ {
		s, e := idx[g*2], idx[g*2+1]
		if s >= 0 && e >= 0 && s <= len(input) && e <= len(input) {
			result[g] = input[s:e]
		}
	}
	return result
}

// englishPat1Names returns the names of the capture groups for the regex
// `(?s)(\s+([,.;:!?]))(?s:.*)`. The slice has one entry per group index: index 0 (the
// whole match) is always "", and an unnamed group is "". This is parity with
// regexp.Regexp.SubexpNames.
func englishPat1Names() []string {
	return []string{"", "", ""}
}

