// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: `  +`

package commentfix



import "strings"


// englishPat2Has reports whether any substring of input matches the regex `  +`.
func englishPat2Has(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		if state == 0 {
			// The DFA can only leave the start state on ' ': memchr to it.
			j := strings.IndexByte(input[i:], ' ')
			if j < 0 {
				return false
			}
			i += j
		}
		c := input[i]
		switch state {

		case 0:
			switch {
			case c == ' ': state = 1
			default: state = 0
			}
		case 1:
			switch {
			case c == ' ': return true
			default: state = 0
			}
		default:
			state = 0
		}
	}

	return false
}
