// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: `([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)#([0-9]+)`

package commentfix


import "github.com/wow-look-at-my/go-regex-compiler/match"



// englishPat0Has reports whether any substring of input matches the regex `([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)#([0-9]+)`.
func englishPat0Has(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {

		case 0:
			switch {
			case match.InRange(c, '-', '.'), match.InRange(c, '0', '9'), match.InRange(c, 'A', 'Z'), c == '_', match.InRange(c, 'a', 'z'): state = 1
			default: state = 0
			}
		case 1:
			switch {
			case match.InRange(c, '-', '.'): state = 1
			case c == '/': state = 2
			case match.InRange(c, '0', '9'), match.InRange(c, 'A', 'Z'), c == '_', match.InRange(c, 'a', 'z'): state = 1
			default: state = 0
			}
		case 2:
			switch {
			case match.InRange(c, '-', '.'), match.InRange(c, '0', '9'), match.InRange(c, 'A', 'Z'), c == '_', match.InRange(c, 'a', 'z'): state = 3
			default: state = 0
			}
		case 3:
			switch {
			case c == '#': state = 4
			case match.InRange(c, '-', '.'): state = 3
			case c == '/': state = 2
			case match.InRange(c, '0', '9'), match.InRange(c, 'A', 'Z'), c == '_', match.InRange(c, 'a', 'z'): state = 3
			default: state = 0
			}
		case 4:
			switch {
			case match.InRange(c, '-', '.'): state = 1
			case match.InRange(c, '0', '9'): return true
			case match.InRange(c, 'A', 'Z'), c == '_', match.InRange(c, 'a', 'z'): state = 1
			default: state = 0
			}
		default:
			state = 0
		}
	}

	return false
}
