// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: `\s+([,.;:!?])`

package commentfix


import "github.com/wow-look-at-my/go-regex-compiler/match"



// englishPat1Has reports whether any substring of input matches the regex `\s+([,.;:!?])`.
func englishPat1Has(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {

		case 0:
			switch {
			case match.InRange(c, '\t', '\n'), match.InRange(c, '\f', '\r'), c == ' ': state = 1
			default: state = 0
			}
		case 1:
			switch {
			case match.InRange(c, '\t', '\n'), match.InRange(c, '\f', '\r'), c == ' ': state = 1
			case c == '!', c == ',', c == '.', match.InRange(c, ':', ';'), c == '?': return true
			default: state = 0
			}
		default:
			state = 0
		}
	}

	return false
}
