// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: `(?s)(([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)#([0-9]+))(?s:.*)`

package commentfix


import "github.com/wow-look-at-my/go-regex-compiler/match"



import "unicode/utf8"

// englishPat0At reports whether input fully matches the regex `(?s)(([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)#([0-9]+))(?s:.*)`.
func englishPat0At(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		// Invalid UTF-8 decodes as (RuneError, 1) and is matched as U+FFFD,
		// exactly like regexp: each bad byte is one U+FFFD rune.
		r, size := utf8.DecodeRuneInString(input[i:])
		switch state {

		case 0:
			switch {
			case match.InRange(r, '-', '.'), match.InRange(r, '0', '9'), match.InRange(r, 'A', 'Z'), r == '_', match.InRange(r, 'a', 'z'): state = 1
			default: return false
			}
		case 1:
			switch {
			case match.InRange(r, '-', '.'): state = 1
			case r == '/': state = 2
			case match.InRange(r, '0', '9'), match.InRange(r, 'A', 'Z'), r == '_', match.InRange(r, 'a', 'z'): state = 1
			default: return false
			}
		case 2:
			switch {
			case match.InRange(r, '-', '.'), match.InRange(r, '0', '9'), match.InRange(r, 'A', 'Z'), r == '_', match.InRange(r, 'a', 'z'): state = 3
			default: return false
			}
		case 3:
			switch {
			case r == '#': state = 4
			case match.InRange(r, '-', '.'), match.InRange(r, '0', '9'), match.InRange(r, 'A', 'Z'), r == '_', match.InRange(r, 'a', 'z'): state = 3
			default: return false
			}
		case 4:
			switch {
			case match.InRange(r, '0', '9'): state = 5
			default: return false
			}
		case 5:
			switch {
			case match.InRange(r, '\x00', '/'): state = 6
			case match.InRange(r, '0', '9'): state = 5
			case match.InRange(r, ':', '\U0010ffff'): state = 6
			default: return false
			}
		case 6:
			switch {
			case match.InRange(r, '\x00', '\U0010ffff'): state = 6
			default: return false
			}
		default:
			return false
		}
		i += size
	}

	switch state {
	case 5, 6:
		return true
	default:
		return false
	}
}

// englishPat0FindIndex returns the submatch index slice for the regex `(?s)(([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)#([0-9]+))(?s:.*)`,
// or nil if the input does not match. It is a COMPILED tagged-DFA register
// machine: a straight-line state machine that records capture-group byte offsets
// into an integer register file in a single left-to-right pass — no NFA program,
// live-position list, or epsilon-closure at run time. Each config that is live
// in a state owns a block of the register file; a transition sets a block's slot
// to the current position when a group boundary is crossed, or copies it from
// the source config's block. At end of input the winning config's block holds
// the capture offsets. The slice layout matches
// regexp.Regexp.FindStringSubmatchIndex: pair (2*g, 2*g+1) is group g's
// [start, end) byte offsets, index 0 is the whole match, and a group that did
// not participate is (-1, -1). It allocates only the result slice and is safe
// for concurrent use (all state is local).
func englishPat0FindIndex(input string) []int {
	var reg [24]int
	for i := range reg {
		reg[i] = -1
	}
	reg[2] = 0
	reg[4] = 0
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return nil
		}
		np := i + size
		switch state {
		case 0:
			switch {
			case match.InRange(r, '-', '.'): reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[13] = reg[5]; reg[14] = reg[6]; reg[15] = reg[7]; state = 1
			case match.InRange(r, '0', '9'): reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[13] = reg[5]; reg[14] = reg[6]; reg[15] = reg[7]; state = 1
			case match.InRange(r, 'A', 'Z'): reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[13] = reg[5]; reg[14] = reg[6]; reg[15] = reg[7]; state = 1
			case r == '_': reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[13] = reg[5]; reg[14] = reg[6]; reg[15] = reg[7]; state = 1
			case match.InRange(r, 'a', 'z'): reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[13] = reg[5]; reg[14] = reg[6]; reg[15] = reg[7]; state = 1
			default:
				return nil
			}
		case 1:
			switch {
			case match.InRange(r, '-', '.'): reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[13] = reg[5]; reg[14] = reg[6]; reg[15] = reg[7]; state = 1
			case r == '/': reg[2] = reg[10]; reg[3] = reg[11]; reg[4] = reg[12]; reg[5] = reg[13]; reg[6] = reg[14]; reg[7] = reg[15]; state = 2
			case match.InRange(r, '0', '9'): reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[13] = reg[5]; reg[14] = reg[6]; reg[15] = reg[7]; state = 1
			case match.InRange(r, 'A', 'Z'): reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[13] = reg[5]; reg[14] = reg[6]; reg[15] = reg[7]; state = 1
			case r == '_': reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[13] = reg[5]; reg[14] = reg[6]; reg[15] = reg[7]; state = 1
			case match.InRange(r, 'a', 'z'): reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[13] = reg[5]; reg[14] = reg[6]; reg[15] = reg[7]; state = 1
			default:
				return nil
			}
		case 2:
			switch {
			case match.InRange(r, '-', '.'): reg[13] = np; reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[14] = reg[6]; reg[15] = reg[7]; state = 3
			case match.InRange(r, '0', '9'): reg[13] = np; reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[14] = reg[6]; reg[15] = reg[7]; state = 3
			case match.InRange(r, 'A', 'Z'): reg[13] = np; reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[14] = reg[6]; reg[15] = reg[7]; state = 3
			case r == '_': reg[13] = np; reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[14] = reg[6]; reg[15] = reg[7]; state = 3
			case match.InRange(r, 'a', 'z'): reg[13] = np; reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[14] = reg[6]; reg[15] = reg[7]; state = 3
			default:
				return nil
			}
		case 3:
			switch {
			case r == '#': reg[6] = np; reg[2] = reg[10]; reg[3] = reg[11]; reg[4] = reg[12]; reg[5] = reg[13]; reg[7] = reg[15]; state = 4
			case match.InRange(r, '-', '.'): reg[13] = np; reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[14] = reg[6]; reg[15] = reg[7]; state = 3
			case match.InRange(r, '0', '9'): reg[13] = np; reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[14] = reg[6]; reg[15] = reg[7]; state = 3
			case match.InRange(r, 'A', 'Z'): reg[13] = np; reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[14] = reg[6]; reg[15] = reg[7]; state = 3
			case r == '_': reg[13] = np; reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[14] = reg[6]; reg[15] = reg[7]; state = 3
			case match.InRange(r, 'a', 'z'): reg[13] = np; reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[14] = reg[6]; reg[15] = reg[7]; state = 3
			default:
				return nil
			}
		case 4:
			if !(match.InRange(r, '0', '9')) { return nil }
			reg[11] = np; reg[15] = np; reg[19] = np; reg[23] = np; reg[10] = reg[2]; reg[12] = reg[4]; reg[13] = reg[5]; reg[14] = reg[6]; reg[18] = reg[2]; reg[20] = reg[4]; reg[21] = reg[5]; reg[22] = reg[6]; state = 5
		case 5:
			switch {
			case match.InRange(r, '\x00', '/'): reg[2] = reg[10]; reg[3] = reg[11]; reg[4] = reg[12]; reg[5] = reg[13]; reg[6] = reg[14]; reg[7] = reg[15]; state = 6
			case match.InRange(r, '0', '9'): reg[11] = np; reg[15] = np; reg[19] = np; reg[23] = np; reg[10] = reg[2]; reg[12] = reg[4]; reg[13] = reg[5]; reg[14] = reg[6]; reg[18] = reg[2]; reg[20] = reg[4]; reg[21] = reg[5]; reg[22] = reg[6]; state = 5
			case match.InRange(r, ':', '\U0010ffff'): reg[2] = reg[10]; reg[3] = reg[11]; reg[4] = reg[12]; reg[5] = reg[13]; reg[6] = reg[14]; reg[7] = reg[15]; state = 6
			default:
				return nil
			}
		case 6:
			if !(match.InRange(r, '\x00', '\U0010ffff')) { return nil }
			reg[10] = reg[2]; reg[11] = reg[3]; reg[12] = reg[4]; reg[13] = reg[5]; reg[14] = reg[6]; reg[15] = reg[7]; state = 6
		default:
			return nil
		}
		i += size
	}
	switch state {
	case 6:
		result := make([]int, 8)
		result[0] = 0
		result[1] = len(input)
		copy(result[2:], reg[10:16])
		return result
	case 5:
		result := make([]int, 8)
		result[0] = 0
		result[1] = len(input)
		copy(result[2:], reg[18:24])
		return result
	default:
		return nil
	}
}

// englishPat0Find returns captured groups for the regex `(?s)(([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)#([0-9]+))(?s:.*)`.
// Returns nil if the input does not match. Index 0 is the entire match,
// indices 1..N are capture groups. A group that did not participate in the
// match yields "" (parity with regexp.Regexp.FindStringSubmatch); use
// englishPat0FindIndex to distinguish an absent group (offset pair -1) from an
// empty one.
func englishPat0Find(input string) []string {
	idx := englishPat0FindIndex(input)
	if idx == nil {
		return nil
	}
	result := make([]string, 4)
	for g := 0; g < 4; g++ {
		s, e := idx[g*2], idx[g*2+1]
		if s >= 0 && e >= 0 && s <= len(input) && e <= len(input) {
			result[g] = input[s:e]
		}
	}
	return result
}

// englishPat0Names returns the names of the capture groups for the regex
// `(?s)(([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)#([0-9]+))(?s:.*)`. The slice has one entry per group index: index 0 (the
// whole match) is always "", and an unnamed group is "". This is parity with
// regexp.Regexp.SubexpNames.
func englishPat0Names() []string {
	return []string{"", "", "", ""}
}

