// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: `(?s)((?i)(?:two|three|four|five|six|seven|eight|nine|ten|dozen)\s+([a-z]))(?s:.*)`

package commentfix


import "github.com/wow-look-at-my/go-regex-compiler/match"



import "unicode/utf8"

// numbersPat7At reports whether input fully matches the regex `(?s)((?i)(?:two|three|four|five|six|seven|eight|nine|ten|dozen)\s+([a-z]))(?s:.*)`.
func numbersPat7At(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		// Invalid UTF-8 decodes as (RuneError, 1) and is matched as U+FFFD,
		// exactly like regexp: each bad byte is one U+FFFD rune.
		r, size := utf8.DecodeRuneInString(input[i:])
		switch state {

		case 0:
			switch {
			case r == 'D': state = 1
			case r == 'E': state = 2
			case r == 'F': state = 3
			case r == 'N': state = 4
			case r == 'S': state = 5
			case r == 'T': state = 6
			case r == 'd': state = 1
			case r == 'e': state = 2
			case r == 'f': state = 3
			case r == 'n': state = 4
			case r == 's': state = 5
			case r == 't': state = 6
			case r == 'ſ': state = 5
			default: return false
			}
		case 1:
			switch {
			case r == 'O', r == 'o': state = 7
			default: return false
			}
		case 2:
			switch {
			case r == 'I', r == 'i': state = 8
			default: return false
			}
		case 3:
			switch {
			case r == 'I': state = 9
			case r == 'O': state = 10
			case r == 'i': state = 9
			case r == 'o': state = 10
			default: return false
			}
		case 4:
			switch {
			case r == 'I', r == 'i': state = 11
			default: return false
			}
		case 5:
			switch {
			case r == 'E': state = 12
			case r == 'I': state = 13
			case r == 'e': state = 12
			case r == 'i': state = 13
			default: return false
			}
		case 6:
			switch {
			case r == 'E': state = 14
			case r == 'H': state = 15
			case r == 'W': state = 16
			case r == 'e': state = 14
			case r == 'h': state = 15
			case r == 'w': state = 16
			default: return false
			}
		case 7:
			switch {
			case r == 'Z', r == 'z': state = 17
			default: return false
			}
		case 8:
			switch {
			case r == 'G', r == 'g': state = 18
			default: return false
			}
		case 9:
			switch {
			case r == 'V', r == 'v': state = 19
			default: return false
			}
		case 10:
			switch {
			case r == 'U', r == 'u': state = 20
			default: return false
			}
		case 11:
			switch {
			case r == 'N', r == 'n': state = 21
			default: return false
			}
		case 12:
			switch {
			case r == 'V', r == 'v': state = 22
			default: return false
			}
		case 13:
			switch {
			case r == 'X', r == 'x': state = 23
			default: return false
			}
		case 14:
			switch {
			case r == 'N', r == 'n': state = 23
			default: return false
			}
		case 15:
			switch {
			case r == 'R', r == 'r': state = 24
			default: return false
			}
		case 16:
			switch {
			case r == 'O', r == 'o': state = 23
			default: return false
			}
		case 17:
			switch {
			case r == 'E', r == 'e': state = 25
			default: return false
			}
		case 18:
			switch {
			case r == 'H', r == 'h': state = 26
			default: return false
			}
		case 19:
			switch {
			case r == 'E', r == 'e': state = 23
			default: return false
			}
		case 20:
			switch {
			case r == 'R', r == 'r': state = 23
			default: return false
			}
		case 21:
			switch {
			case r == 'E', r == 'e': state = 23
			default: return false
			}
		case 22:
			switch {
			case r == 'E', r == 'e': state = 27
			default: return false
			}
		case 23:
			switch {
			case match.InRange(r, '\t', '\n'), match.InRange(r, '\f', '\r'), r == ' ': state = 28
			default: return false
			}
		case 24:
			switch {
			case r == 'E', r == 'e': state = 29
			default: return false
			}
		case 25:
			switch {
			case r == 'N', r == 'n': state = 23
			default: return false
			}
		case 26:
			switch {
			case r == 'T', r == 't': state = 23
			default: return false
			}
		case 27:
			switch {
			case r == 'N', r == 'n': state = 23
			default: return false
			}
		case 28:
			switch {
			case match.InRange(r, '\t', '\n'), match.InRange(r, '\f', '\r'), r == ' ': state = 28
			case match.InRange(r, 'A', 'Z'), match.InRange(r, 'a', 'z'), r == 'ſ', r == 'K': state = 30
			default: return false
			}
		case 29:
			switch {
			case r == 'E', r == 'e': state = 23
			default: return false
			}
		case 30:
			switch {
			case match.InRange(r, '\x00', '\U0010ffff'): state = 31
			default: return false
			}
		case 31:
			switch {
			case match.InRange(r, '\x00', '\U0010ffff'): state = 31
			default: return false
			}
		default:
			return false
		}
		i += size
	}

	switch state {
	case 30, 31:
		return true
	default:
		return false
	}
}

// numbersPat7FindIndex returns the submatch index slice for the regex `(?s)((?i)(?:two|three|four|five|six|seven|eight|nine|ten|dozen)\s+([a-z]))(?s:.*)`,
// or nil if the input does not match. It is a COMPILED tagged-DFA register
// machine: a straight-line state machine that records capture-group byte offsets
// into an integer register file in a single left-to-right pass — no NFA program,
// live-position list, or epsilon-closure at run time. Each config that is live
// in a state owns a block of the register file; a transition sets a block's slot
// to the current position when a group boundary is crossed, or copies it from
// the source config's block. At end of input the winning config's block holds
// the capture offsets. The slice layout matches
// regexp.Regexp.FindStringSubmatchIndex: pair (2*g, 2*g+1) is group g's
// [start, end) byte offsets, index 0 is the whole match, and a group that did
// not participate is (-1, -1). It allocates only the result slice and is safe
// for concurrent use (all state is local).
func numbersPat7FindIndex(input string) []int {
	var reg [42]int
	for i := range reg {
		reg[i] = -1
	}
	reg[2] = 0
	reg[8] = 0
	reg[14] = 0
	reg[20] = 0
	reg[26] = 0
	reg[32] = 0
	reg[38] = 0
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return nil
		}
		np := i + size
		switch state {
		case 0:
			switch {
			case r == 'D': reg[2] = reg[38]; reg[3] = reg[39]; reg[4] = reg[40]; reg[5] = reg[41]; state = 1
			case r == 'E': reg[2] = reg[20]; reg[3] = reg[21]; reg[4] = reg[22]; reg[5] = reg[23]; state = 2
			case r == 'F': reg[2] = reg[8]; reg[3] = reg[9]; reg[4] = reg[10]; reg[5] = reg[11]; state = 3
			case r == 'N': reg[2] = reg[26]; reg[3] = reg[27]; reg[4] = reg[28]; reg[5] = reg[29]; state = 4
			case r == 'S': reg[2] = reg[14]; reg[3] = reg[15]; reg[4] = reg[16]; reg[5] = reg[17]; reg[8] = reg[14]; reg[9] = reg[15]; reg[10] = reg[16]; reg[11] = reg[17]; state = 5
			case r == 'T': reg[8] = reg[2]; reg[9] = reg[3]; reg[10] = reg[4]; reg[11] = reg[5]; reg[14] = reg[32]; reg[15] = reg[33]; reg[16] = reg[34]; reg[17] = reg[35]; state = 6
			case r == 'd': reg[2] = reg[38]; reg[3] = reg[39]; reg[4] = reg[40]; reg[5] = reg[41]; state = 1
			case r == 'e': reg[2] = reg[20]; reg[3] = reg[21]; reg[4] = reg[22]; reg[5] = reg[23]; state = 2
			case r == 'f': reg[2] = reg[8]; reg[3] = reg[9]; reg[4] = reg[10]; reg[5] = reg[11]; state = 3
			case r == 'n': reg[2] = reg[26]; reg[3] = reg[27]; reg[4] = reg[28]; reg[5] = reg[29]; state = 4
			case r == 's': reg[2] = reg[14]; reg[3] = reg[15]; reg[4] = reg[16]; reg[5] = reg[17]; reg[8] = reg[14]; reg[9] = reg[15]; reg[10] = reg[16]; reg[11] = reg[17]; state = 5
			case r == 't': reg[8] = reg[2]; reg[9] = reg[3]; reg[10] = reg[4]; reg[11] = reg[5]; reg[14] = reg[32]; reg[15] = reg[33]; reg[16] = reg[34]; reg[17] = reg[35]; state = 6
			case r == 'ſ': reg[2] = reg[14]; reg[3] = reg[15]; reg[4] = reg[16]; reg[5] = reg[17]; reg[8] = reg[14]; reg[9] = reg[15]; reg[10] = reg[16]; reg[11] = reg[17]; state = 5
			default:
				return nil
			}
		case 1:
			switch {
			case r == 'O': state = 7
			case r == 'o': state = 7
			default:
				return nil
			}
		case 2:
			switch {
			case r == 'I': state = 8
			case r == 'i': state = 8
			default:
				return nil
			}
		case 3:
			switch {
			case r == 'I': reg[2] = reg[8]; reg[3] = reg[9]; reg[4] = reg[10]; reg[5] = reg[11]; state = 9
			case r == 'O': state = 10
			case r == 'i': reg[2] = reg[8]; reg[3] = reg[9]; reg[4] = reg[10]; reg[5] = reg[11]; state = 9
			case r == 'o': state = 10
			default:
				return nil
			}
		case 4:
			switch {
			case r == 'I': state = 11
			case r == 'i': state = 11
			default:
				return nil
			}
		case 5:
			switch {
			case r == 'E': reg[2] = reg[8]; reg[3] = reg[9]; reg[4] = reg[10]; reg[5] = reg[11]; state = 12
			case r == 'I': state = 13
			case r == 'e': reg[2] = reg[8]; reg[3] = reg[9]; reg[4] = reg[10]; reg[5] = reg[11]; state = 12
			case r == 'i': state = 13
			default:
				return nil
			}
		case 6:
			switch {
			case r == 'E': reg[2] = reg[14]; reg[3] = reg[15]; reg[4] = reg[16]; reg[5] = reg[17]; state = 14
			case r == 'H': reg[2] = reg[8]; reg[3] = reg[9]; reg[4] = reg[10]; reg[5] = reg[11]; state = 15
			case r == 'W': state = 16
			case r == 'e': reg[2] = reg[14]; reg[3] = reg[15]; reg[4] = reg[16]; reg[5] = reg[17]; state = 14
			case r == 'h': reg[2] = reg[8]; reg[3] = reg[9]; reg[4] = reg[10]; reg[5] = reg[11]; state = 15
			case r == 'w': state = 16
			default:
				return nil
			}
		case 7:
			switch {
			case r == 'Z': state = 17
			case r == 'z': state = 17
			default:
				return nil
			}
		case 8:
			switch {
			case r == 'G': state = 18
			case r == 'g': state = 18
			default:
				return nil
			}
		case 9:
			switch {
			case r == 'V': state = 19
			case r == 'v': state = 19
			default:
				return nil
			}
		case 10:
			switch {
			case r == 'U': state = 20
			case r == 'u': state = 20
			default:
				return nil
			}
		case 11:
			switch {
			case r == 'N': state = 21
			case r == 'n': state = 21
			default:
				return nil
			}
		case 12:
			switch {
			case r == 'V': state = 22
			case r == 'v': state = 22
			default:
				return nil
			}
		case 13:
			switch {
			case r == 'X': state = 23
			case r == 'x': state = 23
			default:
				return nil
			}
		case 14:
			switch {
			case r == 'N': state = 23
			case r == 'n': state = 23
			default:
				return nil
			}
		case 15:
			switch {
			case r == 'R': state = 24
			case r == 'r': state = 24
			default:
				return nil
			}
		case 16:
			switch {
			case r == 'O': state = 23
			case r == 'o': state = 23
			default:
				return nil
			}
		case 17:
			switch {
			case r == 'E': state = 25
			case r == 'e': state = 25
			default:
				return nil
			}
		case 18:
			switch {
			case r == 'H': state = 26
			case r == 'h': state = 26
			default:
				return nil
			}
		case 19:
			switch {
			case r == 'E': state = 23
			case r == 'e': state = 23
			default:
				return nil
			}
		case 20:
			switch {
			case r == 'R': state = 23
			case r == 'r': state = 23
			default:
				return nil
			}
		case 21:
			switch {
			case r == 'E': state = 23
			case r == 'e': state = 23
			default:
				return nil
			}
		case 22:
			switch {
			case r == 'E': state = 27
			case r == 'e': state = 27
			default:
				return nil
			}
		case 23:
			switch {
			case match.InRange(r, '\t', '\n'): reg[10] = np; reg[8] = reg[2]; reg[9] = reg[3]; reg[11] = reg[5]; state = 28
			case match.InRange(r, '\f', '\r'): reg[10] = np; reg[8] = reg[2]; reg[9] = reg[3]; reg[11] = reg[5]; state = 28
			case r == ' ': reg[10] = np; reg[8] = reg[2]; reg[9] = reg[3]; reg[11] = reg[5]; state = 28
			default:
				return nil
			}
		case 24:
			switch {
			case r == 'E': state = 29
			case r == 'e': state = 29
			default:
				return nil
			}
		case 25:
			switch {
			case r == 'N': state = 23
			case r == 'n': state = 23
			default:
				return nil
			}
		case 26:
			switch {
			case r == 'T': state = 23
			case r == 't': state = 23
			default:
				return nil
			}
		case 27:
			switch {
			case r == 'N': state = 23
			case r == 'n': state = 23
			default:
				return nil
			}
		case 28:
			switch {
			case match.InRange(r, '\t', '\n'): reg[10] = np; reg[8] = reg[2]; reg[9] = reg[3]; reg[11] = reg[5]; state = 28
			case match.InRange(r, '\f', '\r'): reg[10] = np; reg[8] = reg[2]; reg[9] = reg[3]; reg[11] = reg[5]; state = 28
			case r == ' ': reg[10] = np; reg[8] = reg[2]; reg[9] = reg[3]; reg[11] = reg[5]; state = 28
			case match.InRange(r, 'A', 'Z'): reg[3] = np; reg[5] = np; reg[9] = np; reg[11] = np; reg[2] = reg[8]; reg[4] = reg[10]; state = 30
			case match.InRange(r, 'a', 'z'): reg[3] = np; reg[5] = np; reg[9] = np; reg[11] = np; reg[2] = reg[8]; reg[4] = reg[10]; state = 30
			case r == 'ſ': reg[3] = np; reg[5] = np; reg[9] = np; reg[11] = np; reg[2] = reg[8]; reg[4] = reg[10]; state = 30
			case r == 'K': reg[3] = np; reg[5] = np; reg[9] = np; reg[11] = np; reg[2] = reg[8]; reg[4] = reg[10]; state = 30
			default:
				return nil
			}
		case 29:
			switch {
			case r == 'E': state = 23
			case r == 'e': state = 23
			default:
				return nil
			}
		case 30:
			if !(match.InRange(r, '\x00', '\U0010ffff')) { return nil }
			reg[8] = reg[2]; reg[9] = reg[3]; reg[10] = reg[4]; reg[11] = reg[5]; state = 30
		default:
			return nil
		}
		i += size
	}
	switch state {
	case 30:
		result := make([]int, 6)
		result[0] = 0
		result[1] = len(input)
		copy(result[2:], reg[8:12])
		return result
	default:
		return nil
	}
}

// numbersPat7Find returns captured groups for the regex `(?s)((?i)(?:two|three|four|five|six|seven|eight|nine|ten|dozen)\s+([a-z]))(?s:.*)`.
// Returns nil if the input does not match. Index 0 is the entire match,
// indices 1..N are capture groups. A group that did not participate in the
// match yields "" (parity with regexp.Regexp.FindStringSubmatch); use
// numbersPat7FindIndex to distinguish an absent group (offset pair -1) from an
// empty one.
func numbersPat7Find(input string) []string {
	idx := numbersPat7FindIndex(input)
	if idx == nil {
		return nil
	}
	result := make([]string, 3)
	for g := 0; g < 3; g++ {
		s, e := idx[g*2], idx[g*2+1]
		if s >= 0 && e >= 0 && s <= len(input) && e <= len(input) {
			result[g] = input[s:e]
		}
	}
	return result
}

// numbersPat7Names returns the names of the capture groups for the regex
// `(?s)((?i)(?:two|three|four|five|six|seven|eight|nine|ten|dozen)\s+([a-z]))(?s:.*)`. The slice has one entry per group index: index 0 (the
// whole match) is always "", and an unnamed group is "". This is parity with
// regexp.Regexp.SubexpNames.
func numbersPat7Names() []string {
	return []string{"", "", ""}
}

