// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: `(?i)second,\s+`

package commentfix


import "github.com/wow-look-at-my/go-regex-compiler/match"



import "unicode/utf8"

// numbersPat1Has reports whether any substring of input matches the regex `(?i)second,\s+`.
func numbersPat1Has(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		// Invalid UTF-8 decodes as (RuneError, 1) and is matched as U+FFFD,
		// exactly like regexp: each bad byte is one U+FFFD rune.
		r, size := utf8.DecodeRuneInString(input[i:])
		switch state {

		case 0:
			switch {
			case r == 'S', r == 's', r == 'ſ': state = 1
			default: state = 0
			}
		case 1:
			switch {
			case r == 'E': state = 2
			case r == 'S': state = 1
			case r == 'e': state = 2
			case r == 's', r == 'ſ': state = 1
			default: state = 0
			}
		case 2:
			switch {
			case r == 'C': state = 3
			case r == 'S': state = 1
			case r == 'c': state = 3
			case r == 's', r == 'ſ': state = 1
			default: state = 0
			}
		case 3:
			switch {
			case r == 'O': state = 4
			case r == 'S': state = 1
			case r == 'o': state = 4
			case r == 's', r == 'ſ': state = 1
			default: state = 0
			}
		case 4:
			switch {
			case r == 'N': state = 5
			case r == 'S': state = 1
			case r == 'n': state = 5
			case r == 's', r == 'ſ': state = 1
			default: state = 0
			}
		case 5:
			switch {
			case r == 'D': state = 6
			case r == 'S': state = 1
			case r == 'd': state = 6
			case r == 's', r == 'ſ': state = 1
			default: state = 0
			}
		case 6:
			switch {
			case r == ',': state = 7
			case r == 'S', r == 's', r == 'ſ': state = 1
			default: state = 0
			}
		case 7:
			switch {
			case match.InRange(r, '\t', '\n'), match.InRange(r, '\f', '\r'), r == ' ': return true
			case r == 'S', r == 's', r == 'ſ': state = 1
			default: state = 0
			}
		default:
			state = 0
		}
		i += size
	}

	return false
}
