// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: `(?i)the second`

package commentfix




import "unicode/utf8"

// numbersPat4Has reports whether any substring of input matches the regex `(?i)the second`.
func numbersPat4Has(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		// Invalid UTF-8 decodes as (RuneError, 1) and is matched as U+FFFD,
		// exactly like regexp: each bad byte is one U+FFFD rune.
		r, size := utf8.DecodeRuneInString(input[i:])
		switch state {

		case 0:
			switch {
			case r == 'T', r == 't': state = 1
			default: state = 0
			}
		case 1:
			switch {
			case r == 'H': state = 2
			case r == 'T': state = 1
			case r == 'h': state = 2
			case r == 't': state = 1
			default: state = 0
			}
		case 2:
			switch {
			case r == 'E': state = 3
			case r == 'T': state = 1
			case r == 'e': state = 3
			case r == 't': state = 1
			default: state = 0
			}
		case 3:
			switch {
			case r == ' ': state = 4
			case r == 'T', r == 't': state = 1
			default: state = 0
			}
		case 4:
			switch {
			case r == 'S': state = 5
			case r == 'T': state = 1
			case r == 's': state = 5
			case r == 't': state = 1
			case r == 'ſ': state = 5
			default: state = 0
			}
		case 5:
			switch {
			case r == 'E': state = 6
			case r == 'T': state = 1
			case r == 'e': state = 6
			case r == 't': state = 1
			default: state = 0
			}
		case 6:
			switch {
			case r == 'C': state = 7
			case r == 'T': state = 1
			case r == 'c': state = 7
			case r == 't': state = 1
			default: state = 0
			}
		case 7:
			switch {
			case r == 'O': state = 8
			case r == 'T': state = 1
			case r == 'o': state = 8
			case r == 't': state = 1
			default: state = 0
			}
		case 8:
			switch {
			case r == 'N': state = 9
			case r == 'T': state = 1
			case r == 'n': state = 9
			case r == 't': state = 1
			default: state = 0
			}
		case 9:
			switch {
			case r == 'D': return true
			case r == 'T': state = 1
			case r == 'd': return true
			case r == 't': state = 1
			default: state = 0
			}
		default:
			state = 0
		}
		i += size
	}

	return false
}
