// Code generated by cmd/rulegen from ../rules. DO NOT EDIT.

package commentfix

import "github.com/wow-look-at-my/slopfix/table"

// numbersTable is what rules/ says for="numbers", in file name order.
var numbersTable = table.Table{
	Drops: []table.Drop{
	},
	Rewrites: []table.Rewrite{
		{ID: "first-in-first-out", From: "first-in-first-out", To: "FIFO", Where: "", Tests: []table.Test{{In: "A first-in-first-out queue", Out: "A FIFO queue"}}},
		{ID: "first-in-first-out-2", From: "first in, first out", To: "FIFO", Where: "", Tests: []table.Test{{In: "It is first in, first out", Out: "It is FIFO"}}},
		{ID: "last-in-first-out", From: "last-in-first-out", To: "LIFO", Where: "", Tests: []table.Test{{In: "A last-in-first-out stack", Out: "A LIFO stack"}}},
		{ID: "last-in-first-out-2", From: "last in, first out", To: "LIFO", Where: "", Tests: []table.Test{{In: "It is last in, first out", Out: "It is LIFO"}}},
		{ID: "one-another", From: "one another", To: "each other", Where: "", Tests: []table.Test{{In: "They wait for one another", Out: "They wait for each other"}}},
		{ID: "another-one", From: "another one", To: "another", Where: "", Tests: []table.Test{{In: "It cannot block another one", Out: "It cannot block another"}}},
		{ID: "no-one", From: "no one", To: "nobody", Where: "", Tests: []table.Test{{In: "No one reads it", Out: "Nobody reads it"}}},
		{ID: "all-at-once", From: "all at once", To: "together", Where: "", Tests: []table.Test{{In: "It releases all at once", Out: "It releases together"}}},
		{ID: "at-once", From: "at once", To: "at the same time", Where: "", Tests: []table.Test{{In: "Both run at once", Out: "Both run at the same time"}}},
		{ID: "either-one", From: "either one", To: "either", Where: "", Tests: []table.Test{{In: "It cannot fix either one", Out: "It cannot fix either"}}},
		{ID: "each-one", From: "each one", To: "each", Where: "", Tests: []table.Test{{In: "It reads each one", Out: "It reads each"}}},
		{ID: "this-one", From: "this one", To: "this", Where: "", Tests: []table.Test{{In: "It skips this one", Out: "It skips this"}}},
		{ID: "that-one", From: "that one", To: "that", Where: "", Tests: []table.Test{{In: "It skips that one", Out: "It skips that"}}},
		{ID: "one-or-more", From: "one or more", To: "any number of", Where: "", Tests: []table.Test{{In: "It inserts one or more elements", Out: "It inserts any number of elements"}}},
		{ID: "every-one-of", From: "every one of", To: "each of", Where: "", Tests: []table.Test{{In: "It holds every one of the keys", Out: "It holds each of the keys"}}},
		{ID: "at-least-one-of", From: "at least one of", To: "any of", Where: "", Tests: []table.Test{{In: "It holds at least one of the keys", Out: "It holds any of the keys"}}},
		{ID: "exactly-one-of", From: "exactly one of", To: "a single side of", Where: "", Tests: []table.Test{{In: "It is in exactly one of the sets", Out: "It is in a single side of the sets"}}},
		{ID: "one-of", From: "one of", To: "any of", Where: "", Tests: []table.Test{{In: "It is one of the keys", Out: "It is any of the keys"}}},
		{ID: "the-other-two", From: "the other two", To: "the others", Where: "", Tests: []table.Test{{In: "The other two run a loop", Out: "The others run a loop"}}},
		{ID: "the-two", From: "the two", To: "both", Where: "", Tests: []table.Test{{In: "The two agree", Out: "Both agree"}}},
		{ID: "all-three", From: "all three", To: "each of them", Where: "", Tests: []table.Test{{In: "All three agree", Out: "Each of them agree"}}},
		{ID: "the-three", From: "the three", To: "each", Where: "", Tests: []table.Test{{In: "The three agree", Out: "Each agree"}}},
		{ID: "exactly-once", From: "exactly once", To: "exactly a single time", Where: "", Tests: []table.Test{{In: "It runs exactly once", Out: "It runs exactly a single time"}}},
		{ID: "only-once", From: "only once", To: "a single time", Where: "", Tests: []table.Test{{In: "It runs only once", Out: "It runs a single time"}}},
		{ID: "once", From: "once", To: "a single time", Where: "", Tests: []table.Test{{In: "It hashes once", Out: "It hashes a single time"}}},
		{ID: "twice", From: "twice", To: "again", Where: "", Tests: []table.Test{{In: "It hashes the key twice", Out: "It hashes the key again"}}},
		{ID: "the-zero-value", From: "the zero value", To: "an unset value", Where: "", Tests: []table.Test{{In: "The zero value is ready", Out: "An unset value is ready"}}},
		{ID: "zero-value", From: "zero value", To: "unset value", Where: "", Tests: []table.Test{{In: "Its zero value is ready", Out: "Its unset value is ready"}}},
		{ID: "zero", From: "zero", To: "empty", Where: "", Tests: []table.Test{{In: "It returns zero and false", Out: "It returns empty and false"}}},
	},
	Patterns: []table.Pattern{
		{
			ID: "i-bfirst-s", Match: "(?i)\\bfirst,\\s+", To: "", Where: "",
			Tests: []table.Test{{In: "First, it locks", Out: "It locks"}},
			Has: numbersPat0Has, At: numbersPat0At, Find: numbersPat0FindIndex,
			LeadWord: true, TailWord: false,
		},
		{
			ID: "i-bsecond-s", Match: "(?i)\\bsecond,\\s+", To: "then ", Where: "",
			Tests: []table.Test{{In: "Second, it writes", Out: "Then it writes"}},
			Has: numbersPat1Has, At: numbersPat1At, Find: numbersPat1FindIndex,
			LeadWord: true, TailWord: false,
		},
		{
			ID: "i-bthird-s", Match: "(?i)\\bthird,\\s+", To: "then ", Where: "",
			Tests: []table.Test{{In: "Third, it unlocks", Out: "Then it unlocks"}},
			Has: numbersPat2Has, At: numbersPat2At, Find: numbersPat2FindIndex,
			LeadWord: true, TailWord: false,
		},
		{
			ID: "i-ba-second-b", Match: "(?i)\\ba second\\b", To: "another", Where: "",
			Tests: []table.Test{{In: "It grows a second segment", Out: "It grows another segment"}},
			Has: numbersPat3Has, At: numbersPat3At, Find: numbersPat3FindIndex,
			LeadWord: true, TailWord: true,
		},
		{
			ID: "i-bthe-second-b", Match: "(?i)\\bthe second\\b", To: "the next", Where: "",
			Tests: []table.Test{{In: "The second call wins", Out: "The next call wins"}},
			Has: numbersPat4Has, At: numbersPat4At, Find: numbersPat4FindIndex,
			LeadWord: true, TailWord: true,
		},
		{
			ID: "i-bthe-first-b", Match: "(?i)\\bthe first\\b", To: "the earliest", Where: "",
			Tests: []table.Test{{In: "The first writer wins", Out: "The earliest writer wins"}},
			Has: numbersPat5Has, At: numbersPat5At, Find: numbersPat5FindIndex,
			LeadWord: true, TailWord: true,
		},
		{
			ID: "i-bfirst-b", Match: "(?i)\\bfirst\\b", To: "earliest", Where: "",
			Tests: []table.Test{{In: "It takes first", Out: "It takes earliest"}},
			Has: numbersPat6Has, At: numbersPat6At, Find: numbersPat6FindIndex,
			LeadWord: true, TailWord: true,
		},
		{
			ID: "plural-tally-drops-its-count", Match: "(?i)\\b(?:two|three|four|five|six|seven|eight|nine|ten|dozen)\\s+([a-z])", To: "${1}", Where: "",
			Tests: []table.Test{{In: "Two goroutines contend", Out: "Goroutines contend"}},
			Has: numbersPat7Has, At: numbersPat7At, Find: numbersPat7FindIndex,
			LeadWord: true, TailWord: false,
		},
	},
	Flags: []table.Flag{
	},
	Classes: []table.Class{
		{Name: "article", Words: []string{"a", "an", "the"}, Suffix: nil, Open: false, Except: nil},
		{Name: "determiner", Words: []string{"this", "that", "these", "those", "each", "every", "any", "no", "some", "another", "other", "which", "whichever", "either", "neither", "both", "several", "many", "few", "all", "its", "their", "our", "my", "your", "his", "her", "whose"}, Suffix: nil, Open: false, Except: nil},
		{Name: "relative", Words: []string{"that", "which", "who", "whom", "whose", "when", "where", "while"}, Suffix: nil, Open: false, Except: nil},
		{Name: "conjunction", Words: []string{"and", "or", "but", "so", "because", "though", "although", "if", "unless", "since", "while", "whereas"}, Suffix: nil, Open: false, Except: nil},
		{Name: "preposition", Words: []string{"of", "in", "on", "at", "to", "for", "with", "from", "by", "into", "onto", "under", "over", "per", "as", "than", "through", "against", "between", "among", "about", "after", "before", "during", "without", "within", "across", "below", "above", "behind", "beside", "beyond", "near", "upon", "until", "toward", "towards", "along", "around", "via", "despite", "versus", "off", "out", "up", "down"}, Suffix: nil, Open: false, Except: nil},
		{Name: "auxiliary", Words: []string{"is", "are", "was", "were", "be", "been", "being", "am", "has", "have", "had", "does", "do", "did", "can", "could", "will", "would", "shall", "may", "might", "must", "should"}, Suffix: nil, Open: false, Except: nil},
		{Name: "adverb", Words: []string{"still", "already", "only", "never", "always", "also", "too", "here", "there", "now", "then", "again", "once", "twice", "rather", "quite", "very", "just", "even", "soon", "later", "instead", "however", "therefore"}, Suffix: nil, Open: false, Except: nil},
		{Name: "pronoun", Words: []string{"it", "they", "them", "we", "us", "you", "he", "him", "she", "something", "anything", "nothing", "everything"}, Suffix: nil, Open: false, Except: nil},
		{Name: "verbform", Words: nil, Suffix: []string{"ing", "ed"}, Open: false, Except: nil},
		{Name: "noun", Words: nil, Suffix: nil, Open: true, Except: []string{"verbform"}},
		{Name: "cardinal", Words: []string{"zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "dozen", "hundred", "thousand", "million"}, Suffix: nil, Open: false, Except: nil},
	},
	Normals: []table.Normalize{
	},
	Rephrasings: []table.Rephrase{
		{
			ID: "at-least-one", Match: "at least one", To: "any", Where: "",
			Tests: []table.Test{{In: "It holds at least one key", Out: "It holds any key"}},
			Terms: table.Match{Terms: []table.Term{{Classes: nil, Word: "at", Name: "", Many: false}, {Classes: nil, Word: "least", Name: "", Many: false}, {Classes: nil, Word: "one", Name: "", Many: false}}},
		},
		{
			ID: "at-most-one", Match: "at most one", To: "no more than a single", Where: "",
			Tests: []table.Test{{In: "It holds at most one key", Out: "It holds no more than a single key"}},
			Terms: table.Match{Terms: []table.Term{{Classes: nil, Word: "at", Name: "", Many: false}, {Classes: nil, Word: "most", Name: "", Many: false}, {Classes: nil, Word: "one", Name: "", Many: false}}},
		},
		{
			ID: "only-one", Match: "only one", To: "a single", Where: "",
			Tests: []table.Test{{In: "It holds only one key", Out: "It holds a single key"}},
			Terms: table.Match{Terms: []table.Term{{Classes: nil, Word: "only", Name: "", Many: false}, {Classes: nil, Word: "one", Name: "", Many: false}}},
		},
		{
			ID: "no-one-is-nobody", Match: "no one", To: "nobody", Where: "",
			Tests: []table.Test{{In: "No one reads it", Out: "Nobody reads it"}},
			Terms: table.Match{Terms: []table.Term{{Classes: nil, Word: "no", Name: "", Many: false}, {Classes: nil, Word: "one", Name: "", Many: false}}},
		},
		{
			ID: "a-governed-one-counts-its-noun", Match: "{article|determiner:d} one {noun:n}", To: "{d} single {n}", Where: "",
			Tests: []table.Test{{In: "It holds the one key", Out: "It holds the single key"}},
			Terms: table.Match{Terms: []table.Term{{Classes: []string{"article", "determiner"}, Word: "", Name: "d", Many: false}, {Classes: nil, Word: "one", Name: "", Many: false}, {Classes: []string{"noun"}, Word: "", Name: "n", Many: false}}},
		},
		{
			ID: "one-counts-a-noun", Match: "one {noun:n}", To: "a single {n}", Where: "",
			Tests: []table.Test{{In: "It reserves one slot", Out: "It reserves a single slot"}},
			Terms: table.Match{Terms: []table.Term{{Classes: nil, Word: "one", Name: "", Many: false}, {Classes: []string{"noun"}, Word: "", Name: "n", Many: false}}},
		},
	},
}
