// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: `(?i)third,\s+`

package commentfix


import "github.com/wow-look-at-my/go-regex-compiler/match"



// numbersPat2Has reports whether any substring of input matches the regex `(?i)third,\s+`.
func numbersPat2Has(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {

		case 0:
			switch {
			case c == 'T', c == 't': state = 1
			default: state = 0
			}
		case 1:
			switch {
			case c == 'H': state = 2
			case c == 'T': state = 1
			case c == 'h': state = 2
			case c == 't': state = 1
			default: state = 0
			}
		case 2:
			switch {
			case c == 'I': state = 3
			case c == 'T': state = 1
			case c == 'i': state = 3
			case c == 't': state = 1
			default: state = 0
			}
		case 3:
			switch {
			case c == 'R': state = 4
			case c == 'T': state = 1
			case c == 'r': state = 4
			case c == 't': state = 1
			default: state = 0
			}
		case 4:
			switch {
			case c == 'D': state = 5
			case c == 'T': state = 1
			case c == 'd': state = 5
			case c == 't': state = 1
			default: state = 0
			}
		case 5:
			switch {
			case c == ',': state = 6
			case c == 'T', c == 't': state = 1
			default: state = 0
			}
		case 6:
			switch {
			case match.InRange(c, '\t', '\n'), match.InRange(c, '\f', '\r'), c == ' ': return true
			case c == 'T', c == 't': state = 1
			default: state = 0
			}
		default:
			state = 0
		}
	}

	return false
}
