// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: `(?i)first`

package commentfix




import "unicode/utf8"

// numbersPat6Has reports whether any substring of input matches the regex `(?i)first`.
func numbersPat6Has(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		// Invalid UTF-8 decodes as (RuneError, 1) and is matched as U+FFFD,
		// exactly like regexp: each bad byte is one U+FFFD rune.
		r, size := utf8.DecodeRuneInString(input[i:])
		switch state {

		case 0:
			switch {
			case r == 'F', r == 'f': state = 1
			default: state = 0
			}
		case 1:
			switch {
			case r == 'F': state = 1
			case r == 'I': state = 2
			case r == 'f': state = 1
			case r == 'i': state = 2
			default: state = 0
			}
		case 2:
			switch {
			case r == 'F': state = 1
			case r == 'R': state = 3
			case r == 'f': state = 1
			case r == 'r': state = 3
			default: state = 0
			}
		case 3:
			switch {
			case r == 'F': state = 1
			case r == 'S': state = 4
			case r == 'f': state = 1
			case r == 's', r == 'ſ': state = 4
			default: state = 0
			}
		case 4:
			switch {
			case r == 'F': state = 1
			case r == 'T': return true
			case r == 'f': state = 1
			case r == 't': return true
			default: state = 0
			}
		default:
			state = 0
		}
		i += size
	}

	return false
}
