// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: `(?i)the first`

package commentfix




import "unicode/utf8"

// numbersPat5Has reports whether any substring of input matches the regex `(?i)the first`.
func numbersPat5Has(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		// Invalid UTF-8 decodes as (RuneError, 1) and is matched as U+FFFD,
		// exactly like regexp: each bad byte is one U+FFFD rune.
		r, size := utf8.DecodeRuneInString(input[i:])
		switch state {

		case 0:
			switch {
			case r == 'T', r == 't': state = 1
			default: state = 0
			}
		case 1:
			switch {
			case r == 'H': state = 2
			case r == 'T': state = 1
			case r == 'h': state = 2
			case r == 't': state = 1
			default: state = 0
			}
		case 2:
			switch {
			case r == 'E': state = 3
			case r == 'T': state = 1
			case r == 'e': state = 3
			case r == 't': state = 1
			default: state = 0
			}
		case 3:
			switch {
			case r == ' ': state = 4
			case r == 'T', r == 't': state = 1
			default: state = 0
			}
		case 4:
			switch {
			case r == 'F': state = 5
			case r == 'T': state = 1
			case r == 'f': state = 5
			case r == 't': state = 1
			default: state = 0
			}
		case 5:
			switch {
			case r == 'I': state = 6
			case r == 'T': state = 1
			case r == 'i': state = 6
			case r == 't': state = 1
			default: state = 0
			}
		case 6:
			switch {
			case r == 'R': state = 7
			case r == 'T': state = 1
			case r == 'r': state = 7
			case r == 't': state = 1
			default: state = 0
			}
		case 7:
			switch {
			case r == 'S': state = 8
			case r == 'T': state = 1
			case r == 's': state = 8
			case r == 't': state = 1
			case r == 'ſ': state = 8
			default: state = 0
			}
		case 8:
			switch {
			case r == 'T', r == 't': return true
			default: state = 0
			}
		default:
			state = 0
		}
		i += size
	}

	return false
}
