// Code generated by go-regex-compiler. DO NOT EDIT.
// Source regex: `(?s)((?i)the second)(?s:.*)`

package commentfix


import "github.com/wow-look-at-my/go-regex-compiler/match"



import "unicode/utf8"

// numbersPat4At reports whether input fully matches the regex `(?s)((?i)the second)(?s:.*)`.
func numbersPat4At(input string) bool {
	state := 0
	for i := 0; i < len(input); {
		// Invalid UTF-8 decodes as (RuneError, 1) and is matched as U+FFFD,
		// exactly like regexp: each bad byte is one U+FFFD rune.
		r, size := utf8.DecodeRuneInString(input[i:])
		switch state {

		case 0:
			switch {
			case r == 'T', r == 't': state = 1
			default: return false
			}
		case 1:
			switch {
			case r == 'H', r == 'h': state = 2
			default: return false
			}
		case 2:
			switch {
			case r == 'E', r == 'e': state = 3
			default: return false
			}
		case 3:
			switch {
			case r == ' ': state = 4
			default: return false
			}
		case 4:
			switch {
			case r == 'S', r == 's', r == 'ſ': state = 5
			default: return false
			}
		case 5:
			switch {
			case r == 'E', r == 'e': state = 6
			default: return false
			}
		case 6:
			switch {
			case r == 'C', r == 'c': state = 7
			default: return false
			}
		case 7:
			switch {
			case r == 'O', r == 'o': state = 8
			default: return false
			}
		case 8:
			switch {
			case r == 'N', r == 'n': state = 9
			default: return false
			}
		case 9:
			switch {
			case r == 'D', r == 'd': state = 10
			default: return false
			}
		case 10:
			switch {
			case match.InRange(r, '\x00', '\U0010ffff'): state = 11
			default: return false
			}
		case 11:
			switch {
			case match.InRange(r, '\x00', '\U0010ffff'): state = 11
			default: return false
			}
		default:
			return false
		}
		i += size
	}

	switch state {
	case 10, 11:
		return true
	default:
		return false
	}
}

// numbersPat4FindIndex returns the submatch index slice for the regex `(?s)((?i)the second)(?s:.*)`,
// or nil if the input does not match. It is a COMPILED tagged-DFA register
// machine: a straight-line state machine that records capture-group byte offsets
// into an integer register file in a single left-to-right pass — no NFA program,
// live-position list, or epsilon-closure at run time. Each config that is live
// in a state owns a block of the register file; a transition sets a block's slot
// to the current position when a group boundary is crossed, or copies it from
// the source config's block. At end of input the winning config's block holds
// the capture offsets. The slice layout matches
// regexp.Regexp.FindStringSubmatchIndex: pair (2*g, 2*g+1) is group g's
// [start, end) byte offsets, index 0 is the whole match, and a group that did
// not participate is (-1, -1). It allocates only the result slice and is safe
// for concurrent use (all state is local).
func numbersPat4FindIndex(input string) []int {
	var reg [8]int
	for i := range reg {
		reg[i] = -1
	}
	reg[2] = 0
	state := 0
	for i := 0; i < len(input); {
		r, size := utf8.DecodeRuneInString(input[i:])
		if r == utf8.RuneError && size == 1 {
			return nil
		}
		np := i + size
		switch state {
		case 0:
			switch {
			case r == 'T': state = 1
			case r == 't': state = 1
			default:
				return nil
			}
		case 1:
			switch {
			case r == 'H': state = 2
			case r == 'h': state = 2
			default:
				return nil
			}
		case 2:
			switch {
			case r == 'E': state = 3
			case r == 'e': state = 3
			default:
				return nil
			}
		case 3:
			if r != ' ' { return nil }
			state = 4
		case 4:
			switch {
			case r == 'S': state = 5
			case r == 's': state = 5
			case r == 'ſ': state = 5
			default:
				return nil
			}
		case 5:
			switch {
			case r == 'E': state = 6
			case r == 'e': state = 6
			default:
				return nil
			}
		case 6:
			switch {
			case r == 'C': state = 7
			case r == 'c': state = 7
			default:
				return nil
			}
		case 7:
			switch {
			case r == 'O': state = 8
			case r == 'o': state = 8
			default:
				return nil
			}
		case 8:
			switch {
			case r == 'N': state = 9
			case r == 'n': state = 9
			default:
				return nil
			}
		case 9:
			switch {
			case r == 'D': reg[3] = np; reg[7] = np; reg[6] = reg[2]; state = 10
			case r == 'd': reg[3] = np; reg[7] = np; reg[6] = reg[2]; state = 10
			default:
				return nil
			}
		case 10:
			if !(match.InRange(r, '\x00', '\U0010ffff')) { return nil }
			reg[6] = reg[2]; reg[7] = reg[3]; state = 10
		default:
			return nil
		}
		i += size
	}
	switch state {
	case 10:
		result := make([]int, 4)
		result[0] = 0
		result[1] = len(input)
		copy(result[2:], reg[6:8])
		return result
	default:
		return nil
	}
}

// numbersPat4Find returns captured groups for the regex `(?s)((?i)the second)(?s:.*)`.
// Returns nil if the input does not match. Index 0 is the entire match,
// indices 1..N are capture groups. A group that did not participate in the
// match yields "" (parity with regexp.Regexp.FindStringSubmatch); use
// numbersPat4FindIndex to distinguish an absent group (offset pair -1) from an
// empty one.
func numbersPat4Find(input string) []string {
	idx := numbersPat4FindIndex(input)
	if idx == nil {
		return nil
	}
	result := make([]string, 2)
	for g := 0; g < 2; g++ {
		s, e := idx[g*2], idx[g*2+1]
		if s >= 0 && e >= 0 && s <= len(input) && e <= len(input) {
			result[g] = input[s:e]
		}
	}
	return result
}

// numbersPat4Names returns the names of the capture groups for the regex
// `(?s)((?i)the second)(?s:.*)`. The slice has one entry per group index: index 0 (the
// whole match) is always "", and an unnamed group is "". This is parity with
// regexp.Regexp.SubexpNames.
func numbersPat4Names() []string {
	return []string{"", ""}
}

