// Code generated by ts-translate. DO NOT EDIT.

package golang

import (
	_ "embed"
	"sync"

	ts "github.com/wow-look-at-my/go-tree-sitter"
)

//go:embed tables.zst
var tablesBlob []byte

var characterSets [][]ts.CharacterRange

func tsLex(lexer *ts.Lexer, state ts.StateID) bool {
	result := false
	skip := false
	eof := false
	var lookahead int32
	_, _ = eof, lookahead
	goto start
nextState:
	lexer.Advance(skip)
start:
	skip = false
	lookahead = lexer.Lookahead
	eof = lexer.EOF()
	switch state {
	case 0:
		if eof {
			state = 59
			goto nextState
		}
		switch lookahead {
		case 0:
			state = 62
			goto nextState
		case 33:
			state = 106
			goto nextState
		case 34:
			state = 148
			goto nextState
		case 37:
			state = 115
			goto nextState
		case 38:
			state = 110
			goto nextState
		case 39:
			state = 22
			goto nextState
		case 40:
			state = 66
			goto nextState
		case 41:
			state = 67
			goto nextState
		case 42:
			state = 75
			goto nextState
		case 43:
			state = 100
			goto nextState
		case 44:
			state = 68
			goto nextState
		case 45:
			state = 103
			goto nextState
		case 46:
			state = 65
			goto nextState
		case 47:
			state = 113
			goto nextState
		case 48:
			state = 152
			goto nextState
		case 58:
			state = 98
			goto nextState
		case 59:
			state = 61
			goto nextState
		case 60:
			state = 124
			goto nextState
		case 61:
			state = 70
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 91:
			state = 71
			goto nextState
		case 92:
			state = 20
			goto nextState
		case 93:
			state = 72
			goto nextState
		case 94:
			state = 108
			goto nextState
		case 96:
			state = 135
			goto nextState
		case 123:
			state = 77
			goto nextState
		case 124:
			state = 80
			goto nextState
		case 125:
			state = 78
			goto nextState
		case 126:
			state = 76
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 57
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 154
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 134
			goto nextState
		}
		return result
	case 1:
		switch lookahead {
		case 0:
			state = 62
			goto nextState
		case 10:
			state = 60
			goto nextState
		case 33:
			state = 17
			goto nextState
		case 37:
			state = 114
			goto nextState
		case 38:
			state = 111
			goto nextState
		case 40:
			state = 66
			goto nextState
		case 42:
			state = 74
			goto nextState
		case 43:
			state = 99
			goto nextState
		case 44:
			state = 68
			goto nextState
		case 45:
			state = 102
			goto nextState
		case 46:
			state = 63
			goto nextState
		case 47:
			state = 112
			goto nextState
		case 59:
			state = 61
			goto nextState
		case 60:
			state = 127
			goto nextState
		case 61:
			state = 19
			goto nextState
		case 62:
			state = 130
			goto nextState
		case 91:
			state = 71
			goto nextState
		case 94:
			state = 107
			goto nextState
		case 123:
			state = 77
			goto nextState
		case 124:
			state = 81
			goto nextState
		case 125:
			state = 78
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 1
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 134
			goto nextState
		}
		return result
	case 2:
		if (lookahead == 10) {
			skip = true
			state = 16
			goto nextState
		}
		if (lookahead == 34) {
			state = 148
			goto nextState
		}
		if (lookahead == 47) {
			state = 143
			goto nextState
		}
		if (lookahead == 92) {
			state = 20
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			state = 146
			goto nextState
		}
		if (lookahead != 0) {
			state = 147
			goto nextState
		}
		return result
	case 3:
		switch lookahead {
		case 33:
			state = 17
			goto nextState
		case 34:
			state = 142
			goto nextState
		case 37:
			state = 114
			goto nextState
		case 38:
			state = 111
			goto nextState
		case 40:
			state = 66
			goto nextState
		case 41:
			state = 67
			goto nextState
		case 42:
			state = 74
			goto nextState
		case 43:
			state = 99
			goto nextState
		case 44:
			state = 68
			goto nextState
		case 45:
			state = 102
			goto nextState
		case 46:
			state = 64
			goto nextState
		case 47:
			state = 112
			goto nextState
		case 58:
			state = 98
			goto nextState
		case 60:
			state = 125
			goto nextState
		case 61:
			state = 70
			goto nextState
		case 62:
			state = 130
			goto nextState
		case 91:
			state = 71
			goto nextState
		case 93:
			state = 72
			goto nextState
		case 94:
			state = 107
			goto nextState
		case 96:
			state = 135
			goto nextState
		case 123:
			state = 77
			goto nextState
		case 124:
			state = 81
			goto nextState
		case 126:
			state = 76
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 3
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 134
			goto nextState
		}
		return result
	case 4:
		switch lookahead {
		case 33:
			state = 17
			goto nextState
		case 37:
			state = 115
			goto nextState
		case 38:
			state = 110
			goto nextState
		case 40:
			state = 66
			goto nextState
		case 42:
			state = 75
			goto nextState
		case 43:
			state = 100
			goto nextState
		case 44:
			state = 68
			goto nextState
		case 45:
			state = 103
			goto nextState
		case 46:
			state = 63
			goto nextState
		case 47:
			state = 113
			goto nextState
		case 58:
			state = 18
			goto nextState
		case 59:
			state = 61
			goto nextState
		case 60:
			state = 124
			goto nextState
		case 61:
			state = 70
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 91:
			state = 71
			goto nextState
		case 94:
			state = 108
			goto nextState
		case 123:
			state = 77
			goto nextState
		case 124:
			state = 80
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 4
			goto nextState
		}
		return result
	case 5:
		switch lookahead {
		case 33:
			state = 17
			goto nextState
		case 37:
			state = 115
			goto nextState
		case 38:
			state = 110
			goto nextState
		case 40:
			state = 66
			goto nextState
		case 42:
			state = 75
			goto nextState
		case 43:
			state = 101
			goto nextState
		case 44:
			state = 68
			goto nextState
		case 45:
			state = 104
			goto nextState
		case 46:
			state = 63
			goto nextState
		case 47:
			state = 113
			goto nextState
		case 58:
			state = 18
			goto nextState
		case 60:
			state = 126
			goto nextState
		case 61:
			state = 70
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 91:
			state = 71
			goto nextState
		case 94:
			state = 108
			goto nextState
		case 123:
			state = 77
			goto nextState
		case 124:
			state = 80
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 5
			goto nextState
		}
		return result
	case 6:
		switch lookahead {
		case 33:
			state = 17
			goto nextState
		case 37:
			state = 114
			goto nextState
		case 38:
			state = 111
			goto nextState
		case 40:
			state = 66
			goto nextState
		case 41:
			state = 67
			goto nextState
		case 42:
			state = 74
			goto nextState
		case 43:
			state = 99
			goto nextState
		case 44:
			state = 68
			goto nextState
		case 45:
			state = 102
			goto nextState
		case 46:
			state = 64
			goto nextState
		case 47:
			state = 112
			goto nextState
		case 58:
			state = 98
			goto nextState
		case 59:
			state = 61
			goto nextState
		case 60:
			state = 127
			goto nextState
		case 61:
			state = 70
			goto nextState
		case 62:
			state = 130
			goto nextState
		case 91:
			state = 71
			goto nextState
		case 93:
			state = 72
			goto nextState
		case 94:
			state = 107
			goto nextState
		case 123:
			state = 77
			goto nextState
		case 124:
			state = 81
			goto nextState
		case 125:
			state = 78
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 6
			goto nextState
		}
		return result
	case 7:
		if (lookahead == 39) {
			state = 162
			goto nextState
		}
		return result
	case 8:
		if (lookahead == 42) {
			state = 10
			goto nextState
		}
		if (lookahead == 47) {
			state = 164
			goto nextState
		}
		return result
	case 9:
		if (lookahead == 42) {
			state = 9
			goto nextState
		}
		if (lookahead == 47) {
			state = 163
			goto nextState
		}
		if (lookahead != 0) {
			state = 10
			goto nextState
		}
		return result
	case 10:
		if (lookahead == 42) {
			state = 9
			goto nextState
		}
		if (lookahead != 0) {
			state = 10
			goto nextState
		}
		return result
	case 11:
		if (lookahead == 45) {
			state = 82
			goto nextState
		}
		return result
	case 12:
		if (lookahead == 46) {
			state = 14
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 158
			goto nextState
		}
		return result
	case 13:
		if (lookahead == 46) {
			state = 160
			goto nextState
		}
		if (lookahead == 95) {
			state = 35
			goto nextState
		}
		if (lookahead == 105) {
			state = 161
			goto nextState
		}
		if ((lookahead == 69) || (lookahead == 101)) {
			state = 26
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 13
			goto nextState
		}
		return result
	case 14:
		if (lookahead == 46) {
			state = 73
			goto nextState
		}
		return result
	case 15:
		if (lookahead == 46) {
			state = 40
			goto nextState
		}
		if (lookahead == 95) {
			state = 39
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 155
			goto nextState
		}
		return result
	case 16:
		if (lookahead == 47) {
			state = 8
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 16
			goto nextState
		}
		return result
	case 17:
		if (lookahead == 61) {
			state = 123
			goto nextState
		}
		return result
	case 18:
		if (lookahead == 61) {
			state = 83
			goto nextState
		}
		return result
	case 19:
		if (lookahead == 61) {
			state = 122
			goto nextState
		}
		return result
	case 20:
		if (lookahead == 85) {
			state = 53
			goto nextState
		}
		if (lookahead == 117) {
			state = 45
			goto nextState
		}
		if (lookahead == 120) {
			state = 41
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 151
			goto nextState
		}
		if (lookahead != 0) {
			state = 149
			goto nextState
		}
		return result
	case 21:
		if (lookahead == 85) {
			state = 54
			goto nextState
		}
		if (lookahead == 117) {
			state = 46
			goto nextState
		}
		if (lookahead == 120) {
			state = 42
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 55)) {
			state = 32
			goto nextState
		}
		if ts.SetContains(characterSets[2], lookahead) {
			state = 7
			goto nextState
		}
		return result
	case 22:
		if (lookahead == 92) {
			state = 21
			goto nextState
		}
		if ((lookahead != 0) && (lookahead != 39)) {
			state = 7
			goto nextState
		}
		return result
	case 23:
		if (lookahead == 95) {
			state = 28
			goto nextState
		}
		if ((lookahead == 48) || (lookahead == 49)) {
			state = 156
			goto nextState
		}
		return result
	case 24:
		if (lookahead == 95) {
			state = 40
			goto nextState
		}
		if ((lookahead == 80) || (lookahead == 112)) {
			state = 26
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 24
			goto nextState
		}
		return result
	case 25:
		if (lookahead == 95) {
			state = 31
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 55)) {
			state = 157
			goto nextState
		}
		return result
	case 26:
		if ((lookahead == 43) || (lookahead == 45)) {
			state = 36
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 159
			goto nextState
		}
		return result
	case 27:
		if ((lookahead == 80) || (lookahead == 112)) {
			state = 26
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 24
			goto nextState
		}
		return result
	case 28:
		if ((lookahead == 48) || (lookahead == 49)) {
			state = 156
			goto nextState
		}
		return result
	case 29:
		if ((lookahead == 56) || (lookahead == 57)) {
			state = 13
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 55)) {
			state = 153
			goto nextState
		}
		return result
	case 30:
		if ((48 <= lookahead) && (lookahead <= 55)) {
			state = 7
			goto nextState
		}
		return result
	case 31:
		if ((48 <= lookahead) && (lookahead <= 55)) {
			state = 157
			goto nextState
		}
		return result
	case 32:
		if ((48 <= lookahead) && (lookahead <= 55)) {
			state = 30
			goto nextState
		}
		return result
	case 33:
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 154
			goto nextState
		}
		return result
	case 34:
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 158
			goto nextState
		}
		return result
	case 35:
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 13
			goto nextState
		}
		return result
	case 36:
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 159
			goto nextState
		}
		return result
	case 37:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 7
			goto nextState
		}
		return result
	case 38:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 149
			goto nextState
		}
		return result
	case 39:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 155
			goto nextState
		}
		return result
	case 40:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 24
			goto nextState
		}
		return result
	case 41:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 38
			goto nextState
		}
		return result
	case 42:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 37
			goto nextState
		}
		return result
	case 43:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 41
			goto nextState
		}
		return result
	case 44:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 42
			goto nextState
		}
		return result
	case 45:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 43
			goto nextState
		}
		return result
	case 46:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 44
			goto nextState
		}
		return result
	case 47:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 45
			goto nextState
		}
		return result
	case 48:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 46
			goto nextState
		}
		return result
	case 49:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 47
			goto nextState
		}
		return result
	case 50:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 48
			goto nextState
		}
		return result
	case 51:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 49
			goto nextState
		}
		return result
	case 52:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 50
			goto nextState
		}
		return result
	case 53:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 51
			goto nextState
		}
		return result
	case 54:
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 52
			goto nextState
		}
		return result
	case 55:
		if eof {
			state = 59
			goto nextState
		}
		switch lookahead {
		case 0:
			state = 62
			goto nextState
		case 10:
			state = 60
			goto nextState
		case 33:
			state = 105
			goto nextState
		case 34:
			state = 142
			goto nextState
		case 38:
			state = 109
			goto nextState
		case 39:
			state = 22
			goto nextState
		case 40:
			state = 66
			goto nextState
		case 41:
			state = 67
			goto nextState
		case 42:
			state = 74
			goto nextState
		case 43:
			state = 99
			goto nextState
		case 44:
			state = 68
			goto nextState
		case 45:
			state = 102
			goto nextState
		case 46:
			state = 34
			goto nextState
		case 47:
			state = 8
			goto nextState
		case 48:
			state = 152
			goto nextState
		case 59:
			state = 61
			goto nextState
		case 60:
			state = 11
			goto nextState
		case 61:
			state = 69
			goto nextState
		case 91:
			state = 71
			goto nextState
		case 94:
			state = 107
			goto nextState
		case 96:
			state = 135
			goto nextState
		case 123:
			state = 77
			goto nextState
		case 124:
			state = 79
			goto nextState
		case 125:
			state = 78
			goto nextState
		case 126:
			state = 76
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 55
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 154
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 134
			goto nextState
		}
		return result
	case 56:
		if eof {
			state = 59
			goto nextState
		}
		switch lookahead {
		case 0:
			state = 62
			goto nextState
		case 10:
			state = 60
			goto nextState
		case 33:
			state = 17
			goto nextState
		case 34:
			state = 142
			goto nextState
		case 37:
			state = 115
			goto nextState
		case 38:
			state = 110
			goto nextState
		case 40:
			state = 66
			goto nextState
		case 41:
			state = 67
			goto nextState
		case 42:
			state = 75
			goto nextState
		case 43:
			state = 100
			goto nextState
		case 44:
			state = 68
			goto nextState
		case 45:
			state = 103
			goto nextState
		case 46:
			state = 63
			goto nextState
		case 47:
			state = 113
			goto nextState
		case 58:
			state = 98
			goto nextState
		case 59:
			state = 61
			goto nextState
		case 60:
			state = 124
			goto nextState
		case 61:
			state = 70
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 91:
			state = 71
			goto nextState
		case 94:
			state = 108
			goto nextState
		case 96:
			state = 135
			goto nextState
		case 123:
			state = 77
			goto nextState
		case 124:
			state = 80
			goto nextState
		case 125:
			state = 78
			goto nextState
		case 126:
			state = 76
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 56
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 134
			goto nextState
		}
		return result
	case 57:
		if eof {
			state = 59
			goto nextState
		}
		switch lookahead {
		case 0:
			state = 62
			goto nextState
		case 33:
			state = 106
			goto nextState
		case 34:
			state = 142
			goto nextState
		case 37:
			state = 115
			goto nextState
		case 38:
			state = 110
			goto nextState
		case 39:
			state = 22
			goto nextState
		case 40:
			state = 66
			goto nextState
		case 41:
			state = 67
			goto nextState
		case 42:
			state = 75
			goto nextState
		case 43:
			state = 100
			goto nextState
		case 44:
			state = 68
			goto nextState
		case 45:
			state = 103
			goto nextState
		case 46:
			state = 65
			goto nextState
		case 47:
			state = 113
			goto nextState
		case 48:
			state = 152
			goto nextState
		case 58:
			state = 98
			goto nextState
		case 59:
			state = 61
			goto nextState
		case 60:
			state = 124
			goto nextState
		case 61:
			state = 70
			goto nextState
		case 62:
			state = 129
			goto nextState
		case 91:
			state = 71
			goto nextState
		case 93:
			state = 72
			goto nextState
		case 94:
			state = 108
			goto nextState
		case 96:
			state = 135
			goto nextState
		case 123:
			state = 77
			goto nextState
		case 124:
			state = 80
			goto nextState
		case 125:
			state = 78
			goto nextState
		case 126:
			state = 76
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 57
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 154
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 134
			goto nextState
		}
		return result
	case 58:
		if eof {
			state = 59
			goto nextState
		}
		switch lookahead {
		case 33:
			state = 105
			goto nextState
		case 34:
			state = 142
			goto nextState
		case 38:
			state = 109
			goto nextState
		case 39:
			state = 22
			goto nextState
		case 40:
			state = 66
			goto nextState
		case 41:
			state = 67
			goto nextState
		case 42:
			state = 74
			goto nextState
		case 43:
			state = 99
			goto nextState
		case 44:
			state = 68
			goto nextState
		case 45:
			state = 102
			goto nextState
		case 46:
			state = 12
			goto nextState
		case 47:
			state = 8
			goto nextState
		case 48:
			state = 152
			goto nextState
		case 58:
			state = 97
			goto nextState
		case 59:
			state = 61
			goto nextState
		case 60:
			state = 11
			goto nextState
		case 91:
			state = 71
			goto nextState
		case 93:
			state = 72
			goto nextState
		case 94:
			state = 107
			goto nextState
		case 96:
			state = 135
			goto nextState
		case 123:
			state = 77
			goto nextState
		case 125:
			state = 78
			goto nextState
		case 126:
			state = 76
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 58
			goto nextState
		}
		if ((49 <= lookahead) && (lookahead <= 57)) {
			state = 154
			goto nextState
		}
		if ts.SetContains(characterSets[0], lookahead) {
			state = 134
			goto nextState
		}
		return result
	case 59:
		result = true
		lexer.ResultSymbol = 0
		lexer.MarkEnd()
		return result
	case 60:
		result = true
		lexer.ResultSymbol = 2
		lexer.MarkEnd()
		if (lookahead == 10) {
			state = 60
			goto nextState
		}
		return result
	case 61:
		result = true
		lexer.ResultSymbol = 3
		lexer.MarkEnd()
		return result
	case 62:
		result = true
		lexer.ResultSymbol = 4
		lexer.MarkEnd()
		return result
	case 63:
		result = true
		lexer.ResultSymbol = 7
		lexer.MarkEnd()
		return result
	case 64:
		result = true
		lexer.ResultSymbol = 7
		lexer.MarkEnd()
		if (lookahead == 46) {
			state = 14
			goto nextState
		}
		return result
	case 65:
		result = true
		lexer.ResultSymbol = 7
		lexer.MarkEnd()
		if (lookahead == 46) {
			state = 14
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 158
			goto nextState
		}
		return result
	case 66:
		result = true
		lexer.ResultSymbol = 9
		lexer.MarkEnd()
		return result
	case 67:
		result = true
		lexer.ResultSymbol = 10
		lexer.MarkEnd()
		return result
	case 68:
		result = true
		lexer.ResultSymbol = 12
		lexer.MarkEnd()
		return result
	case 69:
		result = true
		lexer.ResultSymbol = 13
		lexer.MarkEnd()
		return result
	case 70:
		result = true
		lexer.ResultSymbol = 13
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 122
			goto nextState
		}
		return result
	case 71:
		result = true
		lexer.ResultSymbol = 16
		lexer.MarkEnd()
		return result
	case 72:
		result = true
		lexer.ResultSymbol = 17
		lexer.MarkEnd()
		return result
	case 73:
		result = true
		lexer.ResultSymbol = 18
		lexer.MarkEnd()
		return result
	case 74:
		result = true
		lexer.ResultSymbol = 20
		lexer.MarkEnd()
		return result
	case 75:
		result = true
		lexer.ResultSymbol = 20
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 86
			goto nextState
		}
		return result
	case 76:
		result = true
		lexer.ResultSymbol = 22
		lexer.MarkEnd()
		return result
	case 77:
		result = true
		lexer.ResultSymbol = 23
		lexer.MarkEnd()
		return result
	case 78:
		result = true
		lexer.ResultSymbol = 24
		lexer.MarkEnd()
		return result
	case 79:
		result = true
		lexer.ResultSymbol = 26
		lexer.MarkEnd()
		return result
	case 80:
		result = true
		lexer.ResultSymbol = 26
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 95
			goto nextState
		}
		if (lookahead == 124) {
			state = 133
			goto nextState
		}
		return result
	case 81:
		result = true
		lexer.ResultSymbol = 26
		lexer.MarkEnd()
		if (lookahead == 124) {
			state = 133
			goto nextState
		}
		return result
	case 82:
		result = true
		lexer.ResultSymbol = 29
		lexer.MarkEnd()
		return result
	case 83:
		result = true
		lexer.ResultSymbol = 30
		lexer.MarkEnd()
		return result
	case 84:
		result = true
		lexer.ResultSymbol = 31
		lexer.MarkEnd()
		return result
	case 85:
		result = true
		lexer.ResultSymbol = 32
		lexer.MarkEnd()
		return result
	case 86:
		result = true
		lexer.ResultSymbol = 33
		lexer.MarkEnd()
		return result
	case 87:
		result = true
		lexer.ResultSymbol = 34
		lexer.MarkEnd()
		return result
	case 88:
		result = true
		lexer.ResultSymbol = 35
		lexer.MarkEnd()
		return result
	case 89:
		result = true
		lexer.ResultSymbol = 36
		lexer.MarkEnd()
		return result
	case 90:
		result = true
		lexer.ResultSymbol = 37
		lexer.MarkEnd()
		return result
	case 91:
		result = true
		lexer.ResultSymbol = 38
		lexer.MarkEnd()
		return result
	case 92:
		result = true
		lexer.ResultSymbol = 39
		lexer.MarkEnd()
		return result
	case 93:
		result = true
		lexer.ResultSymbol = 40
		lexer.MarkEnd()
		return result
	case 94:
		result = true
		lexer.ResultSymbol = 41
		lexer.MarkEnd()
		return result
	case 95:
		result = true
		lexer.ResultSymbol = 42
		lexer.MarkEnd()
		return result
	case 96:
		result = true
		lexer.ResultSymbol = 43
		lexer.MarkEnd()
		return result
	case 97:
		result = true
		lexer.ResultSymbol = 44
		lexer.MarkEnd()
		return result
	case 98:
		result = true
		lexer.ResultSymbol = 44
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 83
			goto nextState
		}
		return result
	case 99:
		result = true
		lexer.ResultSymbol = 62
		lexer.MarkEnd()
		return result
	case 100:
		result = true
		lexer.ResultSymbol = 62
		lexer.MarkEnd()
		if (lookahead == 43) {
			state = 84
			goto nextState
		}
		if (lookahead == 61) {
			state = 93
			goto nextState
		}
		return result
	case 101:
		result = true
		lexer.ResultSymbol = 62
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 93
			goto nextState
		}
		return result
	case 102:
		result = true
		lexer.ResultSymbol = 63
		lexer.MarkEnd()
		return result
	case 103:
		result = true
		lexer.ResultSymbol = 63
		lexer.MarkEnd()
		if (lookahead == 45) {
			state = 85
			goto nextState
		}
		if (lookahead == 61) {
			state = 94
			goto nextState
		}
		return result
	case 104:
		result = true
		lexer.ResultSymbol = 63
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 94
			goto nextState
		}
		return result
	case 105:
		result = true
		lexer.ResultSymbol = 64
		lexer.MarkEnd()
		return result
	case 106:
		result = true
		lexer.ResultSymbol = 64
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 123
			goto nextState
		}
		return result
	case 107:
		result = true
		lexer.ResultSymbol = 65
		lexer.MarkEnd()
		return result
	case 108:
		result = true
		lexer.ResultSymbol = 65
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 96
			goto nextState
		}
		return result
	case 109:
		result = true
		lexer.ResultSymbol = 66
		lexer.MarkEnd()
		return result
	case 110:
		result = true
		lexer.ResultSymbol = 66
		lexer.MarkEnd()
		if (lookahead == 38) {
			state = 132
			goto nextState
		}
		if (lookahead == 61) {
			state = 91
			goto nextState
		}
		if (lookahead == 94) {
			state = 121
			goto nextState
		}
		return result
	case 111:
		result = true
		lexer.ResultSymbol = 66
		lexer.MarkEnd()
		if (lookahead == 38) {
			state = 132
			goto nextState
		}
		if (lookahead == 94) {
			state = 120
			goto nextState
		}
		return result
	case 112:
		result = true
		lexer.ResultSymbol = 67
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 10
			goto nextState
		}
		if (lookahead == 47) {
			state = 164
			goto nextState
		}
		return result
	case 113:
		result = true
		lexer.ResultSymbol = 67
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 10
			goto nextState
		}
		if (lookahead == 47) {
			state = 164
			goto nextState
		}
		if (lookahead == 61) {
			state = 87
			goto nextState
		}
		return result
	case 114:
		result = true
		lexer.ResultSymbol = 68
		lexer.MarkEnd()
		return result
	case 115:
		result = true
		lexer.ResultSymbol = 68
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 88
			goto nextState
		}
		return result
	case 116:
		result = true
		lexer.ResultSymbol = 69
		lexer.MarkEnd()
		return result
	case 117:
		result = true
		lexer.ResultSymbol = 69
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 89
			goto nextState
		}
		return result
	case 118:
		result = true
		lexer.ResultSymbol = 70
		lexer.MarkEnd()
		return result
	case 119:
		result = true
		lexer.ResultSymbol = 70
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 90
			goto nextState
		}
		return result
	case 120:
		result = true
		lexer.ResultSymbol = 71
		lexer.MarkEnd()
		return result
	case 121:
		result = true
		lexer.ResultSymbol = 71
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 92
			goto nextState
		}
		return result
	case 122:
		result = true
		lexer.ResultSymbol = 72
		lexer.MarkEnd()
		return result
	case 123:
		result = true
		lexer.ResultSymbol = 73
		lexer.MarkEnd()
		return result
	case 124:
		result = true
		lexer.ResultSymbol = 74
		lexer.MarkEnd()
		if (lookahead == 45) {
			state = 82
			goto nextState
		}
		if (lookahead == 60) {
			state = 117
			goto nextState
		}
		if (lookahead == 61) {
			state = 128
			goto nextState
		}
		return result
	case 125:
		result = true
		lexer.ResultSymbol = 74
		lexer.MarkEnd()
		if (lookahead == 45) {
			state = 82
			goto nextState
		}
		if (lookahead == 60) {
			state = 116
			goto nextState
		}
		if (lookahead == 61) {
			state = 128
			goto nextState
		}
		return result
	case 126:
		result = true
		lexer.ResultSymbol = 74
		lexer.MarkEnd()
		if (lookahead == 60) {
			state = 117
			goto nextState
		}
		if (lookahead == 61) {
			state = 128
			goto nextState
		}
		return result
	case 127:
		result = true
		lexer.ResultSymbol = 74
		lexer.MarkEnd()
		if (lookahead == 60) {
			state = 116
			goto nextState
		}
		if (lookahead == 61) {
			state = 128
			goto nextState
		}
		return result
	case 128:
		result = true
		lexer.ResultSymbol = 75
		lexer.MarkEnd()
		return result
	case 129:
		result = true
		lexer.ResultSymbol = 76
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 131
			goto nextState
		}
		if (lookahead == 62) {
			state = 119
			goto nextState
		}
		return result
	case 130:
		result = true
		lexer.ResultSymbol = 76
		lexer.MarkEnd()
		if (lookahead == 61) {
			state = 131
			goto nextState
		}
		if (lookahead == 62) {
			state = 118
			goto nextState
		}
		return result
	case 131:
		result = true
		lexer.ResultSymbol = 77
		lexer.MarkEnd()
		return result
	case 132:
		result = true
		lexer.ResultSymbol = 78
		lexer.MarkEnd()
		return result
	case 133:
		result = true
		lexer.ResultSymbol = 79
		lexer.MarkEnd()
		return result
	case 134:
		result = true
		lexer.ResultSymbol = 1
		lexer.MarkEnd()
		if ts.SetContains(characterSets[1], lookahead) {
			state = 134
			goto nextState
		}
		return result
	case 135:
		result = true
		lexer.ResultSymbol = 80
		lexer.MarkEnd()
		return result
	case 136:
		result = true
		lexer.ResultSymbol = 81
		lexer.MarkEnd()
		if (lookahead == 10) {
			state = 141
			goto nextState
		}
		if ((lookahead != 0) && (lookahead != 96)) {
			state = 136
			goto nextState
		}
		return result
	case 137:
		result = true
		lexer.ResultSymbol = 81
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 139
			goto nextState
		}
		if (lookahead == 47) {
			state = 136
			goto nextState
		}
		if ((lookahead != 0) && (lookahead != 96)) {
			state = 141
			goto nextState
		}
		return result
	case 138:
		result = true
		lexer.ResultSymbol = 81
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 138
			goto nextState
		}
		if (lookahead == 47) {
			state = 141
			goto nextState
		}
		if ((lookahead != 0) && (lookahead != 96)) {
			state = 139
			goto nextState
		}
		return result
	case 139:
		result = true
		lexer.ResultSymbol = 81
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 138
			goto nextState
		}
		if ((lookahead != 0) && (lookahead != 96)) {
			state = 139
			goto nextState
		}
		return result
	case 140:
		result = true
		lexer.ResultSymbol = 81
		lexer.MarkEnd()
		if (lookahead == 47) {
			state = 137
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			state = 140
			goto nextState
		}
		if ((lookahead != 0) && (lookahead != 96)) {
			state = 141
			goto nextState
		}
		return result
	case 141:
		result = true
		lexer.ResultSymbol = 81
		lexer.MarkEnd()
		if ((lookahead != 0) && (lookahead != 96)) {
			state = 141
			goto nextState
		}
		return result
	case 142:
		result = true
		lexer.ResultSymbol = 82
		lexer.MarkEnd()
		return result
	case 143:
		result = true
		lexer.ResultSymbol = 83
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 145
			goto nextState
		}
		if (lookahead == 47) {
			state = 147
			goto nextState
		}
		if ((((lookahead != 0) && (lookahead != 10)) && (lookahead != 34)) && (lookahead != 92)) {
			state = 147
			goto nextState
		}
		return result
	case 144:
		result = true
		lexer.ResultSymbol = 83
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 144
			goto nextState
		}
		if (lookahead == 47) {
			state = 147
			goto nextState
		}
		if ((((lookahead != 0) && (lookahead != 10)) && (lookahead != 34)) && (lookahead != 92)) {
			state = 145
			goto nextState
		}
		return result
	case 145:
		result = true
		lexer.ResultSymbol = 83
		lexer.MarkEnd()
		if (lookahead == 42) {
			state = 144
			goto nextState
		}
		if ((((lookahead != 0) && (lookahead != 10)) && (lookahead != 34)) && (lookahead != 92)) {
			state = 145
			goto nextState
		}
		return result
	case 146:
		result = true
		lexer.ResultSymbol = 83
		lexer.MarkEnd()
		if (lookahead == 47) {
			state = 143
			goto nextState
		}
		if (((lookahead == 9) || ((11 <= lookahead) && (lookahead <= 13))) || (lookahead == 32)) {
			state = 146
			goto nextState
		}
		if ((((lookahead != 0) && ((lookahead < 9) || (13 < lookahead))) && (lookahead != 34)) && (lookahead != 92)) {
			state = 147
			goto nextState
		}
		return result
	case 147:
		result = true
		lexer.ResultSymbol = 83
		lexer.MarkEnd()
		if ((((lookahead != 0) && (lookahead != 10)) && (lookahead != 34)) && (lookahead != 92)) {
			state = 147
			goto nextState
		}
		return result
	case 148:
		result = true
		lexer.ResultSymbol = 84
		lexer.MarkEnd()
		return result
	case 149:
		result = true
		lexer.ResultSymbol = 85
		lexer.MarkEnd()
		return result
	case 150:
		result = true
		lexer.ResultSymbol = 85
		lexer.MarkEnd()
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 149
			goto nextState
		}
		return result
	case 151:
		result = true
		lexer.ResultSymbol = 85
		lexer.MarkEnd()
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 150
			goto nextState
		}
		return result
	case 152:
		result = true
		lexer.ResultSymbol = 86
		lexer.MarkEnd()
		switch lookahead {
		case 46:
			state = 160
			goto nextState
		case 95:
			state = 29
			goto nextState
		case 105:
			state = 161
			goto nextState
		case 66:
			state = 23
			goto nextState
		case 98:
			state = 23
			goto nextState
		case 69:
			state = 26
			goto nextState
		case 101:
			state = 26
			goto nextState
		case 79:
			state = 25
			goto nextState
		case 111:
			state = 25
			goto nextState
		case 88:
			state = 15
			goto nextState
		case 120:
			state = 15
			goto nextState
		case 56:
			state = 13
			goto nextState
		case 57:
			state = 13
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 55)) {
			state = 153
			goto nextState
		}
		return result
	case 153:
		result = true
		lexer.ResultSymbol = 86
		lexer.MarkEnd()
		if (lookahead == 46) {
			state = 160
			goto nextState
		}
		if (lookahead == 95) {
			state = 29
			goto nextState
		}
		if (lookahead == 105) {
			state = 161
			goto nextState
		}
		if ((lookahead == 69) || (lookahead == 101)) {
			state = 26
			goto nextState
		}
		if ((lookahead == 56) || (lookahead == 57)) {
			state = 13
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 55)) {
			state = 153
			goto nextState
		}
		return result
	case 154:
		result = true
		lexer.ResultSymbol = 86
		lexer.MarkEnd()
		if (lookahead == 46) {
			state = 160
			goto nextState
		}
		if (lookahead == 95) {
			state = 33
			goto nextState
		}
		if (lookahead == 105) {
			state = 161
			goto nextState
		}
		if ((lookahead == 69) || (lookahead == 101)) {
			state = 26
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 154
			goto nextState
		}
		return result
	case 155:
		result = true
		lexer.ResultSymbol = 86
		lexer.MarkEnd()
		if (lookahead == 46) {
			state = 27
			goto nextState
		}
		if (lookahead == 95) {
			state = 39
			goto nextState
		}
		if (lookahead == 105) {
			state = 161
			goto nextState
		}
		if ((lookahead == 80) || (lookahead == 112)) {
			state = 26
			goto nextState
		}
		if ((((48 <= lookahead) && (lookahead <= 57)) || ((65 <= lookahead) && (lookahead <= 70))) || ((97 <= lookahead) && (lookahead <= 102))) {
			state = 155
			goto nextState
		}
		return result
	case 156:
		result = true
		lexer.ResultSymbol = 86
		lexer.MarkEnd()
		if (lookahead == 95) {
			state = 28
			goto nextState
		}
		if (lookahead == 105) {
			state = 161
			goto nextState
		}
		if ((lookahead == 48) || (lookahead == 49)) {
			state = 156
			goto nextState
		}
		return result
	case 157:
		result = true
		lexer.ResultSymbol = 86
		lexer.MarkEnd()
		if (lookahead == 95) {
			state = 31
			goto nextState
		}
		if (lookahead == 105) {
			state = 161
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 55)) {
			state = 157
			goto nextState
		}
		return result
	case 158:
		result = true
		lexer.ResultSymbol = 87
		lexer.MarkEnd()
		if (lookahead == 95) {
			state = 34
			goto nextState
		}
		if (lookahead == 105) {
			state = 161
			goto nextState
		}
		if ((lookahead == 69) || (lookahead == 101)) {
			state = 26
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 158
			goto nextState
		}
		return result
	case 159:
		result = true
		lexer.ResultSymbol = 87
		lexer.MarkEnd()
		if (lookahead == 95) {
			state = 36
			goto nextState
		}
		if (lookahead == 105) {
			state = 161
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 159
			goto nextState
		}
		return result
	case 160:
		result = true
		lexer.ResultSymbol = 87
		lexer.MarkEnd()
		if (lookahead == 105) {
			state = 161
			goto nextState
		}
		if ((lookahead == 69) || (lookahead == 101)) {
			state = 26
			goto nextState
		}
		if ((48 <= lookahead) && (lookahead <= 57)) {
			state = 158
			goto nextState
		}
		return result
	case 161:
		result = true
		lexer.ResultSymbol = 88
		lexer.MarkEnd()
		return result
	case 162:
		result = true
		lexer.ResultSymbol = 89
		lexer.MarkEnd()
		return result
	case 163:
		result = true
		lexer.ResultSymbol = 94
		lexer.MarkEnd()
		return result
	case 164:
		result = true
		lexer.ResultSymbol = 94
		lexer.MarkEnd()
		if ((lookahead != 0) && (lookahead != 10)) {
			state = 164
			goto nextState
		}
		return result
	default:
		return false
	}
}

func tsLexKeywords(lexer *ts.Lexer, state ts.StateID) bool {
	result := false
	skip := false
	eof := false
	var lookahead int32
	_, _ = eof, lookahead
	goto start
nextState:
	lexer.Advance(skip)
start:
	skip = false
	lookahead = lexer.Lookahead
	eof = lexer.EOF()
	switch state {
	case 0:
		switch lookahead {
		case 95:
			state = 1
			goto nextState
		case 98:
			state = 2
			goto nextState
		case 99:
			state = 3
			goto nextState
		case 100:
			state = 4
			goto nextState
		case 101:
			state = 5
			goto nextState
		case 102:
			state = 6
			goto nextState
		case 103:
			state = 7
			goto nextState
		case 105:
			state = 8
			goto nextState
		case 109:
			state = 9
			goto nextState
		case 110:
			state = 10
			goto nextState
		case 112:
			state = 11
			goto nextState
		case 114:
			state = 12
			goto nextState
		case 115:
			state = 13
			goto nextState
		case 116:
			state = 14
			goto nextState
		case 118:
			state = 15
			goto nextState
		}
		if (((9 <= lookahead) && (lookahead <= 13)) || (lookahead == 32)) {
			skip = true
			state = 0
			goto nextState
		}
		return result
	case 1:
		result = true
		lexer.ResultSymbol = 8
		lexer.MarkEnd()
		return result
	case 2:
		if (lookahead == 114) {
			state = 16
			goto nextState
		}
		return result
	case 3:
		if (lookahead == 97) {
			state = 17
			goto nextState
		}
		if (lookahead == 104) {
			state = 18
			goto nextState
		}
		if (lookahead == 111) {
			state = 19
			goto nextState
		}
		return result
	case 4:
		if (lookahead == 101) {
			state = 20
			goto nextState
		}
		return result
	case 5:
		if (lookahead == 108) {
			state = 21
			goto nextState
		}
		return result
	case 6:
		if (lookahead == 97) {
			state = 22
			goto nextState
		}
		if (lookahead == 111) {
			state = 23
			goto nextState
		}
		if (lookahead == 117) {
			state = 24
			goto nextState
		}
		return result
	case 7:
		if (lookahead == 111) {
			state = 25
			goto nextState
		}
		return result
	case 8:
		if (lookahead == 102) {
			state = 26
			goto nextState
		}
		if (lookahead == 109) {
			state = 27
			goto nextState
		}
		if (lookahead == 110) {
			state = 28
			goto nextState
		}
		if (lookahead == 111) {
			state = 29
			goto nextState
		}
		return result
	case 9:
		if (lookahead == 97) {
			state = 30
			goto nextState
		}
		return result
	case 10:
		if (lookahead == 101) {
			state = 31
			goto nextState
		}
		if (lookahead == 105) {
			state = 32
			goto nextState
		}
		return result
	case 11:
		if (lookahead == 97) {
			state = 33
			goto nextState
		}
		return result
	case 12:
		if (lookahead == 97) {
			state = 34
			goto nextState
		}
		if (lookahead == 101) {
			state = 35
			goto nextState
		}
		return result
	case 13:
		if (lookahead == 101) {
			state = 36
			goto nextState
		}
		if (lookahead == 116) {
			state = 37
			goto nextState
		}
		if (lookahead == 119) {
			state = 38
			goto nextState
		}
		return result
	case 14:
		if (lookahead == 114) {
			state = 39
			goto nextState
		}
		if (lookahead == 121) {
			state = 40
			goto nextState
		}
		return result
	case 15:
		if (lookahead == 97) {
			state = 41
			goto nextState
		}
		return result
	case 16:
		if (lookahead == 101) {
			state = 42
			goto nextState
		}
		return result
	case 17:
		if (lookahead == 115) {
			state = 43
			goto nextState
		}
		return result
	case 18:
		if (lookahead == 97) {
			state = 44
			goto nextState
		}
		return result
	case 19:
		if (lookahead == 110) {
			state = 45
			goto nextState
		}
		return result
	case 20:
		if (lookahead == 102) {
			state = 46
			goto nextState
		}
		return result
	case 21:
		if (lookahead == 115) {
			state = 47
			goto nextState
		}
		return result
	case 22:
		if (lookahead == 108) {
			state = 48
			goto nextState
		}
		return result
	case 23:
		if (lookahead == 114) {
			state = 49
			goto nextState
		}
		return result
	case 24:
		if (lookahead == 110) {
			state = 50
			goto nextState
		}
		return result
	case 25:
		result = true
		lexer.ResultSymbol = 50
		lexer.MarkEnd()
		if (lookahead == 116) {
			state = 51
			goto nextState
		}
		return result
	case 26:
		result = true
		lexer.ResultSymbol = 52
		lexer.MarkEnd()
		return result
	case 27:
		if (lookahead == 112) {
			state = 52
			goto nextState
		}
		return result
	case 28:
		if (lookahead == 116) {
			state = 53
			goto nextState
		}
		return result
	case 29:
		if (lookahead == 116) {
			state = 54
			goto nextState
		}
		return result
	case 30:
		if (lookahead == 107) {
			state = 55
			goto nextState
		}
		if (lookahead == 112) {
			state = 56
			goto nextState
		}
		return result
	case 31:
		if (lookahead == 119) {
			state = 57
			goto nextState
		}
		return result
	case 32:
		if (lookahead == 108) {
			state = 58
			goto nextState
		}
		return result
	case 33:
		if (lookahead == 99) {
			state = 59
			goto nextState
		}
		return result
	case 34:
		if (lookahead == 110) {
			state = 60
			goto nextState
		}
		return result
	case 35:
		if (lookahead == 116) {
			state = 61
			goto nextState
		}
		return result
	case 36:
		if (lookahead == 108) {
			state = 62
			goto nextState
		}
		return result
	case 37:
		if (lookahead == 114) {
			state = 63
			goto nextState
		}
		return result
	case 38:
		if (lookahead == 105) {
			state = 64
			goto nextState
		}
		return result
	case 39:
		if (lookahead == 117) {
			state = 65
			goto nextState
		}
		return result
	case 40:
		if (lookahead == 112) {
			state = 66
			goto nextState
		}
		return result
	case 41:
		if (lookahead == 114) {
			state = 67
			goto nextState
		}
		return result
	case 42:
		if (lookahead == 97) {
			state = 68
			goto nextState
		}
		return result
	case 43:
		if (lookahead == 101) {
			state = 69
			goto nextState
		}
		return result
	case 44:
		if (lookahead == 110) {
			state = 70
			goto nextState
		}
		return result
	case 45:
		if (lookahead == 115) {
			state = 71
			goto nextState
		}
		if (lookahead == 116) {
			state = 72
			goto nextState
		}
		return result
	case 46:
		if (lookahead == 97) {
			state = 73
			goto nextState
		}
		if (lookahead == 101) {
			state = 74
			goto nextState
		}
		return result
	case 47:
		if (lookahead == 101) {
			state = 75
			goto nextState
		}
		return result
	case 48:
		if (lookahead == 108) {
			state = 76
			goto nextState
		}
		if (lookahead == 115) {
			state = 77
			goto nextState
		}
		return result
	case 49:
		result = true
		lexer.ResultSymbol = 54
		lexer.MarkEnd()
		return result
	case 50:
		if (lookahead == 99) {
			state = 78
			goto nextState
		}
		return result
	case 51:
		if (lookahead == 111) {
			state = 79
			goto nextState
		}
		return result
	case 52:
		if (lookahead == 111) {
			state = 80
			goto nextState
		}
		return result
	case 53:
		if (lookahead == 101) {
			state = 81
			goto nextState
		}
		return result
	case 54:
		if (lookahead == 97) {
			state = 82
			goto nextState
		}
		return result
	case 55:
		if (lookahead == 101) {
			state = 83
			goto nextState
		}
		return result
	case 56:
		result = true
		lexer.ResultSymbol = 27
		lexer.MarkEnd()
		return result
	case 57:
		result = true
		lexer.ResultSymbol = 60
		lexer.MarkEnd()
		return result
	case 58:
		result = true
		lexer.ResultSymbol = 90
		lexer.MarkEnd()
		return result
	case 59:
		if (lookahead == 107) {
			state = 84
			goto nextState
		}
		return result
	case 60:
		if (lookahead == 103) {
			state = 85
			goto nextState
		}
		return result
	case 61:
		if (lookahead == 117) {
			state = 86
			goto nextState
		}
		return result
	case 62:
		if (lookahead == 101) {
			state = 87
			goto nextState
		}
		return result
	case 63:
		if (lookahead == 117) {
			state = 88
			goto nextState
		}
		return result
	case 64:
		if (lookahead == 116) {
			state = 89
			goto nextState
		}
		return result
	case 65:
		if (lookahead == 101) {
			state = 90
			goto nextState
		}
		return result
	case 66:
		if (lookahead == 101) {
			state = 91
			goto nextState
		}
		return result
	case 67:
		result = true
		lexer.ResultSymbol = 14
		lexer.MarkEnd()
		return result
	case 68:
		if (lookahead == 107) {
			state = 92
			goto nextState
		}
		return result
	case 69:
		result = true
		lexer.ResultSymbol = 57
		lexer.MarkEnd()
		return result
	case 70:
		result = true
		lexer.ResultSymbol = 28
		lexer.MarkEnd()
		return result
	case 71:
		if (lookahead == 116) {
			state = 93
			goto nextState
		}
		return result
	case 72:
		if (lookahead == 105) {
			state = 94
			goto nextState
		}
		return result
	case 73:
		if (lookahead == 117) {
			state = 95
			goto nextState
		}
		return result
	case 74:
		if (lookahead == 114) {
			state = 96
			goto nextState
		}
		return result
	case 75:
		result = true
		lexer.ResultSymbol = 53
		lexer.MarkEnd()
		return result
	case 76:
		if (lookahead == 116) {
			state = 97
			goto nextState
		}
		return result
	case 77:
		if (lookahead == 101) {
			state = 98
			goto nextState
		}
		return result
	case 78:
		result = true
		lexer.ResultSymbol = 15
		lexer.MarkEnd()
		return result
	case 79:
		result = true
		lexer.ResultSymbol = 48
		lexer.MarkEnd()
		return result
	case 80:
		if (lookahead == 114) {
			state = 99
			goto nextState
		}
		return result
	case 81:
		if (lookahead == 114) {
			state = 100
			goto nextState
		}
		return result
	case 82:
		result = true
		lexer.ResultSymbol = 93
		lexer.MarkEnd()
		return result
	case 83:
		result = true
		lexer.ResultSymbol = 61
		lexer.MarkEnd()
		return result
	case 84:
		if (lookahead == 97) {
			state = 101
			goto nextState
		}
		return result
	case 85:
		if (lookahead == 101) {
			state = 102
			goto nextState
		}
		return result
	case 86:
		if (lookahead == 114) {
			state = 103
			goto nextState
		}
		return result
	case 87:
		if (lookahead == 99) {
			state = 104
			goto nextState
		}
		return result
	case 88:
		if (lookahead == 99) {
			state = 105
			goto nextState
		}
		return result
	case 89:
		if (lookahead == 99) {
			state = 106
			goto nextState
		}
		return result
	case 90:
		result = true
		lexer.ResultSymbol = 91
		lexer.MarkEnd()
		return result
	case 91:
		result = true
		lexer.ResultSymbol = 19
		lexer.MarkEnd()
		return result
	case 92:
		result = true
		lexer.ResultSymbol = 46
		lexer.MarkEnd()
		return result
	case 93:
		result = true
		lexer.ResultSymbol = 11
		lexer.MarkEnd()
		return result
	case 94:
		if (lookahead == 110) {
			state = 107
			goto nextState
		}
		return result
	case 95:
		if (lookahead == 108) {
			state = 108
			goto nextState
		}
		return result
	case 96:
		result = true
		lexer.ResultSymbol = 51
		lexer.MarkEnd()
		return result
	case 97:
		if (lookahead == 104) {
			state = 109
			goto nextState
		}
		return result
	case 98:
		result = true
		lexer.ResultSymbol = 92
		lexer.MarkEnd()
		return result
	case 99:
		if (lookahead == 116) {
			state = 110
			goto nextState
		}
		return result
	case 100:
		if (lookahead == 102) {
			state = 111
			goto nextState
		}
		return result
	case 101:
		if (lookahead == 103) {
			state = 112
			goto nextState
		}
		return result
	case 102:
		result = true
		lexer.ResultSymbol = 55
		lexer.MarkEnd()
		return result
	case 103:
		if (lookahead == 110) {
			state = 113
			goto nextState
		}
		return result
	case 104:
		if (lookahead == 116) {
			state = 114
			goto nextState
		}
		return result
	case 105:
		if (lookahead == 116) {
			state = 115
			goto nextState
		}
		return result
	case 106:
		if (lookahead == 104) {
			state = 116
			goto nextState
		}
		return result
	case 107:
		if (lookahead == 117) {
			state = 117
			goto nextState
		}
		return result
	case 108:
		if (lookahead == 116) {
			state = 118
			goto nextState
		}
		return result
	case 109:
		if (lookahead == 114) {
			state = 119
			goto nextState
		}
		return result
	case 110:
		result = true
		lexer.ResultSymbol = 6
		lexer.MarkEnd()
		return result
	case 111:
		if (lookahead == 97) {
			state = 120
			goto nextState
		}
		return result
	case 112:
		if (lookahead == 101) {
			state = 121
			goto nextState
		}
		return result
	case 113:
		result = true
		lexer.ResultSymbol = 49
		lexer.MarkEnd()
		return result
	case 114:
		result = true
		lexer.ResultSymbol = 59
		lexer.MarkEnd()
		return result
	case 115:
		result = true
		lexer.ResultSymbol = 21
		lexer.MarkEnd()
		return result
	case 116:
		result = true
		lexer.ResultSymbol = 56
		lexer.MarkEnd()
		return result
	case 117:
		if (lookahead == 101) {
			state = 122
			goto nextState
		}
		return result
	case 118:
		result = true
		lexer.ResultSymbol = 58
		lexer.MarkEnd()
		return result
	case 119:
		if (lookahead == 111) {
			state = 123
			goto nextState
		}
		return result
	case 120:
		if (lookahead == 99) {
			state = 124
			goto nextState
		}
		return result
	case 121:
		result = true
		lexer.ResultSymbol = 5
		lexer.MarkEnd()
		return result
	case 122:
		result = true
		lexer.ResultSymbol = 47
		lexer.MarkEnd()
		return result
	case 123:
		if (lookahead == 117) {
			state = 125
			goto nextState
		}
		return result
	case 124:
		if (lookahead == 101) {
			state = 126
			goto nextState
		}
		return result
	case 125:
		if (lookahead == 103) {
			state = 127
			goto nextState
		}
		return result
	case 126:
		result = true
		lexer.ResultSymbol = 25
		lexer.MarkEnd()
		return result
	case 127:
		if (lookahead == 104) {
			state = 128
			goto nextState
		}
		return result
	case 128:
		result = true
		lexer.ResultSymbol = 45
		lexer.MarkEnd()
		return result
	default:
		return false
	}
}

func loadTables() *ts.Language {
	tables, err := ts.DecodeTables(tablesBlob)
	if err != nil {
		panic("golang: reading tables.zst: " + err.Error())
	}
	characterSets = tables.CharacterSets
	language := &tables.Language
	language.LexFn = tsLex
	language.KeywordLexFn = tsLexKeywords
	return language
}

var (
	loadOnce  sync.Once
	generated *ts.Language
)

// Language returns the golang grammar, decoding its tables when a
// parse needs them.
func Language() *ts.Language {
	loadOnce.Do(func() { generated = loadTables() })
	return generated
}
